Feature/ie11 deprecation
boltdesignsystem/bolt pull request #1801
Opened 2020-03-30 14:01 UTC by danielamorse

## Jira

http://vjira2:8080/browse/BDS-2026

## Summary

(Enter a one-line summary of the changes in this PR.  This will be included in the release notes)

## Details

(Explain the changes in enough detail fo reviewers to understand.  Raise any questions for reviewers to consider.)

## How to test

(List clear steps to test that the changes are working)

2020-04-08 20:36 UTC, sghoweri commented on packages/build-tools/create-webpack-config.js
> +        '@bolt/polyfills',
@danielamorse if we're only supporting Edge 79 and later than this line can get 100% removed, otherwise shouldn't this really be pointing to `'@bolt/polyfills/modern.js',`?

2020-04-08 21:47 UTC, danielamorse commented on packages/build-tools/create-webpack-config.js
> +        '@bolt/polyfills',
@sghoweri good call. We _are_ only supporting 79 and later, correct? Current version is 80 and we support last 2 browsers.

Previous versions of Edge just used the Custom Elements polyfill, right? https://caniuse.com/#feat=custom-elementsv1

2020-04-08 22:01 UTC, danielamorse commented
> 1. Check out my comment regarding the `@bolt/polyfills` package that's auto-added to the Webpack entry (might need to switch the path)
Replied with a question.

> 2. Any reason why you didn't remove this entire package as well in this PR? https://github.com/boltdesignsystem/bolt/tree/master/packages/components/bolt-critical-path-polyfills
I have a follow-up PR that removes unused Polyfills and dependencies. I'll remove it there, just trying to keep this initial PR as slim as possibile.

> 3. Make sure to resolve the merge conflicts + pull in the latest from master (_probably_ resolving using your code vs the code from master...)
Done 👍

2020-04-30 01:40 UTC, danielamorse commented on packages/build-tools/create-webpack-config.js
> +        '@bolt/polyfills',
@sghoweri would you please confirm that we no longer need to include `@bolt/polyfills`?

2020-04-30 01:42 UTC, danielamorse commented on packages/base-starter-kit/.boltrc.js
>        '@bolt/components-critical-css',
@sghoweri I know to remove `critical-css-vars` but should I also remove `critical-css`? That package doesn't appear to do anything but add support for async CSS loading. Where's the real critical-css happen?

2020-04-30 02:23 UTC, sghoweri commented on packages/build-tools/create-webpack-config.js
> +        '@bolt/polyfills',
Just to confirm / clarify @danielamorse: 

Are you asking if its OK to replace `@bolt/polyfills` with `@bolt/polyfills/modern.js` (aka we ARE supporting older versions of Edge pre-Chromium) OR are you asking if its OK to remove `@bolt/polyfills` entirely (meaning, we are ONLY supporting Edge 79 and up)?

2020-04-30 02:28 UTC, sghoweri commented on packages/base-starter-kit/.boltrc.js
>        '@bolt/components-critical-css',
I'd recommend removing it from here (and in the starter kit's package.json) but perhaps keep the package itself in our repo for now.

My most recent implementations of Critical CSS are 100% automated (including injecting the code that handles asyncing the CSS) so it's a little unlikely that we'd end up using this package (vs sometime entirely different)... 🤔 

Lmk if you need more info on this!

2020-10-06 19:07 UTC, danielamorse commented on packages/build-tools/create-webpack-config.js
> +        '@bolt/polyfills',
Leaving as is for now. Will address in https://pegadigitalit.atlassian.net/browse/DS-235.

2020-10-07 17:04 UTC, colbytcook commented on packages/components/bolt-card-replacement/src/card-replacement/card-replacement.scss
> +    // Note: at of v3.0 no longer uses themify to set variable token
as*

2020-10-07 17:05 UTC, colbytcook commented on packages/components/bolt-card-replacement/src/card-replacement/card-replacement.scss
>    // Non-themed card-replacement color settings.
Does this file require any changes or does this just need a comment here?

2020-10-07 17:06 UTC, colbytcook commented on packages/components/bolt-card-replacement/src/card-replacement/card-replacement.scss
>    // Non-themed card-replacement color settings.
nevermind, I saw this is being added other places

2020-10-07 17:07 UTC, colbytcook commented on packages/components/bolt-card-replacement/src/card-replacement/card-replacement.scss
> +    // Note: at of v3.0 no longer uses themify to set variable token
Not going to list this on all examples, but I recommend doing a search for this string

2020-10-07 17:08 UTC, colbytcook commented on packages/components/bolt-nav-priority/nav-priority.scss
> +
Is this supposed to be in the IE 11 fix?

2020-10-07 17:22 UTC, colbytcook commented
Lets make sure to merge in https://github.com/boltdesignsystem/bolt/pull/1846 before this gets merge

2020-10-07 17:23 UTC, colbytcook requested changes
Lets make sure the typo and the merge gets done before this is merged

2020-10-07 20:34 UTC, danielamorse reviewed
> Lets make sure to merge in #1846 before this gets merge

As I mentioned in chat, that will be handled separately, merged into `feature/v3.0-rc.2`: https://github.com/boltdesignsystem/bolt/pull/1846#issuecomment-705168795

2020-10-07 20:34 UTC, danielamorse commented on packages/components/bolt-nav-priority/nav-priority.scss
> +
Good question, yes. After changing line `134` this pseudo element gives us roughly the same effect as it had before but without the themify magic.

2020-10-07 20:43 UTC, colbytcook commented on packages/components/bolt-nav-priority/nav-priority.scss
> +
sounds good to me, thanks

2020-10-07 20:43 UTC, colbytcook approved these changes

2020-10-08 14:53 UTC, mikemai2awesome requested changes

2020-10-08 14:53 UTC, mikemai2awesome commented on packages/components/bolt-nav-priority/nav-priority.scss
> +  background-color: bolt-theme(background);
There's just one problem with this, when background color is white, you end up with white on white.

2020-10-08 15:06 UTC, mikemai2awesome commented on packages/components/bolt-nav-priority/nav-priority.scss
> +  background-color: bolt-theme(background);
NVM, white on white is intended for that theme.

2020-10-08 15:06 UTC, mikemai2awesome approved these changes

2020-10-08 15:13 UTC, merged