DS-149 Fix Modal focus
boltdesignsystem/bolt pull request #1983
Opened 2020-09-23 14:15 UTC by danielamorse

## Jira

https://pegadigitalit.atlassian.net/browse/DS-149

## Summary

Properly set initial focus when modal first opens.

## Details

On open, modal now focuses on 1) the built-in close button 2) the first element with `autofocus` attribute or 3) the first focusable element, in that order.

I updated the persistent modal demo so that the custom close button has `autofocus`.

> Note: @mikemai2awesome in the persistent demo the custom close button _does_ get focus, but the focus style doesn't seem to apply unless you tab onto it. If I add an explicit `.c-bolt-link:focus` style to the Link SCSS that style _does_ work.

## How to test

- Review code changes
- Review Modal demos and verify the expected element gets focus on open.

2020-09-23 17:20 UTC, remydenton approved these changes
This looks sensible to me, though please don't merge without approval from @mikemai2awesome.

I was going to remark on the following weirdness, but see you already noted it in the PR description.  I'm curious how our link can be focused but not have focus styles 🤔 .  Sadly I have no insight to offer.
> in the persistent demo the custom close button does get focus, but the focus style doesn't seem to apply unless you tab onto it

2020-09-23 18:48 UTC, mikemai2awesome requested changes

2020-09-23 18:48 UTC, mikemai2awesome commented on docs-site/src/pages/pattern-lab/_patterns/40-components/modal/52-modal-usage-persistent.twig
> +          "autofocus": ""
This is not valid HTML, `autofocus` is only supported in form controls such as `<button>`, `<input>`, `<select>` and `<textarea>`.

2020-09-25 14:14 UTC, danielamorse commented on docs-site/src/pages/pattern-lab/_patterns/40-components/modal/52-modal-usage-persistent.twig
> +          "autofocus": ""
@mikemai2awesome updated with `data-bolt-autofocus` selector.

2020-09-25 16:12 UTC, mikemai2awesome approved these changes

2020-09-25 16:19 UTC, merged