DS-222: Convert Text to latest renderer
boltdesignsystem/bolt pull request #1984
Opened 2020-09-23 19:51 UTC by cjwhitedev

## Jira

[https://pegadigitalit.atlassian.net/browse/DS-224](https://pegadigitalit.atlassian.net/browse/DS-224)

## Summary

Convert bolt-text to the latest renderer.

## Details

Convert bolt-text to the latest renderer.

## How to test

To test the conversion:

- Review changes
- Test text demos

2020-09-30 19:29 UTC, danielamorse requested changes
@cjwhitedev looking good. I approve of removing all that commented-out code 👍 

Only regression I found was the "This is the xsmall headline" demo under "Headlines" [here](https://boltdesignsystem.com/pattern-lab/?p=components-text-typographic-recipes). Run locally and compare. It has more letter-spacing currently on master. Pull the latest before you debug. I made some edits:
- Renamed the original `subComponentValues` function to `setDefaultValue` which better describes what it does.
- I added a check for the `url` in the `a` tag switch statement so that `url="undefined"` is never output.

Be sure to mention any meaningful code changes in the PR description. For example, `a` was added to the schema in this PR. That's good to know as a reviewer. Use your judgement, but that change seemed important to me.

You can avoid commits like "for dan's eyes only" 😆 going into git history with the `git commit --amend` flag ([docs](https://www.atlassian.com/git/tutorials/rewriting-history)). I use it all the time. Let me know and we can review it together.

2020-10-02 19:41 UTC, cjwhitedev commented
@danielamorse all of these notes have been acted upon besides amending the old commit. Doing so retroactively seems risky.

2020-10-16 15:00 UTC, cjwhitedev commented
@danielamorse I just made another update to this while its open. **You had mentioned yesterday that you need to fix some tests before we merge this**, just documenting that here as well.

2020-10-20 14:04 UTC, danielamorse commented
To "fix" the failing tests I had to remove `bolt-text` from other component Jest tests: https://github.com/boltdesignsystem/bolt/pull/1984/commits/34f9b16dbb53ef601f458b949aedf53cefdf0835

These tests do not wait long enough for nested components (like `bolt-text`) to finish rendering, so the results it returns are not correct. I spent a bit of time looking for a way to get the tests to wait, but I did not find a solution that works with our current testing setup.

See here for example: https://github.com/boltdesignsystem/bolt/blob/master/packages/testing/testing-helpers/index.js#L53. `customElements` is undefined inside this `renderWC` function. While, it _is_ defined inside the main `test()` function. So, it will never wait for the Promise to resolve.

This requires more time to debug and potentially rebuild our tests. For now, I'm just removing the failing parts of the test.

cc: @colbytcook @remydenton

2020-10-20 15:10 UTC, mikemai2awesome requested changes

2020-10-20 15:10 UTC, mikemai2awesome commented on packages/components/bolt-text/text.schema.js
> +        'a',
Remove the anchor tag here. Also the `cite`, no one is using that and it doesn't make sense to be here. Only keep headings, paragraph, div, and span.

2020-10-20 15:22 UTC, mikemai2awesome commented
Here're the bugs on Safari locally:

1. Tabs disappearing
2. Text color util classes are not working with bolt-text
3. List is not rendering correctly with icons in the item

<img width="1383" alt="Screen Shot 2020-10-20 at 11 22 09 AM" src="https://user-images.githubusercontent.com/3027663/96607646-8d658f80-12c6-11eb-99c2-65cbefd5453b.png">

2020-10-21 14:58 UTC, cjwhitedev commented on packages/components/bolt-text/text.schema.js
> +        'a',
@mikemai2awesome these have been removed.

2020-10-21 15:02 UTC, cjwhitedev commented on docs-site/src/pages/pattern-lab/_patterns/40-components/text/15-text-tag-variations.twig
> +<bolt-text tag="a" url="https://www.google.com">
@mikemai2awesome I have removed this demo for now. We are going to deprecate the use of URL, but do so in a different PR. I made a ticket [here](https://pegadigitalit.atlassian.net/browse/DS-243).

2020-10-21 17:41 UTC, cjwhitedev commented
> Here're the bugs on Safari locally:
> 
> 1. Tabs disappearing
> 2. Text color util classes are not working with bolt-text
> 3. List is not rendering correctly with icons in the item

ok @mikemai2awesome this is resolved as we saw in dev huddle. Do you want to just double check that all is well on your system?

2020-10-26 15:37 UTC, mikemai2awesome approved these changes

2020-10-26 18:40 UTC, merged