DS-198 Tabs renderer conversion
boltdesignsystem/bolt pull request #1985
Opened 2020-09-25 01:44 UTC by danielamorse

## Jira

https://pegadigitalit.atlassian.net/browse/DS-198

## Summary

Convert Tabs component to BoltElement renderer.

## Details

Convert Tabs to use new renderer, along with new `wc-context` library.

Because `wc-context` works well with props, it made sense to convert some variables into internal props (i.e. private, not in schema). As that conversion was underway, I noticed there was some unnecessary complexity (written by yours truly) that I simplified just to understand how the component functioned. So this includes some careful rework.

Test snapshots are updated. Due to errors waiting for promises to resolve in Puppeteer, some of the updated snapshots are of HTML before the component finishes updating, so they're not very helpful. I commented out the Light DOM test as there's a bug with `conditional-shadow-dom` that's out of scope of this update. The Tabs `no-shadow` demo works as expected, so I think it's safe to disable this test for now.

## How to test

- Review code changes (there are a lot)
- Review all Tabs demos
- Also review Accordion Content demo which has Tabs as content in an Accordion Item

2020-09-25 19:09 UTC, mikemai2awesome requested changes
@danielamorse The tabs are all not loading on this page. I tried Chrome and Safari. https://feature-ds-198-tabs-renderer-conversion.boltdesignsystem.com/pattern-lab/?p=viewall-components-tabs

2020-09-25 19:47 UTC, cjwhitedev approved these changes
@danielamorse everything looks good and works for me.

2020-10-01 20:54 UTC, danielamorse commented
> @danielamorse The tabs are all not loading on this page. I tried Chrome and Safari. https://feature-ds-198-tabs-renderer-conversion.boltdesignsystem.com/pattern-lab/?p=viewall-components-tabs

@mikemai2awesome great save! I tested in Edge but not Safari, and Safari had a major rendering bug. It should be fixed now. Please take another look.

2020-10-05 15:27 UTC, mikemai2awesome approved these changes
@danielamorse Good, the tabs are rendering again.

Side note, any reason why we have this page showing up? https://feature-ds-198-tabs-renderer-conversion.boltdesignsystem.com/pattern-lab/?p=components-tabs-no-shadow

2020-10-06 19:32 UTC, danielamorse commented
> Side note, any reason why we have this page showing up? https://feature-ds-198-tabs-renderer-conversion.boltdesignsystem.com/pattern-lab/?p=components-tabs-no-shadow

@mikemai2awesome it's used by our Nightwatch Tabs test. Other components have a similar demo just for Nightwatch. It's confusing to put it here alongside the other prop demos. We could bury this Nightwatch demo elsewhere in PL. What do you think?

2020-10-07 14:26 UTC, colbytcook approved these changes

2020-10-07 20:15 UTC, merged