[DRAFT] DS-189: Table Caption
boltdesignsystem/bolt pull request #1986
Opened 2020-09-25 17:31 UTC by cjwhitedev

## Jira

[https://pegadigitalit.atlassian.net/browse/DS-189](https://pegadigitalit.atlassian.net/browse/DS-189)

## Summary

Edit twig and JS to allow tables to be captioned.

## Details

Add a conditional to twig to allow for a new `caption` prop. Add said prop to schema. Fix JS error caused by adding caption to table with markup. Set up both of these to work with a `figure` and `figcaption`.

## How to test

Check out the new caption demo page.

2020-10-23 20:30 UTC, danielamorse commented
@mikemai2awesome addressed the feedback about the images and WC demos:
> For the docs, you changed fillmurray to placeholder, can you change to a bolt-image instead? The point is to show different types of content. And for the WC docs, use web component markup, no twig please.

2020-10-26 20:35 UTC, mikemai2awesome requested changes

2020-10-26 20:40 UTC, mikemai2awesome approved these changes

2020-10-26 20:50 UTC, mikemai2awesome commented
@cjwhitedev @danielamorse I fixed some indents and demo markup. Make sure your text editor is set to use tab width of 2 spaces.

2020-10-27 12:16 UTC, colbytcook commented on packages/components/bolt-table/src/table.js
> +            <!-- <caption class=${captionClasses}>
Should we remove these commented tags?

2020-10-27 12:19 UTC, colbytcook commented on packages/components/bolt-table/src/table.scss
> +  // }
Should we remove this commented out code?

2020-10-27 12:20 UTC, colbytcook approved these changes

2020-10-30 19:04 UTC, merged