[DO NOT MERGE] DS-152 Page Header Refactor
boltdesignsystem/bolt pull request #1991
Opened 2020-10-08 22:13 UTC by mikemai2awesome

# WIP. DO NOT MERGE.

## Jira

(Enter a link to the Jira issue this PR applies to, if any)

## Summary

(Enter a one-line summary of the changes in this PR.  This will be included in the release notes)

## Details

(Explain the changes in enough detail fo reviewers to understand.  Raise any questions for reviewers to consider.)

## How to test

(List clear steps to test that the changes are working)

## Release notes

(Optionally, add details that will be added to the release notes. Use this to call out deprecations. [Read more](https://intuit.github.io/auto/docs/generated/changelog#additional-release-notes))

2021-01-04 16:52 UTC, remydenton requested changes
I've given most of my feedback previously in dev huddles, Slack, etc. and it looks like it's all been addressed.

One last thing I just noticed, we need to move the header component from [the pattern lab boltrc file](https://github.com/boltdesignsystem/bolt/blob/feature/ds-152-page-header/docs-site/.boltrc.js#L94) to [the starter kit boltrc file](https://github.com/boltdesignsystem/bolt/blob/feature/ds-152-page-header/packages/base-starter-kit/.boltrc.js) since it is no longer just an internal component.

I also added a comment with one nitpick about schema while we're making changes.

2021-01-04 16:52 UTC, remydenton commented on packages/components/bolt-page-header/page-header-nav-ul.schema.js
> +  // required: ['content', 'category'],
This doesn't need to be commented out now since we've [commented out the validation in the twig file](https://github.com/boltdesignsystem/bolt/pull/1991/files#diff-2145f6c793cca3ae115f7ffdf4ce6ec3738bb5131fedc41b4b2b3a948db3696eR1-R9).  The problem isn't that these props aren't required, it's that we haven't yet figured out how to validate multiple sub component files yet.  So we should make the schema correct even if there's no validation happening.

2021-01-04 21:07 UTC, remydenton approved these changes

2021-01-05 16:53 UTC, danielamorse approved these changes

2021-01-05 17:02 UTC, merged