DS-236: Add support for images in action blocks (and other cleanup)
boltdesignsystem/bolt pull request #1995
Opened 2020-10-09 20:13 UTC by remydenton

## Jira

https://pegadigitalit.atlassian.net/browse/DS-236

## Summary

Allows images and other freeform content to be passed to action blocks

## Details

- Removes the `icon` property (with deprecation) and adds a new `content` property.   There was an unused `__icon` class that was also removed.  Now, instead of passing an object for the icon, you can pass an already rendered icon or anything else for content.
- Renames `contentItems` to `items` (with deprecation)
- Adds support for passing an item without a url.  This makes something like the partner links shown at https://boltdesignsystem.com/pattern-lab/?p=pages-event-detail possible.
- Updates the partner links to require less custom CSS and delegate more to action blocks.
- Replaces the private _action-blocks-item.twig file with a public action-block.twig file.  This was based on a discussion with @danielamorse about architecture for patterns with multiple items.

## How to test

- Confirm that images and other content can now be passed to action blocks as shown in the new example at /pattern-lab/?p=components-action-blocks-freeform-content
- Confirm that action blocks examples shown at the following URLs are unchanged.
/pattern-lab/patterns/40-components-action-blocks/index.html
/pattern-lab/?p=pages-event-detail

2020-10-23 17:11 UTC, mikemai2awesome requested changes
Can we rename icon to media instead? We can rename text to content later. Don't rename icon to content.

2020-10-23 21:10 UTC, danielamorse approved these changes
@remydenton updated `content` prop to `media` as discussed. Left `text` alone for now.

Approved. There is a slight layout change on [this demo](https://boltdesignsystem.com/pattern-lab/?p=components-action-blocks-spacing-variations), but it's expected because the icon sizes changed.

2020-10-26 20:55 UTC, mikemai2awesome approved these changes

2020-10-26 20:58 UTC, mikemai2awesome requested changes
Oops, just caught a lot of other docs didn't get updated to `media`. See inline comment.

2020-10-26 20:58 UTC, mikemai2awesome commented on docs-site/src/pages/pattern-lab/_patterns/10-visual-styles/20-information-density/_info-density.twig
> +          content: icon_1,
This along with other docs still need to be updated to `media`. It sucks we don't have validation now that we are not aware of errors. @danielamorse @remydenton

2020-10-30 19:18 UTC, danielamorse commented on docs-site/src/pages/pattern-lab/_patterns/10-visual-styles/20-information-density/_info-density.twig
> +          content: icon_1,
The rest have been updated @mikemai2awesome: https://github.com/boltdesignsystem/bolt/pull/1995/commits/7c92d7ed8e0a8498ceb681966ce5730f59460ced

2020-10-30 19:25 UTC, mikemai2awesome approved these changes

2020-10-30 19:40 UTC, merged