ACD-286 Academy popover overflow bug
boltdesignsystem/bolt pull request #1996
Opened 2020-10-14 20:03 UTC by danielamorse

## Jira

https://pegadigitalit.atlassian.net/browse/ACD-286

## Summary

Add custom Academy component to fix bug where popover gets clipped by overflow hidden.

## Details

Academy's horizontal card used the grid with `--bordered` class and negative margin and overflow hidden to create a layout with vertical border-separated items. Because this required overflow hidden, any popover inside the content would get clipped. This PR introduces a custom component that uses very simple css grid styles to accomplish the border-separated layout without requiring overflow hidden.

It also adds a demo of the popover menu in search results: `/pattern-lab/patterns/50-pages-60-academy-05-pages-search-search-results-acd-search-results-page/50-pages-60-academy-05-pages-search-search-results-acd-search-results-page.html`

## How to test

(List clear steps to test that the changes are working)

## Release notes

(Optionally, add details that will be added to the release notes. Use this to call out deprecations. [Read more](https://intuit.github.io/auto/docs/generated/changelog#additional-release-notes))

2020-10-14 21:05 UTC, mikemai2awesome requested changes

2020-10-14 21:05 UTC, mikemai2awesome commented on docs-site/src/pages/pattern-lab/_patterns/50-pages/60-academy/index.scss
> +  @media (min-width: 600px) {
Use bolt-mq mixin for this.

2020-10-14 21:05 UTC, mikemai2awesome commented on docs-site/src/pages/pattern-lab/_patterns/50-pages/60-academy/index.scss
> +    height: 100%;
If you set `height: 100%`, it will ignore `align-items: center`. CSS grid items are 100% by default, so you should just remove both `height: 100%` and `align-items: center`

2020-10-15 15:32 UTC, danielamorse commented
Thanks @mikemai2awesome, addressed all of the above. Ready for another review.

2020-10-15 19:10 UTC, cjwhitedev approved these changes
@danielamorse  This all looks great to me. Just visually, I wonder if we should lessen the spacing on the popover. I tried locally with `spacing: "xsmall"` and it looked better to me. Not a big deal either way, approving.

2020-10-16 14:54 UTC, danielamorse commented
@cjwhitedev good call. I missed this. I updated the [Academy demo](https://github.com/boltdesignsystem/bolt/pull/1996/commits/06c34b80f212e197c82b4c0937960c661f33d825) to match our [Menu + Popover component demo](https://boltdesignsystem.com/pattern-lab/?p=components-menu-use-case-popover).

Link `text` and `url` are passed as props in the menu items, and `spacing` is set to "none" on the menu. Much better now!

2020-10-19 14:45 UTC, mikemai2awesome approved these changes

2020-10-23 19:24 UTC, merged