[DO NOT MERGE] DS-156 add link element
boltdesignsystem/bolt pull request #1999
Opened 2020-10-19 16:11 UTC by mikemai2awesome

# WIP. DO NOT MERGE

## Jira

(Enter a link to the Jira issue this PR applies to, if any)

## Summary

(Enter a one-line summary of the changes in this PR.  This will be included in the release notes)

## Details

(Explain the changes in enough detail fo reviewers to understand.  Raise any questions for reviewers to consider.)

## How to test

(List clear steps to test that the changes are working)

## Release notes

(Optionally, add details that will be added to the release notes. Use this to call out deprecations. [Read more](https://intuit.github.io/auto/docs/generated/changelog#additional-release-notes))

2020-10-29 01:25 UTC, danielamorse requested changes
@mikemai2awesome great work! I'm really liking the simplicity.

The new focus styles are nice, too. On the reversed-underline header example, the focus styles overlap a bit. Are you ok with this? Seems kind of unavoidable with this style. Just pointing it out.
![image](https://user-images.githubusercontent.com/36336/97513883-bf7c8e80-1963-11eb-881c-62365ed1b76e.png)

I left some inline comments and questions.

2020-10-29 01:25 UTC, danielamorse commented on packages/elements/bolt-text-link/src/text-link.scss
> +.e-bolt-text-link--block {
I love this feature but it's not really "block". What if we had a `block` option that was just `display: block` and another that was called `cover` or `fill` (or something like that)?

2020-10-29 01:25 UTC, danielamorse commented on packages/elements/bolt-text-link/src/text-link.scss
> +a.e-bolt-text-link[type],
I'm not sure we should do this.

1) We need to eliminate any CSS that's not absolutely necessary for performance reasons.

2) In the event someone makes a mistake or some errant JS puts the wrong attribute on an element, it will look very unprofessional on a production site.

I know bad accessibility is a serious problem, but I worry putting our validation in CSS and making it publicly visible will come back to haunt us.

2020-10-29 01:25 UTC, danielamorse commented on packages/elements/bolt-text-link/src/text-link.twig
> +{% if button %}
Could replace this if/else with:
```
{% set tag = button ? 'button' : 'a' %}
```

2020-10-29 01:25 UTC, danielamorse commented on packages/elements/bolt-text-link/src/text-link.twig
> +{% spaceless %}<{{ tag }} {{ attributes.addClass(classes) }}>{% if icon_before %}<span class="e-bolt-text-link__icon-before" aria-hidden="true">{{ icon_before|spaceless }}</span>{% endif %}{{ content
This outputs the same thing as far as I can tell (if you consider it an improvement):
```
{% spaceless %}<{{ tag }} {{ attributes.addClass(classes) }}>{% spaceless %}  
  {% if icon_before %}<span class="e-bolt-text-link__icon-before" aria-hidden="true">{{ icon_before|spaceless }}</span>{% endif %}
  {{- content -}}
  {% if icon_after %}<span class="e-bolt-text-link__icon-after" aria-hidden="true">{{ icon_after|spaceless }}</span>{% endif %}
{% endspaceless %}</{{ tag }}>{% endspaceless %}
```

2020-10-29 01:25 UTC, danielamorse commented on packages/elements/bolt-text-link/text-link.schema.js
> +      type: 'string',
Should this be `string` or `object`? `object` would work with both strings and a Drupal render array, right @remydenton?

2020-10-29 22:19 UTC, mikemai2awesome commented on docs-site/src/pages/pattern-lab/_patterns/20-elements/text-link/05-text-link.twig
> +{% set description %}
Moved it to second.

2020-10-29 22:19 UTC, mikemai2awesome commented on packages/elements/bolt-text-link/src/text-link.scss
> +a.e-bolt-text-link[type],
removed

2020-10-29 22:20 UTC, mikemai2awesome commented on packages/elements/bolt-text-link/text-link.schema.js
> +      type: 'string',
changed to `object`.

2020-10-29 22:20 UTC, mikemai2awesome commented on packages/elements/bolt-text-link/src/text-link.twig
> +{% spaceless %}<{{ tag }} {{ attributes.addClass(classes) }}>{% if icon_before %}<span class="e-bolt-text-link__icon-before" aria-hidden="true">{{ icon_before|spaceless }}</span>{% endif %}{{ content
i think it's ok to keep it in one line and use one less spaceless.

2020-10-29 22:22 UTC, mikemai2awesome commented
@danielamorse I updated the focus outline, that overlap only happens in Firefox now, looks good in chrome and safari. And the underline only turns gray if it's a visited link.

2020-10-30 16:05 UTC, mikemai2awesome commented on packages/elements/bolt-text-link/src/text-link.scss
> +.e-bolt-text-link--block {
changed to `expand-click-target`

2020-10-30 18:30 UTC, danielamorse approved these changes

2020-10-30 19:23 UTC, remydenton commented
This looks great.  Nice work @mikemai2awesome.

I'm approving, but I have a philosophical question-- does it really make sense to have twig template be the recommended solution for Drupal?  I personally think we should recommend the bare element, `<a class="e-bolt-text-link"></a>`, in all cases.  Here's why:
* We do officially support the bare element, so the genie is already out the bottle.
* Having two different ways of doing something makes it confusing.  Without looking at the docs, how do you know which one is preferred and which situations to use which one in?  It's one more thing to keep track of for developers who already struggle with Bolt and its quirks.
* We have a strong line in the sand about NOT using `c-bolt-*` elements outside bolt.  The fact that you CAN use `e-bolt-*` elements is already an exception to that, so the clearer we can make the line between the two, the better.  Otherwise, the rule against `c-bolt-*` may not be quite as clear (and that one is very important).
* One major goal of twig is to make components easy to update.  But the core philosophy behind elements is that they are simple, and we officially support their usage outside of twig, so they should be updated very little (i.e. we both shouldn't have much reason to AND it would be a lot of work).  So that reduces the usefulness of twig.
* Another major goal of twig is SSR.  That doesn't apply to elements though.

2020-10-30 19:24 UTC, remydenton approved these changes

2020-11-02 12:22 UTC, adamszalapski commented
Everything looks good but I have one question because the component section on my end is empty and all components are in the elements section. See image below

![image](https://user-images.githubusercontent.com/16049049/97867460-34f2b100-1d0e-11eb-930a-70abbe0d5558.png)

Except for this everything is ok. I agree with @remydenton that maybe we don't need twig for elements because they should be the simplest part of our design system.

2020-11-02 15:33 UTC, adamszalapski approved these changes

2020-11-03 16:22 UTC, mikemai2awesome commented
As discussed, we are hiding the elements section for now till we decide on keeping twig template for elements or not.

2020-11-03 16:22 UTC, merged