Feature/ds 237 move no shadow demos
boltdesignsystem/bolt pull request #2000
Opened 2020-10-20 13:56 UTC by cjwhitedev

## Jira

[https://pegadigitalit.atlassian.net/browse/DS-237](https://pegadigitalit.atlassian.net/browse/DS-237)

## Summary

Move all no-shadow demos in pattern lab to their own directory and hide them.

## Details

Move all no-shadow demos in pattern lab to their own directory and hide them. This also involved renaming the expirements directory so that tests could be placed last permanently and hidden according to its position (last).

## How to test

- make sure all no-shadow demos are removed from the components listing
- make sure the tests listing is actually hidden
- verify that the experiments listing isnt broken from the rename
- make sure that the tests still run from their new location

## Release notes

no-shadow testing updated and experiments directory moved.

2020-10-20 13:57 UTC, cjwhitedev commented
@mikemai2awesome I wanted to pull you in specifically because of how I handled the hiding of the tests directory, and having to rename the experiments directory. I would love your feedback anywhere you can provide it though.

2020-10-20 19:55 UTC, mikemai2awesome requested changes
@cjwhitedev Thank you for moving these, the organization makes much more sense now. Can you take care of the following?

1. Can we remove the `<form>` tags wrapping each accordion test on accordion-no-shadow.twig? I am not sure why the tags are used.
2. For the experiments section, let's go with 60-experiments.

2020-10-20 19:55 UTC, mikemai2awesome commented on packages/website-ui/uikit-workshop/src/scripts/components/pl-nav/nav-list.scss
> +  &:nth-last-child(2) {
What is this hiding? @cjwhitedev

2020-10-20 20:51 UTC, danielamorse commented
> * Can we remove the `<form>` tags wrapping each accordion test on accordion-no-shadow.twig? I am not sure why the tags are used.

@mikemai2awesome `<form>` is a workaround for `no-shadow`. When a component is in a form it renders to Light DOM. You could add the `no-shadow` attribute to every "bolt-accordion" and "bolt-accordion-item" element in the test instead, but I'd just leave the `<form>` tag there for simplicity. Maybe add a comment "components inside form always render to Light DOM".

2020-10-21 13:04 UTC, cjwhitedev commented on packages/website-ui/uikit-workshop/src/scripts/components/pl-nav/nav-list.scss
> +  &:nth-last-child(2) {
@mikemai2awesome the `Tests` section in the pattern lab navigation.

2020-10-26 20:30 UTC, mikemai2awesome approved these changes
PL compiled correctly after `yarn build`.

2020-10-29 15:26 UTC, danielamorse approved these changes
Nicely done!

2020-10-30 18:43 UTC, merged