DS-178 Fix Blockquote quotes in safari
boltdesignsystem/bolt pull request #2003
Opened 2020-10-23 14:29 UTC by danielamorse

## Jira

https://pegadigitalit.atlassian.net/browse/DS-178

## Summary

Fixes quotes in Safari which were previously not showing.

## Details

Safari doesn't support the CSS selector we were using to add quotation marks. That selector is `::slotted()` combined with a pseudo-selector, example: `::slotted(p):before { }`. I couldn't find any Safari docs specifically saying this isn't supported, but it's what I found after testing. It supports chaining `::slotted()` with other selectors, just no pseudo-selectors.

Given that limitation of Safari, I had to refactor the CSS to use attribute selectors not classes in order to target the blockquote `<p>` tags. In the end this actually reduced a lot of complexity in the CSS _and_ in the JS.

I switch to use `first-of-type` rather than `.is-first` classes and eliminated some unnecessary JS in the process.

I also had to refactor the language-specific quotes so that it worked when the `[lang]` attribute was on the blockquote itself _or_ somewhere up the tree.

## How to test
- Review code changes
- Review all Blockquote demos

2020-10-23 20:57 UTC, mikemai2awesome requested changes

2020-10-23 20:57 UTC, mikemai2awesome commented on packages/components/bolt-blockquote/src/blockquote.scss
> +  @at-root [lang='de'] &,
Are you sure this is working? I have never been able to use `@at-root` with multiple lines. Sass yells at me and I have to do separate rules.

2020-10-23 21:38 UTC, danielamorse commented on packages/components/bolt-blockquote/src/blockquote.scss
> +  @at-root [lang='de'] &,
Yeah, this is the output:
![image](https://user-images.githubusercontent.com/36336/97056079-1c3c0b80-1556-11eb-85b7-202503d61e9c.png)

It barks at me when `@at-root` is not first in the list. Works fine when it is. In this case it _should_ be first in the list. Think I should put it on its own line to be safe? Or leave out `@at-root` altogether?

2020-10-26 14:14 UTC, colbytcook approved these changes

2020-10-26 14:43 UTC, mikemai2awesome approved these changes

2020-10-26 14:43 UTC, mikemai2awesome commented on packages/components/bolt-blockquote/src/blockquote.scss
> +  @at-root [lang='de'] &,
@danielamorse OK if it's working then let's keep it.

2020-10-26 18:22 UTC, danielamorse commented
Merging since we have approvals, but just want to remind @cjwhitedev to check out this PR. Thought you might be interested to see how we solved the bug and that we were able to remove some component JS once the fix was in place.

2020-10-26 18:22 UTC, merged

2020-10-26 18:22 UTC, cjwhitedev approved these changes
looks great @mikemai2awesome