WWW-105 PatternLab video clean up
boltdesignsystem/bolt pull request #2011
Opened 2020-11-06 13:53 UTC by colbytcook

## Jira

https://pegadigitalit.atlassian.net/browse/WWW-105

## Summary

Updated the existing PatternLab instance with the new version of the Brightcove video

## Details

1. Updated all the examples of videos being used within the PatternLab instance to the new Brigthcove video method
2. Added a "Deprecated" label on the Videos PL tab and added a deprecation message to the videos docs
3. Updated the build to output an isolated Brightcove CSS file for use within the Brigthcove Studio player

## How to test

Check instances of videos in the PL instance and confirm they are still working as expected

2020-11-06 16:03 UTC, mikemai2awesome requested changes

2020-11-06 16:03 UTC, mikemai2awesome commented on docs-site/src/pages/pattern-lab/_patterns/40-components/modal/45-modal-usage-video.twig
> +      "on-click-target": "js-modal-456"
let's fix the conventions in this doc, use `js-bolt-modal-*`.

2020-11-06 16:03 UTC, mikemai2awesome commented on packages/components/bolt-video/brightcove/video.scss
> +// Same as max-width of wrapper container
Is this going to live in the base theme? If so, we need to move the source of truth there and utilize the Drupal `docs` folder in that particular theme.

2020-11-06 16:20 UTC, remydenton commented on docs-site/src/pages/pattern-lab/_patterns/40-components/card-replacement/35-card-replacement-with-video.twig
> +            "class": "brightcove-toggle"
I actually had this same critique and created a ticket for it on the pega.com board: https://pegadigitalit.atlassian.net/browse/WWW-355

2020-11-06 16:41 UTC, remydenton commented on packages/components/bolt-video/brightcove/video.scss
> +.c-base-video {
How does the `c-base-video` class get added to the video markup?

2020-11-06 16:48 UTC, remydenton commented on docs-site/src/pages/pattern-lab/_patterns/40-components/accordion/40-accordion-content-variations.twig
> +      data-account="1900410236"
These come straight from Brightcove, which is why the naming doesn't have prefix and namespace. 
 See https://studio.support.brightcove.com/publish/choosing-correct-embed-code.html#inpage

2020-11-06 16:49 UTC, remydenton commented on docs-site/src/pages/pattern-lab/_patterns/40-components/card-replacement/999-card-replacement-with-web-component.twig
> +  {% spaceless %}
I'm also curious what spaceless is needed for here 🤔 .

2020-11-06 18:47 UTC, colbytcook commented on docs-site/src/pages/pattern-lab/_patterns/40-components/card-replacement/35-card-replacement-with-video.twig
> +            "class": "brightcove-toggle"
@remydenton updated to the js-base-video-toggle class, feel free to update on the Drupal side

2020-11-06 20:22 UTC, mikemai2awesome commented on docs-site/src/pages/pattern-lab/_patterns/40-components/accordion/40-accordion-content-variations.twig
> +      data-account="1900410236"
ok then.

2020-11-06 20:25 UTC, colbytcook commented on packages/components/bolt-video/brightcove/video.scss
> +.c-base-video {
i think this is a legacy that I missed, let me recheck this

2020-11-09 22:28 UTC, mikemai2awesome approved these changes
I updated the card docs and hid the old video docs from the view all page. @colbytcook

2020-11-10 15:26 UTC, remydenton commented on packages/components/bolt-video/brightcove/_video.scss
> +  display: none; // [3]
This line was specifically removed in https://github.com/boltdesignsystem/bolt/pull/2004.  How did it come back?  It's difficult to see what else was added/removed in this file, so I'm concerned about what else it might be introducing that is unintended.

2020-11-10 15:32 UTC, remydenton commented on packages/components/bolt-video/brightcove/_video.scss
> +  position: absolute; // [5]
Does positioning `.video-js` absolutely still work if there is no `bolt-video` wrapper?  Is ratio now required? Ratio wasn't previously required (see [the schema](https://boltdesignsystem.com/pattern-lab/?p=viewall-components-video), which has a ratio boolean), and I believe there are currently places in Drupal where `ratio` is set to `false`.

2020-11-10 16:28 UTC, colbytcook commented on packages/components/bolt-video/brightcove/_video.scss
> +  display: none; // [3]
nice catch, let me check this out. since this was copied over from the existing CSS it might be an out of date artifact

2020-11-10 16:31 UTC, colbytcook commented on packages/components/bolt-video/brightcove/_video.scss
> +  position: absolute; // [5]
As far as I know, the bolt-ratio is required for the new video otherwise I am not sure we will get the correct responsive behavior.

2020-11-13 19:17 UTC, cjwhitedev commented
Is the title and play time still supposed to show? If you go to accordion component variations and open the video tab on this branch and on master you can see what i mean. 

There is no longer an example video in Figure Media Variations

I can see the title is missing in the Modal demo, as well as Tabs Content.

in the deprecated video warning, is it possible to link "**Drupal integrated Brightcove video component**" to the documentation?

2020-11-20 21:19 UTC, remydenton approved these changes
I think this is ready to merge.  I'm a little nervous that we're taking out the `bolt-video` docs while all our properties are still using it, but it seems like ripping off the bandaid may be the best way to get this done.

2020-11-20 21:20 UTC, merged