WWW-384 Play icon on video players floating separately from buttons on Edge v42 (Pega Edge)
boltdesignsystem/bolt pull request #2017
Opened 2020-11-16 18:30 UTC by colbytcook

## Jira

https://pegadigitalit.atlassian.net/browse/WWW-384

## Summary

Create Edge ~v.42 specific CSS to handle the video player "play" icon

## Details

Wrapped the "play" icon CSS in @support to serve up two different CSS blocks depending on if the browser supports clip-path

## How to test

View "/pattern-lab/?p=components-video" in Edge v.18 Browserstack (this browser also doesn't support clip-path)

2020-11-17 11:26 UTC, adamszalapski commented on packages/components/bolt-video/src/_edge-video-updates.scss
> +        top: 40% !important;
@colbytcook we really need `!important` here I try to remove it and it works as well.

2020-11-17 11:26 UTC, adamszalapski commented on packages/components/bolt-video/src/_edge-video-updates.scss
> +        left: 40% !important;
@colbytcook we really need `!important` here I try to remove it and it works as well.

2020-11-17 11:27 UTC, adamszalapski approved these changes
It works perfectly. I add two comments in the code.

2020-11-17 14:38 UTC, colbytcook commented on packages/components/bolt-video/src/_edge-video-updates.scss
> +        top: 40% !important;
ah ok, let me test that, i was having trouble at one point

2020-11-17 14:46 UTC, colbytcook commented on packages/components/bolt-video/src/_edge-video-updates.scss
> +        top: 40% !important;
Edge inspector is strange, the 40% CSS declaration is being overwritten (according to the inspector anyways) but it is not changing the display at all. This is why I put the !important in originally. Well I am removing it now anyways.

2020-11-18 15:46 UTC, mikemai2awesome requested changes

2020-11-18 15:46 UTC, mikemai2awesome commented on packages/components/bolt-video/src/_edge-video-updates.scss
> +.video-js {
Let's not create a separate file for this. it's really hard to know there are hacks. keep it in the same file and write a comment.

2020-11-20 15:36 UTC, mikemai2awesome approved these changes

2020-11-20 18:17 UTC, merged