WWW-385 Space/padding missing in between Subnav links when set to 'Use Centered Layout' in Edge v42 (Pega Edge)
boltdesignsystem/bolt pull request #2018
Opened 2020-11-17 17:57 UTC by colbytcook

## Jira

https://pegadigitalit.atlassian.net/browse/WWW-385

## Summary

Create Edge ~v.42 specific CSS to handle the navlink spacing

## Details

Wrapped the navlink CSS in @support to serve up two different CSS blocks depending on if the browser supports clip-path (this is used to target Legacy Edge)

## How to test

View "/pattern-lab/patterns/40-components-navbar-05-navbar/40-components-navbar-05-navbar.html" in Edge v.17 Browserstack (this browser also doesn't support clip-path)

2020-11-17 21:29 UTC, adamszalapski approved these changes
I don't like that we checking if `clip-path` is supported and fixing calc/CSS vars issue but this is temporary and the fix is working that I'm ok with that. Good job @colbytcook 👍

2020-11-18 15:43 UTC, mikemai2awesome requested changes

2020-11-18 15:43 UTC, mikemai2awesome commented on packages/components/bolt-navlink/_edge-bolt-navlink.scss
> +        (-webkit-clip-path: polygon(0 0, 0 100%, 100% 50%)) or
Why are we using clip path as the logic?

2020-11-18 15:43 UTC, mikemai2awesome commented on packages/components/bolt-navlink/navlink.scss
> +@import '_edge-bolt-navlink';
Don't create a separate file, just keep it in the same file with a comment.

2020-11-20 15:36 UTC, mikemai2awesome approved these changes

2020-11-20 18:18 UTC, merged