DS-174: Layout POC
boltdesignsystem/bolt pull request #2030
Opened 2020-12-04 18:04 UTC by cjwhitedev

## Jira

[https://pegadigitalit.atlassian.net/browse/DS-174](https://pegadigitalit.atlassian.net/browse/DS-174)

## Summary

Create a layout POC in the layouts directory.

## Details

The layout POC is meant to simplify grid for Drupal use while replacing band and hero.

## How to test

- review the code
- check out the demo page with all the docs

## Release notes

Added a layout concept meant to replace and simplify several components.

2020-12-07 13:09 UTC, cjwhitedev commented on packages/components/bolt-background/src/background.scss
>  }
does editing the background itself have a negative impact on how its working elsewhere? I put the changes in the layout since it seemed like it was a problem specific to layout and nothing else.

2021-06-09 20:31 UTC, mikemai2awesome commented on packages/components/bolt-background/src/background.scss
>  }
this has been moved out by itself.

2021-06-21 18:06 UTC, cjwhitedev reviewed
It doesn't look like every layout doc page has a demo - is this intentional?

2021-06-21 18:21 UTC, cjwhitedev reviewed
Is there anywhere a user could see all potential template options that im not seeing?

2021-06-21 18:34 UTC, mikemai2awesome commented
> Is there anywhere a user could see all potential template options that im not seeing?

All the templates are here and breakpoints are explained in the notes section: https://feature-ds-174-layout-poc.boltdesignsystem.com/pattern-lab/?p=layouts-layout-template

The schema needs to list all possible template options, which Dan is fixing.

2021-06-22 15:04 UTC, mikemai2awesome approved these changes

2021-06-29 13:25 UTC, danielamorse requested changes
@mikemai2awesome @cjwhitedev schema should now display options when a prop is an array of strings (see layout schema).

Next steps:
- Resolve conflict with master
- Set `@bolt/layouts-layout` version to `4.0.0`
- Add `@bolt/layouts-layout` as dependency to starter-kit (currently included without listing as. dependency)

Then this should be good to go.

2021-06-29 13:26 UTC, danielamorse commented on packages/layouts/bolt-layout/package.json
> +  "version": "3.1.0",
Change to `4.0.0` _after_ merging in master (if necessary)

2021-06-29 13:26 UTC, danielamorse commented on packages/layouts/bolt-layout/package.json
> +    "@bolt/core-v3.x": "^3.1.0"
Change to `4.0.0` _after_ merging in master (if necessary)

2021-06-29 19:45 UTC, cjwhitedev commented
> - Resolve conflict with master
> - Set `@bolt/layouts-layout` version to `4.0.0`
> - Add `@bolt/layouts-layout` as dependency to starter-kit (currently included without listing as. dependency)

@mikemai2awesome I resolved the merge conflict, just double check that for me please. Looking into the starter-kit stuff now.

2021-06-29 21:44 UTC, mikemai2awesome requested changes
@cjwhitedev Thanks, I have to fix some doc typos before this is ready.

2021-07-01 16:44 UTC, mikemai2awesome approved these changes
Docs are fixed.

2021-07-01 18:16 UTC, danielamorse approved these changes
Approved, nice work guys.

FYI @mikemai2awesome I'm going to fix the [accordion scroll jank](https://pegadigitalit.atlassian.net/browse/DS-524) issue separately.

2021-07-01 18:16 UTC, merged