DS-302: Band twig update
boltdesignsystem/bolt pull request #2077
Opened 2021-01-15 17:03 UTC by cjwhitedev

## Jira

[https://pegadigitalit.atlassian.net/browse/DS-302](https://pegadigitalit.atlassian.net/browse/DS-302)

## Summary

update band twig conventions

## Details

band still used the old validation so this updates background validation to use `{% set this = init(schema) %}`. also used this time to remove `base_class` variable and update as many other twig standards as I could manage.

## How to test

- test unexpected props and classes.
- visually test demos against master.

2021-01-15 18:23 UTC, danielamorse requested changes

2021-01-15 18:23 UTC, danielamorse commented on packages/components/bolt-band/band.schema.js
> +      enum: ['start', 'center', 'end', 'top', 'bottom', '25%'],
If "middle" is default, it should be included in `enum`.

2021-01-15 18:23 UTC, danielamorse commented on packages/components/bolt-band/src/band.twig
> +{% if contentTag %}
I'd move this deprecation block above `init()` with the other deprecations as it was before and simply output `this.data.tag.value` below:
```
<{{ this.data.tag.value }} ...>
```

Unless there's another reason to move it here?

2021-01-15 18:23 UTC, danielamorse commented on packages/components/bolt-band/src/band.twig
> +  {{ this.props|without("content")|without("class") }}
Was going to say add "items" here, but actually `init()` ignores deprecated props. So, just right as is 👍

2021-01-15 18:23 UTC, danielamorse commented on packages/components/bolt-band/src/band.twig
> -{% set attributes = create_attribute(attributes|default({})) %}
Ah ha! We have found one of the exceptions where `attributes` (not just `inner_attributes`) is required. Look at the original Twig file. `attributes` is output twice, once on the outer element and once inside. This is not the way we do it today (we don't allow arbitrary attributes anywhere except the outer element), but for backwards compatibility we must output the attributes inside the component as they were before (see line 115 below).

2021-01-15 19:19 UTC, cjwhitedev commented on packages/components/bolt-band/src/band.twig
> +{% if contentTag %}
@danielamorse i didnt do a normal depreciation because i cant do {% set this.data.tag.value %} so i had to deprecate this a different way and i mimicked how we did it on background. that said, i can still move this up.

2021-01-15 19:23 UTC, cjwhitedev commented on packages/components/bolt-band/src/band.twig
> +{% if contentTag %}
actually, moving it before inti() breaks everything.

2021-01-15 20:34 UTC, mikemai2awesome requested changes

2021-01-15 20:34 UTC, mikemai2awesome commented on packages/components/bolt-band/band.schema.js
> +      enum: ['middle', 'start', 'center', 'end', 'top', 'bottom', '25%'],
where did all these options come from??? @danielamorse @cjwhitedev

2021-01-15 20:36 UTC, cjwhitedev commented on packages/components/bolt-band/band.schema.js
> +      enum: ['middle', 'start', 'center', 'end', 'top', 'bottom', '25%'],
@mikemai2awesome when the validator started working I was getting barked at. So those are being passed in somewhere.

2021-01-15 20:37 UTC, cjwhitedev commented on packages/components/bolt-band/band.schema.js
> +      enum: ['middle', 'start', 'center', 'end', 'top', 'bottom', '25%'],
except middle, we added middle because it was the default

2021-01-15 20:39 UTC, mikemai2awesome commented on packages/components/bolt-band/band.schema.js
> +      enum: ['middle', 'start', 'center', 'end', 'top', 'bottom', '25%'],
Go to those places and remove or fix them. Look at the CSS and the classes produced in twig, there's only start, center and end. Someone was making mistakes.

2021-01-15 20:42 UTC, mikemai2awesome commented on packages/components/bolt-band/band.schema.js
> +      enum: ['middle', 'start', 'center', 'end', 'top', 'bottom', '25%'],
Also this prop should not exist, it's completely ignored because of how content is build on Drupal, there's always a grid in a band, the grid handles this. This would just conflict with the grid and produce undesired results.

2021-01-15 20:45 UTC, cjwhitedev commented on packages/components/bolt-band/band.schema.js
> +      enum: ['middle', 'start', 'center', 'end', 'top', 'bottom', '25%'],
@mikemai2awesome so should we just deprecate it?

2021-01-19 19:34 UTC, cjwhitedev commented on packages/components/bolt-band/band.schema.js
> +      enum: ['middle', 'start', 'center', 'end', 'top', 'bottom', '25%'],
@mikemai2awesome there was an issue with variables in a background demo. this should be working as intended now.

2021-01-19 19:35 UTC, cjwhitedev commented on packages/components/bolt-band/band.schema.js
> +      enum: ['middle', 'start', 'center', 'end', 'top', 'bottom', '25%'],
https://github.com/boltdesignsystem/bolt/pull/2077/files#diff-7c7d18d446f59a4185ca5b588e4261b5392871aedf92c77c6d305e418731dc8cR81

2021-01-19 20:14 UTC, mikemai2awesome commented on packages/components/bolt-band/band.schema.js
> +      enum: ['middle', 'start', 'center', 'end', 'top', 'bottom', '25%'],
Ok, so it was confused with the background component's `valign` prop. Thanks for fixing it.

2021-01-19 20:17 UTC, mikemai2awesome requested changes

2021-01-19 20:17 UTC, mikemai2awesome commented on docs-site/src/pages/pattern-lab/_patterns/40-components/background/35-background-valign-variations.twig
> +          valign: image_valign
The reason that the `valign` was passed incorrectly because this include does not have the `only` keyword. Let's make sure to add `only` in the closing tag. @cjwhitedev

2021-01-19 20:25 UTC, cjwhitedev commented on docs-site/src/pages/pattern-lab/_patterns/40-components/background/35-background-valign-variations.twig
> +          valign: image_valign
thanks mike, i added that so im resolving.

2021-01-19 20:25 UTC, cjwhitedev commented
@danielamorse @mikemai2awesome I think all thats left is to confirm that the failed tests can be overwritten. They look good to me but I wanted to confirm with someone else.

2021-01-20 20:32 UTC, mikemai2awesome approved these changes
@cjwhitedev Since the markup changed because you fixed a few things. You just need to update the tests to make it pass. This is good otherwise.

2021-01-26 16:53 UTC, danielamorse approved these changes

2021-01-26 16:53 UTC, merged