[DO NOT MERGE] DS-214 Post-list Component POC
boltdesignsystem/bolt pull request #2080
Opened 2021-01-20 23:18 UTC by mikemai2awesome

# WIP

## Jira

(Enter a link to the Jira issue this PR applies to, if any)

## Summary

(Enter a one-line summary of the changes in this PR.  This will be included in the release notes)

## Details

(Explain the changes in enough detail fo reviewers to understand.  Raise any questions for reviewers to consider.)

## How to test

(List clear steps to test that the changes are working)

## Release notes

(Optionally, add details that will be added to the release notes. Use this to call out deprecations. [Read more](https://intuit.github.io/auto/docs/generated/changelog#additional-release-notes))

2021-02-05 15:22 UTC, danielamorse reviewed
Nice, this will be great to have on Academy. Code review and xbrowser testing are all good. I left a couple comments inline.

When status items wrap do you still want the left border?
![image](https://user-images.githubusercontent.com/36336/107051840-ec2e1680-679a-11eb-9301-38a941e1aefa.png)

Currently this doesn't give users a way to modify the content of the actions (reply, favorite, etc). I assume that's something they'll need in order to integrate it with Drupal. Any thoughts?

2021-02-05 15:22 UTC, danielamorse commented on packages/components/bolt-post/src/post.twig
> +{% set _post_id = _post_id|default(bolt.data.config.env == 'test' ? 'js-test-target' : 'js-bolt-post-' ~ random()) %}
It looks like `_post_id` is only set internally, i.e. you don't ever pass `_post_id` into the template. Is the `default()` necessary?

2021-02-05 15:22 UTC, danielamorse commented on packages/components/bolt-post/src/post.twig
> +      {% if headline.link_attributes %}
If you're setting `_headline_link_attributes` variable, might as well use it on this line too.

2021-02-05 15:28 UTC, mikemai2awesome commented on packages/components/bolt-post/src/post.twig
> +      {% if headline.link_attributes %}
that was my thought, but it didn't work as expected. we can look at it together.

2021-02-05 15:29 UTC, mikemai2awesome commented on packages/components/bolt-post/src/post.twig
> +{% set _post_id = _post_id|default(bolt.data.config.env == 'test' ? 'js-test-target' : 'js-bolt-post-' ~ random()) %}
oh right, i should just set the var straight.

2021-02-05 19:24 UTC, mikemai2awesome commented on packages/components/bolt-post/src/post.twig
> +      {% if headline.link_attributes %}
now it works. not sure why it was not working before. previously it was rendering all the props as attributes, things like `reversed_underline` and `expand_click_target` were added as attributes. weird.

2021-02-05 19:37 UTC, mikemai2awesome commented
@danielamorse The border is fine. It lines up the content, without it then it looks like the items are indented.

Good catch on the popover actions, I need to pick your brains on that.

2021-02-05 22:40 UTC, mikemai2awesome commented
@danielamorse Action menu and share menu props are updated after our discussion.

2021-02-09 23:12 UTC, danielamorse approved these changes
Updates look good, approved.

This has me thinking about how we use nested props. Nested props make sense here -- you do want all headline props to be under `headline` once there are enough of them. But we're not leveraging `init()` when we do that, and then we end up with a mix of conventions.

I'm good merging this as is, but I'd like to discuss this use case in huddle tomorrow.

2021-02-17 13:23 UTC, deepakqkumar commented
@mikemai2awesome - on pages where we have unfavorite or unsubscribe icons before the node type icon, can you help understand how we should insert those action icons with this new component?
![image](https://user-images.githubusercontent.com/4835849/108210338-6b372d80-7151-11eb-960d-d4db84396609.png)

2021-02-17 15:20 UTC, mikemai2awesome commented
Hi @deepakqkumar, as we discussed in Slack, all actions are consolidated into the action menu popover.
![Screen Shot 2021-02-17 at 10 19 06 AM](https://user-images.githubusercontent.com/3027663/108225283-c9402280-7109-11eb-8e0f-3b6ac876e625.png)

2021-02-25 14:58 UTC, remydenton requested changes
I think the main thing to do before merging is change the component name to 'listing teaser'.  I added one other optional comment.

2021-02-26 17:56 UTC, mikemai2awesome commented on packages/components/bolt-post/post.schema.js
> +          description: 'Set the text of the headline.',
Updated.

2021-02-26 19:49 UTC, mikemai2awesome commented
@remydenton Renamed and updated schema as instructed.

2021-02-26 21:00 UTC, remydenton approved these changes
Updates look great, thanks @mikemai2awesome.

2021-02-26 21:49 UTC, merged