DS-308: card-replacement twig update
boltdesignsystem/bolt pull request #2095
Opened 2021-02-03 20:26 UTC by cjwhitedev

## Jira

[https://pegadigitalit.atlassian.net/browse/DS-308](https://pegadigitalit.atlassian.net/browse/DS-308)

## Summary

update card-replacement twig conventions

## Details

card-replacement still used the old validation so this updates background validation to use `{% set this = init(schema) %}`. also used this time to remove `base_class` variable and update as many other twig standards as I could manage.

## How to test

- test unexpected props and classes.
- visually test demos against master.

2021-02-08 22:20 UTC, danielamorse reviewed
@cjwhitedev left some inline comments and questions.

2021-02-08 22:20 UTC, danielamorse commented on packages/components/bolt-card-replacement/src/card-replacement/card-replacement.scss
> -    min-height: 100%;
I understand why we need to change CSS since the default `height="full"` value is no longer output (that's good), but this does set `height="auto"` to `display: flex`, which I don't think is necessary. @mikemai2awesome any concerns?

2021-02-10 16:48 UTC, cjwhitedev commented on packages/components/bolt-card-replacement/src/card-replacement-actions/_card-replacement-action.twig
> +{% set this = init(schema) %}
we talked about setting the schema like:
```
{% set schema = bolt.data.components["@bolt-components-card-replacement"].schema.action.properties %}
```

2021-02-10 16:48 UTC, cjwhitedev commented
we also talked about using single quotes wherever possible

2021-02-10 17:00 UTC, mikemai2awesome commented on packages/components/bolt-card-replacement/src/card-replacement/card-replacement.twig
> -  {% if rounded %} rounded {% endif %}
@danielamorse we should just kill it, this was never in the schema, it was a salem hack.

2021-02-10 17:12 UTC, mikemai2awesome requested changes

2021-02-10 17:12 UTC, mikemai2awesome commented on packages/components/bolt-card-replacement/src/card-replacement/card-replacement.scss
> -    min-height: 100%;
@danielamorse is right, you don't want to turn on flex for auto height, this could potentially break certain layouts on prod. And this is also a breaking change. If there is any web component usage out there, they will break.

Before this update, this means auto height:
```html
<bolt-card-replacement>...</bolt-card-replacement>
```

After this update, this means full height:
```html
<bolt-card-replacement>...</bolt-card-replacement>
```

2021-03-18 19:22 UTC, cjwhitedev commented on packages/components/bolt-card-replacement/src/card-replacement-actions/_card-replacement-action.twig
> +        {% if this.data.spacing.value is not empty %}
I think we do need it here. somehow its a null var in some cases, so i think removing it would be a breaking change.

2021-03-19 14:16 UTC, cjwhitedev commented on packages/components/bolt-card-replacement/src/card-replacement-actions/_card-replacement-action.twig
> +{% set this = init(schema) %}
Hey @danielamorse im not sure this works. I'm doing:
```
{% set schema = bolt.data.components["@bolt-components-card-replacement"].schema.actions.properties %}
{% set this = init(schema) %}

<script>
  console.log({{ this.data|json_encode() }})
</script>
```
and it looks like its logging the data for the parent element. Is it inherited?

2021-03-19 14:18 UTC, cjwhitedev commented on packages/components/bolt-card-replacement/src/card-replacement/card-replacement.scss
> -    min-height: 100%;
@mikemai2awesome this should be resolved in the latest commit. can you confirm?

2021-03-19 14:19 UTC, cjwhitedev commented on packages/components/bolt-card-replacement/src/card-replacement/card-replacement.twig
> -  {% if rounded %} rounded {% endif %}
perfect. resolving this.

2021-03-19 14:19 UTC, cjwhitedev commented on packages/components/bolt-card-replacement/src/card-replacement/card-replacement.twig
> -  {% if link_url %} url="{{ link_url }}" {% endif %}
@danielamorse i put `link_url` back in with the latest commit. can you confirm it is working as expected?

2021-03-19 14:19 UTC, cjwhitedev commented on packages/components/bolt-card-replacement/src/card-replacement-body/_card-replacement-body.twig
> -<bolt-card-replacement-body {{ attributes }}>
I think you're right. I put this back in the latest commit. resolving.

2021-04-15 12:18 UTC, closed without merging

2021-04-15 12:18 UTC, colbytcook commented
This PR is only for reference purposes