Feature/ds 303 button twig update
boltdesignsystem/bolt pull request #2103
Opened 2021-02-10 16:50 UTC by cjwhitedev

## Jira

[https://pegadigitalit.atlassian.net/browse/DS-303](https://pegadigitalit.atlassian.net/browse/DS-303)

## Summary

update button twig conventions

## Details

button still used the old validation so this updates background validation to use `{% set this = init(schema) %}`. also used this time to remove `base_class` variable and update as many other twig standards as I could manage. we're also trying to use single quotes instead of double quotes wherever possible.

## How to test

- test unexpected props and classes.
- visually test demos against master.

2021-02-13 00:26 UTC, danielamorse reviewed
@cjwhitedev nice job, this is a very tricky one. Button has a lot of gotchas. We're pretty close.

I'm in the process of addressing these inline comments myself cause I was already in the weeds debugging this stuff. I will finish this up on Tuesday.

2021-02-18 22:56 UTC, danielamorse commented on packages/components/bolt-button/src/button.scss
> +  @if $radius-name == 'full' {
@mikemai2awesome wanted to point out this edit to you. I noticed we were outputting unused radius values here.

2021-02-18 22:57 UTC, danielamorse approved these changes

2021-02-19 15:38 UTC, mikemai2awesome requested changes
@cjwhitedev Just one small update needed, the doc page still says "Style", we need to update it to "Hierarchy".

2021-02-22 15:42 UTC, mikemai2awesome commented on packages/components/bolt-button/src/button.scss
> +  @if $radius-name == 'full' {
Yup all good.

2021-02-26 19:24 UTC, danielamorse commented
> @cjwhitedev Just one small update needed, the doc page still says "Style", we need to update it to "Hierarchy".

@mikemai2awesome this is the change you requested right? https://github.com/boltdesignsystem/bolt/pull/2103/commits/4ccfb9123bc59a61474f129b89fec5e30559dba9

2021-02-26 19:37 UTC, mikemai2awesome approved these changes

2021-02-26 19:38 UTC, merged