[DO NOT MERGE] DS-296 Image Element
boltdesignsystem/bolt pull request #2105
Opened 2021-02-10 22:39 UTC by mikemai2awesome

## Jira

(Enter a link to the Jira issue this PR applies to, if any)

## Summary

(Enter a one-line summary of the changes in this PR. This will be included in the release notes)

## Details

(Explain the changes in enough detail fo reviewers to understand. Raise any questions for reviewers to consider.)

## How to test

(List clear steps to test that the changes are working)

## Release notes

(Optionally, add details that will be added to the release notes. Use this to call out deprecations. [Read more](https://intuit.github.io/auto/docs/generated/changelog#additional-release-notes))

### Visual changes

(Note any visual changes associated with this PR. This will be shared with QA team for VRT.)

2021-02-22 14:13 UTC, colbytcook commented
This work is in a draft state until we start the Bolt Image sprint.

2021-07-21 14:16 UTC, colbytcook commented on docs-site/src/pages/pattern-lab/_patterns/20-elements/image/05-image.twig
> +    <bolt-li>If responsiveness is not needed, please use a plain <bolt-code-snippet display="inline">&lt;img&gt;</bolt-code-snippet> element instead.</bolt-li>
@mikemai2awesome is there a use case for a non-responsive image?

2021-07-21 14:27 UTC, colbytcook approved these changes

2021-07-21 14:28 UTC, colbytcook commented
Approved, just have a quick question

2021-07-21 20:19 UTC, danielamorse requested changes
@mikemai2awesome looking great. I love the simplicity. The docs are really well written, even if the topic of `srcset` and `sizes` is hard to grasp.

I made a couple minor fixes and made one inline change request.

2021-07-21 20:19 UTC, danielamorse commented on packages/elements/bolt-image/src/image.twig
> +  this.data.fill.value ? 'e-bolt-image--fill',
@mikemai2awesome changed to `this.data.foo.value`. Must use `.value` when doing a conditional check with the data that comes back from `init()`. Otherwise, the presence of any value will be truthy.

2021-07-21 20:19 UTC, danielamorse commented on packages/elements/bolt-image/src/image.twig
> +{% spaceless %}<img {{ attributes.addClass(classes) }} alt="{{ alt }}" src="{{ src }}" {% if srcset %}srcset="{{ srcset }}"{% endif %} {% if sizes %}sizes="{{ sizes }}"{% endif %}>{% endspaceless %}
@mikemai2awesome all of the attributes listed individually here are passed through `attributes`. Listing them out individually will output them twice (view source rather than inspecting with dev tools and you'll see). All that's needed is `attributes.addClass(classes)`.

2021-07-26 18:30 UTC, mikemai2awesome commented on docs-site/src/pages/pattern-lab/_patterns/20-elements/image/05-image.twig
> +    <bolt-li>If responsiveness is not needed, please use a plain <bolt-code-snippet display="inline">&lt;img&gt;</bolt-code-snippet> element instead.</bolt-li>
yes, something like a avatar photo that stays at 48px by 48px.

2021-07-26 18:45 UTC, remydenton commented on packages/elements/bolt-image/src/image.twig
> +{% spaceless %}<img {{ attributes.addClass(classes) }} alt="{{ alt }}" src="{{ src }}" {% if srcset %}srcset="{{ srcset }}"{% endif %} {% if sizes %}sizes="{{ sizes }}"{% endif %}>{% endspaceless %}
+1, this should probably just look like this:

```suggestion
{% spaceless %}<img {{ attributes.addClass(classes) }}>{% endspaceless %}
```
I'm also confused about the use of `{% spaceless %}` here.  Per the docs:
> Use the spaceless tag to remove whitespace between HTML tags, not whitespace within HTML tags or whitespace in plain text

There's only one self-closing HTML tag here, so I'm not sure how we'd ever end up with whitespace between tags 🤔 .  Maybe this all boils down to the following?

```suggestion
<img {{ attributes.addClass(classes) }}>
```

2021-07-26 18:48 UTC, remydenton requested changes
See inline comment about attributes.  Otherwise, this looks great, such an improvement over the image component 😂

2021-07-26 21:55 UTC, mikemai2awesome commented on packages/elements/bolt-image/src/image.twig
> +  this.data.fill.value ? 'e-bolt-image--fill',
thanks for the change

2021-07-26 22:01 UTC, mikemai2awesome commented on packages/elements/bolt-image/src/image.twig
> +{% spaceless %}<img {{ attributes.addClass(classes) }} alt="{{ alt }}" src="{{ src }}" {% if srcset %}srcset="{{ srcset }}"{% endif %} {% if sizes %}sizes="{{ sizes }}"{% endif %}>{% endspaceless %}
Updated, removed all that.

2021-07-27 14:02 UTC, danielamorse approved these changes

2021-07-27 14:15 UTC, remydenton approved these changes

2021-07-27 15:55 UTC, merged