DS-323: deprecate auto slides per view. set max slides to 4.
boltdesignsystem/bolt pull request #2108
Opened 2021-02-16 14:57 UTC by cjwhitedev

## Jira

[https://pegadigitalit.atlassian.net/browse/DS-323](https://pegadigitalit.atlassian.net/browse/DS-323)

## Summary

Allow users to have 4 slides per view.

## Details

Change schema to allow 4 slides per view and a max sliders per view of 4. Deprecate auto from slides per view to avoid further confusion.

## How to test

Check out carousel demos

## Release notes

Deprecate auto value from carousel `slides_per_group` prop

2021-02-16 22:37 UTC, mikemai2awesome requested changes

2021-02-16 22:37 UTC, mikemai2awesome commented on packages/components/bolt-carousel/carousel.schema.js
> +      default: 4,
We are changing a default here, is this a breaking change?

2021-02-17 13:03 UTC, cjwhitedev commented on packages/components/bolt-carousel/carousel.schema.js
> +      default: 4,
It is not. The only case where the default mattered as far as I can tell is when folks used `auto` sliders per view. We're removing that option so changing the max will not have an effect.

2021-02-17 21:17 UTC, remydenton commented on packages/components/bolt-carousel/carousel.schema.js
> +      default: 4,
We had a giant convo in Slack about this on Friday.  It will only affect carousels that have `slides_per_view` set to `auto`, which is not the default.  The rationale for this change is a) not many carousels will have `auto` selected since it's functionally the same as `3` and b) if `auto` _is_ selected, the intention is to have the number determined automatically, which it still is, it will now just be 4 if 4 items will fit.

2021-02-17 21:21 UTC, remydenton approved these changes
Looks great.  I love how we don't even have to update the PL demo since it pulls automatically from schema!

2021-02-18 20:27 UTC, danielamorse approved these changes
Nicely work, works perfectly 👍

2021-02-18 20:30 UTC, mikemai2awesome approved these changes

2021-02-18 22:05 UTC, merged