[DO NOT MERGE] DS-322 Teaser Replacement
boltdesignsystem/bolt pull request #2123
Opened 2021-03-05 17:51 UTC by cjwhitedev

## Jira

[https://pegadigitalit.atlassian.net/browse/DS-322](https://pegadigitalit.atlassian.net/browse/DS-322)

## Summary

A new Teaser component to replace the text one.

## Details

A new Teaser component to replace the text one and be used for best of content.

## How to test

Read my code and check out my demos.

## Release notes

Removes old text based Teaser, Replaces it with a new component.

2021-03-06 01:54 UTC, mikemai2awesome requested changes
@cjwhitedev Overall, good job. The twig template is solid. I made some updates to further this.

I reconfigured the meta, views, and description based on Yao's feedback. The meta (duration or time read) is on the bottom right of thumbnail, description is truncated with ellipsis, views stays at the same place, premium appears on hover and it doesn't block description, and only video has type signifier shown.

Also I tightened and organized the CSS. Let's try to avoid writing one big blob with `&` nested inside. It's ok to use `&` sparingly, once the nesting gets really long, It is really hard to read. I've grouped all relevant rules together now so we don't have to scroll up and down to see what modifier does what. Remember to use `@at-root` to your advantage, it is very helpful for organizing CSS.

## To Do:

1. Remove `article` from type. Only `video`, `external-link`, and `PDF`.
2. Update demo with fallback image. There are couple images provided by Yao that will be defaults for external-link and PDF if no image is passed. We need to demonstrate this. I'll get you the images.
3. Let's have `content` and `show_on_hover` under `description` prop. Grouping the two together.
4. Build out the like button because this needs to look exactly like the share button. No styles should be changed, we need to lock it down. The only thing they should do is add attributes.
5. Remove `eyebrow_text` and create `featured` boolean instead.
6. Lastly, group `views`, `featured`, and `premium` under `status`.

2021-03-06 20:00 UTC, mikemai2awesome commented on packages/components/bolt-teaser/src/teaser.twig
> +        {% if headline.size %}
Changed this to make it exactly like how we built listing teaser.

2021-03-06 20:00 UTC, mikemai2awesome commented on docs-site/src/pages/pattern-lab/_patterns/40-components/teaser/90-teaser-horizontal.twig
> +{% set _image %}
Removed the underscore in demos.

2021-03-08 15:07 UTC, cjwhitedev commented
@mikemai2awesome

1. Remove article from type. Only video, external-link, and PDF.
    - Should this even be a type if we’re not showing signifiers for others? Should it just be like an is_video boolean or something?
2. Update demo with fallback image. There are couple images provided by Yao that will be defaults for external-link and PDF if no image is passed. We need to demonstrate this. I’ll get you the images.
    - I’ll look out for the images, thank you.
3. Let’s have content and show_on_hover under description prop. Grouping the two together.
    - that makes sense, I’ll get on this.
4. Build out the like button because this needs to look exactly like the share button. No styles should be changed, we need to lock it down. The only thing they should do is add attributes.
    - I’m not sure what you mean by this, like it should be a part of the component instead of passed in on the template side? How would we handle that? The drupal guys will need to manipulate whether or not someting is “liked”
5. ~~Remove eyebrow_text and create featured boolean instead.~~ Done. Added featured prop and kept eyebrow_text for customization.
    - thank you
6. Group views, featured, and premium under status.
    - I’m not sure what you mean by this either? just group them in the schema? so it would be like status.views and status.featured ? I thought we wanted to keep the views section a little more open for the drupal guys?
7. Lastly, we need to clean up schema writings and doc pages.
    - yeah i just wanted to get the component out for review, i knew the docs werent ready.

2021-03-09 20:18 UTC, danielamorse reviewed
@cjwhitedev this is looking really good. It's a pretty complex component, so nice job pulling it all together.

I edited the [Like button JS](https://github.com/boltdesignsystem/bolt/pull/2123/files#diff-cf6231b754e50374c473703ec74470eb31c62156a5bd176d3e9f8d4ba8458c0dR76) and updated [the Jest test](https://github.com/boltdesignsystem/bolt/pull/2123/files#diff-ec857acc388c552e4c6ffbf61df8ec102c3929ac651773572ce7368f6d08768d). Take a look and let me know if you have any questions.

Not approving yet because I know the demos are still in progress, but so far so good 👌

2021-03-09 21:56 UTC, danielamorse commented
@cjwhitedev @mikemai2awesome a couple things I did notice reviewing:
- When you hover over the "Featured" element you can see it seems to be on top of the clickable link area, cursor goes from "pointer" to "text". More noticeable on small-screen.
- On the [version with a dark theme](https://boltdesignsystem-54kw74vmj-boltdesignsystem.vercel.app/pattern-lab/patterns/40-components-teaser-90-teaser-00/40-components-teaser-90-teaser-00.html) the Share menu is also dark. Is this intended?

2021-03-09 22:40 UTC, mikemai2awesome commented
@danielamorse Thanks, I just fixed that eyebrow. As for the share menu, that's how it's been working since it was released, it adapts to the themes.

2021-03-10 21:03 UTC, mikemai2awesome approved these changes
Please proof read all the docs and demos. They are all set now.

@cjwhitedev @remydenton @danielamorse

2021-03-11 16:30 UTC, remydenton requested changes
Looking great guys.  I pushed one fix to jest tests (please confirm that we do want the chevron if the headline is linked-- I believe we do).  I had a few inline comments that need addressing, and a few others that are just questions.

2021-03-11 16:30 UTC, remydenton commented on packages/components/bolt-teaser/teaser.schema.js
> +      enum: ['pdf', 'video', 'external-link'],
What do types of `pdf` or `external-link` do?  I don't see any logic in the twig (not to mention demos) for them.

2021-03-11 16:30 UTC, remydenton commented on packages/components/bolt-teaser/teaser.schema.js
> +    },
I don't fully understand how `like_button_attributes` is supposed to work.  Or more importantly, how do I indicate from the Drupal side a) whether I want the like button to appear and b) whether the current user has liked this teaser?  Note that the later may need to happen using javascript.

2021-03-11 16:30 UTC, remydenton commented on packages/components/bolt-teaser/teaser.schema.js
> +      description: 'Set a breif description of the resource.',
Nitpick, i before e...

2021-03-11 16:30 UTC, remydenton commented on packages/components/bolt-teaser/teaser.schema.js
> +    // @TODO: meta or meta_items reserved for author and posted date info?
Just to clarify, is the idea that `views`, `like`, and `share` are all very opinionated and should not accept other kinds of content, but there could conceivably be other types of content in the future?

2021-03-11 16:30 UTC, remydenton commented on packages/components/bolt-teaser/src/teaser.twig
> +                  content: 'Like',
All strings in source code twig files need the `|t` function so they can be translated, e.g. `'Like'|t`

2021-03-11 16:30 UTC, remydenton commented on packages/components/bolt-teaser/src/teaser.twig
> +                    content: 'Share',
Needs |t

2021-03-11 17:48 UTC, colbytcook commented on docs-site/src/pages/pattern-lab/_patterns/40-components/teaser/10-teaser-layout.twig
> +    <bolt-li>Horizontal teaser accepts 1:1 (square) aspect ratio signifier.</bolt-li>
@mikemai2awesome should we mention that images with something other than 1:1 aspect ratio will be cropped on a Horizontal layout? We mentioned it in the teaser page but just to be safe, lets mention it here?

2021-03-11 18:09 UTC, mikemai2awesome commented on packages/components/bolt-teaser/teaser.schema.js
> +      enum: ['pdf', 'video', 'external-link'],
@remydenton currently only video does something, but it is subject to change because the design is evolving. This is scalable as they keep adding different types (for example, blog post) and the design changes to accommodate them.

2021-03-11 18:12 UTC, colbytcook commented on docs-site/src/pages/pattern-lab/_patterns/40-components/teaser/10-teaser-layout.twig
> +    <bolt-li>Horizontal teaser accepts 1:1 (square) aspect ratio signifier.</bolt-li>
I updated this with 
`{% set notes %}
  <bolt-ol>
    <bolt-li>Vertical or responsive teaser accepts 16:9 aspect ratio signifier. Any other aspect ratio will automatically be cropped to a 16:9 ratio.</bolt-li>
    <bolt-li>Horizontal teaser accepts 1:1 (square) aspect ratio signifier. Any other aspect ratio will automatically be cropped to a 1:1 ratio.</bolt-li>
  </bolt-ol>
{% endset %}`

2021-03-11 18:13 UTC, mikemai2awesome commented on packages/components/bolt-teaser/teaser.schema.js
> +    },
You can add any attributes here, so if you target it with something like `js-like-button`, you can do whatever JS you need. Does that make sense. An example is in the docs.

2021-03-11 18:16 UTC, mikemai2awesome commented on packages/components/bolt-teaser/teaser.schema.js
> +    // @TODO: meta or meta_items reserved for author and posted date info?
@remydenton Yes, we are reserving the name `meta` or `meta_items` for things like Posted by [Author Name] or Posted at [Date]. Again, content is evolving and blog post can become a type soon. We need to be ready to scale.

2021-03-11 18:29 UTC, remydenton commented on packages/components/bolt-teaser/src/teaser.twig
> +                    content: 'Share',
```suggestion
                    content: 'Share'|t,
```

2021-03-11 18:29 UTC, remydenton commented on packages/components/bolt-teaser/src/teaser.twig
> +                  content: 'Like',
```suggestion
                  content: 'Like'|t,
```

2021-03-11 18:29 UTC, remydenton commented on packages/components/bolt-teaser/teaser.schema.js
> +      description: 'Set a breif description of the resource.',
```suggestion
      description: 'Set a brief description of the resource.',
```

2021-03-11 18:30 UTC, mikemai2awesome commented on docs-site/src/pages/pattern-lab/_patterns/40-components/teaser/10-teaser-layout.twig
> +    <bolt-li>Horizontal teaser accepts 1:1 (square) aspect ratio signifier.</bolt-li>
Yes add it.

2021-03-11 21:35 UTC, danielamorse requested changes
The share menu is clipped by carousel and is behind the carousel dots. I'm not sure this can be fixed without the Popover overhaul:
![image](https://user-images.githubusercontent.com/36336/110857897-66185a80-8287-11eb-8560-2ee5d558e782.png)

Also, I'm not a fan of the pastrami-ispum, but if you guys like it I won't be a party pooper 😆

2021-03-11 21:46 UTC, danielamorse approved these changes
We will fix the popover issue next sprint with https://pegadigitalit.atlassian.net/browse/DS-239.

The only other issue I see is the shadows around quick filters but I know @mikemai2awesome is fixing that separately.

2021-03-11 21:53 UTC, colbytcook approved these changes

2021-03-12 16:26 UTC, mikemai2awesome commented on packages/components/bolt-teaser/teaser.schema.js
> +    },
`like` and `share` props created to replace the old ones.

2021-03-12 18:54 UTC, danielamorse approved these changes

2021-03-12 19:10 UTC, charginghawk approved these changes

2021-03-12 19:41 UTC, remydenton approved these changes
:shipit:

2021-03-12 20:26 UTC, merged