[Do Not Merge] DS-333: replace onClick and onClickTarget with snake case
boltdesignsystem/bolt pull request #2132
Opened 2021-03-17 19:37 UTC by cjwhitedev

## Jira

[https://pegadigitalit.atlassian.net/browse/DS-333](https://pegadigitalit.atlassian.net/browse/DS-333)

## Summary

deprecate onClick and onClickTarget in BoltActionElement in favor of snake case

## Details

Replace BoltActionElement properties onClick and onClickTarget with snake case counterparts, on_click and on_click_target

## How to test

Make sure none of the demos are broken, and confirm that any precautions put in place would prevent disaster. Also confirm I didn't miss any uses of the camel case props.

## Release notes

deprecate onClick and onClickTarget for snake case.

2021-03-18 20:55 UTC, danielamorse requested changes
@cjwhitedev, looks good! See my comment about converting `packages/base-element/src/BoltActionElement.js`. Then PR this and send for review 👍

2021-03-18 20:55 UTC, danielamorse commented on packages/components/bolt-link/src/link.twig
> +{% if on_click_target or attributes["on-click-target"] %}
We haven't converted Link to use `init()` yet? Totally missed this. Is there a ticket to convert this component?

2021-03-18 20:55 UTC, danielamorse commented on packages/base-element/src/BoltActionElement.js
> +      on_click_target: {
Here in the JS these will always be camelCase, only snake case in the schema and Twig.

If you import the schema and convert this base Class to use the `...this.props` pattern they will be automatically converted for you. I suggest doing that, just like you did on a bunch of other components.

2021-03-18 20:55 UTC, danielamorse commented on packages/base-element/src/BoltActionElement.schema.js
> +    onClick: {
Nice, deprecate it here and import this everywhere 👌

2021-03-19 13:39 UTC, cjwhitedev commented on packages/components/bolt-link/src/link.twig
> +{% if on_click_target or attributes["on-click-target"] %}
[https://pegadigitalit.atlassian.net/browse/DS-372](https://pegadigitalit.atlassian.net/browse/DS-372)

2021-03-19 15:21 UTC, cjwhitedev commented on packages/base-element/src/BoltActionElement.js
> +      on_click_target: {
should be resolved with my latest commit, but im not sure how to test it properly. the console log seemed correct at least.

2021-04-05 19:10 UTC, danielamorse approved these changes
Build is now passing 😅 

I increased the Jest timeout globally, but what I really think fixed it was that I updated the Button, Link, and Trigger snapshots which removed an old test result from the file. I'm not sure how it got in that state, but updating it seemed to fix everything.

2021-04-05 19:10 UTC, merged