DS-372: Standardize Twig and Schema (Link)
boltdesignsystem/bolt pull request #2145
Opened 2021-03-29 18:10 UTC by cjwhitedev

## Jira

[https://pegadigitalit.atlassian.net/browse/DS-372](https://pegadigitalit.atlassian.net/browse/DS-372)

## Summary

Standardize Twig and Schema for Link

## Details

Standardize Twig and Schema for Link

## How to test

Check out the tests and demos and make sure nothing is a breaking change in the code.

## Release notes

Deprecate `isHeadline` prop in favor or `is_headline`.

2021-03-30 12:40 UTC, colbytcook approved these changes

2021-03-30 21:02 UTC, danielamorse requested changes
Nicely done! Almost there. I left some inline comments and requested a few changes.

I think it'd be good to note a few details that might not be obvious to the reviewer in the 
**Details** section. For instance, I would mention that `shadow-root` is intentionally removed as it's no longer necessary, and that certain attributes no longer show up in the snapshots because they are default values that aren't output once we switch to use `init()`. I know these things because we've been looking at it together, but another reviewer might not. You don't have to go overboard with every detail, just the things you think a newcomer might not get right away.

2021-04-06 21:30 UTC, danielamorse approved these changes
Thanks for addressing the feedback @cjwhitedev . Approved, just waiting on https://github.com/boltdesignsystem/bolt/pull/2156 to be merged to fix failing Carousel tests.

2021-04-06 21:30 UTC, danielamorse commented on packages/components/bolt-link/src/link.twig
> +{% if href %}
@cjwhitedev I added this simple deprecation statement instead of [the old one](https://github.com/boltdesignsystem/bolt/pull/2145/files#diff-a570967cefe213c5d718a8efcdb554f61d28351886ef81a79a1b6b480a99de1fL31), which checked for both the prop and the attributes. `init()` will consolidate the props and the attributes _and_ add them to the `this.data` object, so it's safe to just check for the prop here.

2021-04-06 21:30 UTC, danielamorse commented on packages/components/bolt-link/src/link.twig
> +  {% if class starts with 'is-' == true %}
@cjwhitedev is the `== true` necessary? Looks like we're doing it both ways throughout the codebase. It would be nice to figure out the best way and normalize it.

2021-04-06 21:30 UTC, danielamorse commented on packages/components/bolt-link/src/link.twig
> -  {% if on_click %} on-click="{{ on_click }}" {% endif %}
@cjwhitedev we can remove these now that you've converted them to snake case and we're using `this.props` 🎉

2021-04-07 19:55 UTC, danielamorse commented on packages/components/bolt-link/src/link.twig
> +  {% if class starts with 'is-' == true %}
I checked and the `==` is not necessary. I updated this block to look like the example in the Wiki Twig example: https://github.com/boltdesignsystem/bolt/wiki/Twig%3A-Example-Component

2021-04-09 15:10 UTC, colbytcook approved these changes

2021-04-09 15:38 UTC, merged