DS-401: Standardize Twig and Schema (Background)
boltdesignsystem/bolt pull request #2189
Opened 2021-04-23 12:11 UTC by cjwhitedev

## Jira

[https://pegadigitalit.atlassian.net/browse/DS-401](https://pegadigitalit.atlassian.net/browse/DS-401)

## Summary

Standardize Twig and Schema for Background

## Details

Standardize Twig and Schema for Background. The snapshots have been updated because the default values of properties no longer need to be printed, and some have been re-ordered. For more detailed information, please see the initial ticket, as well as the associate TWIG and Schema tickets.

## How to test

Check out the tests and demos and make sure nothing is a breaking change in the code.

## Release notes

(Optionally, add details that will be added to the release notes. Use this to call out deprecations. [Read more](https://intuit.github.io/auto/docs/generated/changelog#additional-release-notes))

2021-04-27 21:41 UTC, danielamorse requested changes
@cjwhitedev looks good. Again, I just made a couple minor formatting tweaks:
- Space around `|` https://github.com/boltdesignsystem/bolt/pull/2189/commits/2d39746abed57091f262b038a6d496aa80e4f4f7
- Quotes around template data  https://github.com/boltdesignsystem/bolt/pull/2189/commits/294e01868cb40710859ae7e879ac6f5b2e26c1d3

Now that we've deprecated several props, we need to update usage of those props throughout PL (search the repo for `shapeGroup`, `shapeAlignment`, etc. and you'll find them). That can happen in a separate PR but we should try to ship that along with these updates if possible.

2021-04-29 19:02 UTC, cjwhitedev commented
> Now that we've deprecated several props, we need to update usage of those props throughout PL (search the repo for `shapeGroup`, `shapeAlignment`, etc. and you'll find them). That can happen in a separate PR but we should try to ship that along with these updates if possible.

@danielamorse I think i got them all in this last commit.

2021-04-30 19:01 UTC, mikemai2awesome approved these changes

2021-05-03 14:21 UTC, danielamorse approved these changes

2021-05-03 14:22 UTC, merged