CC-472 Add reply prop and styles
boltdesignsystem/bolt pull request #2192
Opened 2021-04-23 20:48 UTC by mikemai2awesome

## Jira

https://pegadigitalit.atlassian.net/browse/CC-472

## Summary

Adds a `reply` prop for the Listing Teaser component.

## Details

1. Added `reply` prop to showcase a relevant reply.
2. Updated CSS to style the reply content.
3. Added docs to demonstrate the `reply` prop.

## How to test

Run the branch locally and read the Listing Teaser props, especially the one with reply prop and Collaboration Center use case. Make sure the prop works as expected.

2021-04-26 11:27 UTC, adamszalapski requested changes
@mikemai2awesome I add few comments, please check.

2021-04-26 11:27 UTC, adamszalapski commented on packages/components/bolt-listing-teaser/src/listing-teaser.twig
> +      {% if this.data.reply %}
We shouldn't use `this.data` for checking content different than `string`. @danielamorse, @remydenton please correct me if I'm wrong. In this case, we should use `{% if reply %}`

2021-04-26 11:27 UTC, adamszalapski commented on packages/components/bolt-listing-teaser/src/listing-teaser.twig
> +            content: this.data.reply,
The same issue here we should pass `content: reply`

2021-04-26 11:27 UTC, adamszalapski commented on packages/components/bolt-listing-teaser/src/listing-teaser.twig
> +          {% set _reply_link %}
I noticed that right now `Go to reply` will point to the same place as a whole row (whole row clickability) but what I heard was that header should link to the post where the answer was added and `Go to replay` should point to that reply directly. I don't know if you know it @mikemai2awesome or maybe you agreed that we will change the existing approach.

2021-04-26 11:28 UTC, adamszalapski commented on packages/components/bolt-listing-teaser/src/listing-teaser.twig
> +          {% set _reply_link %}
Maybe we should add `reply_link` prop?

2021-04-26 13:11 UTC, mikemai2awesome commented on packages/components/bolt-listing-teaser/src/listing-teaser.twig
> +          {% set _reply_link %}
thanks for the heads up. let me make some changes

2021-04-26 15:22 UTC, mikemai2awesome commented on packages/components/bolt-listing-teaser/src/listing-teaser.twig
> +      {% if this.data.reply %}
all set

2021-04-26 15:22 UTC, mikemai2awesome commented on packages/components/bolt-listing-teaser/src/listing-teaser.twig
> +            content: this.data.reply,
all set

2021-04-26 15:22 UTC, mikemai2awesome commented on packages/components/bolt-listing-teaser/src/listing-teaser.twig
> +          {% set _reply_link %}
prop is updated

2021-04-26 16:55 UTC, adamszalapski approved these changes
Looks good, great job @mikemai2awesome

2021-04-27 12:10 UTC, colbytcook approved these changes

2021-04-27 20:06 UTC, remydenton approved these changes
Looks great, nice work.

2021-04-29 09:12 UTC, adamszalapski approved these changes
Everything ok, nice work @mikemai2awesome

2021-04-30 15:07 UTC, remydenton approved these changes

2021-05-03 21:39 UTC, merged