DS-464 add bell and flag icons
boltdesignsystem/bolt pull request #2197
Opened 2021-04-30 17:57 UTC by mikemai2awesome

## Jira

https://pegadigitalit.atlassian.net/browse/DS-464

## Summary

Adds `bell` and `flag` icons.

## Details

1. Compressed and cleaned up SVGs
2. Imported the SVGs to icons

## How to test

Run the branch locally and check the icon name variations doc, make sure the `bell` and `flag` icons are displaying correctly in both light and dark themes.

2021-04-30 18:06 UTC, cjwhitedev approved these changes
looks good to me

2021-05-03 16:00 UTC, danielamorse commented
Should use the `-solid` naming convention since both icons are solid.

2021-05-03 16:00 UTC, danielamorse requested changes
Should use the `-solid` naming convention since both icons are solid.

2021-05-03 17:44 UTC, danielamorse approved these changes

2021-05-03 18:23 UTC, merged