Update the z-index for tooltip and popover
boltdesignsystem/bolt pull request #2211
Opened 2021-05-18 10:22 UTC by adamszalapski

## Jira

https://pegadigitalit.atlassian.net/browse/DS-479

## Summary

Update default `z-index` to match earlier default for tooltip and popover.

## Details

`zIndex` prop was added to tippy call.

## How to test

Open popover and tooltip demo and confirm that element created by tippy on the bottom of the page use:
- `z-index: 120` for popovers
- `z-index: 140` for tooltips

2021-05-18 12:41 UTC, danielamorse reviewed
@adamszalapski, thanks for raising this issue and making the PR.

As I mentioned on Slack, I have a few concerns. If we set z-index to 120/140 we'll have to account for the total height of sticky content. Otherwise, it will display "top" when there's not actually room for it to be visible (covered by sticky elements).

This can be handled via [popperOptions](https://atomiks.github.io/tippyjs/v6/all-props/#popperoptions) and the [detectOverflow/padding](https://popper.js.org/docs/v2/utils/detect-overflow//#padding). Additionally, we'll need a system for knowing what sticky elements are actually "pinned".

We might want to coordinate this with the release of Navbar and Page Header. Let's talk more in grooming/dev huddle.

2021-05-24 15:05 UTC, mikemai2awesome requested changes
what @danielamorse said and also this isn't using our z-index system. we do not want to manually write random z-index values, we need to find a way to use the system.

2021-06-01 20:13 UTC, mikemai2awesome requested changes

2021-06-01 20:13 UTC, mikemai2awesome commented on packages/components/bolt-popover/src/popover.js
> +      getComputedStyle(this).getPropertyValue('--c-bolt-popover-zindex'),
Let's use `--c-bolt-popover-z-index` instead to be consistent with how z-index is spelled.

2021-06-01 20:13 UTC, mikemai2awesome commented on packages/components/bolt-popover/src/popover.scss
> +  --c-bolt-popover-zindex: #{bolt-z-index('popover')};
Same comment on the naming.

2021-06-01 20:13 UTC, mikemai2awesome commented on packages/components/bolt-tooltip/src/tooltip.scss
> +  --c-bolt-tooltip-zindex: #{bolt-z-index('tooltip')};
Same comment on the naming.

2021-06-15 20:28 UTC, mikemai2awesome approved these changes
Approved with a question for @danielamorse, see inline comments.

2021-06-15 20:28 UTC, mikemai2awesome commented on packages/components/bolt-popover/src/popover.js
> +      document.querySelector('header.is-fixed') !== null ||
Question for @danielamorse, are you using `is-*` classes? I thought you said you stopped using them.

2021-06-15 20:28 UTC, mikemai2awesome commented on packages/components/bolt-tooltip/src/tooltip.js
> +      document.querySelector('header.is-fixed') !== null ||
Same comment about `is-*` classes.

2021-06-17 03:15 UTC, danielamorse commented on packages/components/bolt-tooltip/src/tooltip.js
> +      document.querySelector('header.is-fixed') !== null ||
@mikemai2awesome `header.is-fixed` is for the old page header. It's the only way we can target it.

We need a universal "sticky" selector, and we need the ability to differentiate between the sticky page header and other sticky elements. How about:
- `.js-bolt-sticky.c-bolt-page-header` // sticky header
- `.js-bolt-sticky:not('c-bolt-page-header')` // everything else

Alternatively, we do:
- `.js-bolt-sticky-page-header` // sticky header
- `.js-bolt-sticky` // everything else

I think I prefer the latter.

On the navbar branch I'm using `[data-bolt-sticky-header]`, but I think a `js-*` class more consistent with our conventions because we're using is as a JS selector. Plus, I see "sticky" as a property not a state, and `data-*` is for state, like `[data-bolt-ready]`.

2021-06-21 14:52 UTC, danielamorse commented
@cjwhitedev, todo:
- In CSS use the modal z-index value instead, comment that this needs to be refactored
- See Popover JS and apply my changes to Tooltip

2021-06-30 21:49 UTC, danielamorse approved these changes
Looks good, ship it!

2021-06-30 21:49 UTC, danielamorse commented on packages/components/bolt-tooltip/src/tooltip.js
> +  getPaddingTop() {
@cjwhitedev in retrospect this is be a good function to move to core and let both components share. Not necessary now, but next time we have to touch this code I'd say it's a good idea.

2021-06-30 21:50 UTC, merged