DS-457: Table Width Bug Fix
boltdesignsystem/bolt pull request #2230
Opened 2021-06-14 18:45 UTC by cjwhitedev

## Jira

[https://pegadigitalit.atlassian.net/browse/DS-457](https://pegadigitalit.atlassian.net/browse/DS-457)

## Summary

Address bug for tables that aren't as wide as their container.

## Details

Change default styles of table to not include a background (because there was an improperly styled flash when undoing the inverse). Compare table body width to table width and apply background and styles if the former is equal to or wider than the latter.

## How to test

Pull the branch and check out the temporary demo page I made as well as the real demo pages.

2021-06-15 13:47 UTC, mikemai2awesome requested changes

2021-06-15 13:47 UTC, mikemai2awesome commented on packages/components/bolt-table/src/table.scss
> +  &--background {
This modifier should be named `--responsive` since that's what it's doing.

2021-06-15 13:47 UTC, mikemai2awesome commented on packages/components/bolt-table/src/table.scss
> +  @include bolt-table-border(bottom);
This is what i meant by moving around the border, going from table to table body and cells. This breaks existing tables, especially the web components (and this is the majority use case). See page: https://boltdesignsystem-2kddt3vvb-boltdesignsystem.vercel.app/pattern-lab/?p=components-table-with-web-component

2021-06-28 21:57 UTC, danielamorse commented
Let's address this when we rebuild the Table component: https://pegadigitalit.atlassian.net/browse/DS-457?focusedCommentId=32787

2021-06-28 21:57 UTC, closed without merging