DS:526 replace button in carousel and update snap.
boltdesignsystem/bolt pull request #2245
Opened 2021-06-25 13:52 UTC by cjwhitedev

## Jira

[https://pegadigitalit.atlassian.net/browse/DS-526](https://pegadigitalit.atlassian.net/browse/DS-526)

## Summary

Replace component button with element button in carousel component.

## Details

we're deprecating and removingt the button component. this replaces instance of the button component in carousel with the button element.

## How to test

look at the demos in pattern lab as well as the code and the updated jest snap.

2021-06-25 15:58 UTC, mikemai2awesome requested changes
As discussed in Slack, remove the button inside another button. Use a span with the button classes can be a quick fix:

```
<div class="c-bolt-carousel__button c-bolt-carousel__button--next c-bolt-carousel__button--inside" tabindex="0" role="button" aria-label="Next slide">
  <span class="e-bolt-button e-bolt-button--border-radius-full e-bolt-button--secondary e-bolt-button--icon-only" slot="next-btn">...</span>
</div>
```

2021-06-28 15:06 UTC, mikemai2awesome requested changes

2021-06-28 15:06 UTC, mikemai2awesome commented on packages/components/bolt-carousel/__tests__/carousel.js
> +<button class="e-bolt-button e-bolt-button--border-radius-full e-bolt-button--secondary e-bolt-button--icon-only"  aria-label="Previous" slot="previous-btn">
Should this be the same as the others and use `span`? If so, remove `aria-label`. Add `aria-hidden="true"` instead since the label is already rendered on the `role="button"` element.

2021-06-28 20:34 UTC, mikemai2awesome requested changes

2021-06-28 20:34 UTC, mikemai2awesome commented on packages/components/bolt-carousel/src/carousel.js
> +        type="button"
Missed one here, remove `type`.

2021-06-28 20:35 UTC, mikemai2awesome commented on packages/components/bolt-carousel/src/carousel.js
> +        aria-label="${text}"
Still need to remove `type`.

2021-06-29 16:08 UTC, mikemai2awesome approved these changes

2021-06-30 21:40 UTC, danielamorse requested changes
Looks great, two requests:
- See comment about removing icon text
- Add Release Notes to this PR describing visual changes to button for QA

2021-06-30 21:40 UTC, danielamorse commented on packages/components/bolt-carousel/src/carousel.js
> -        ${text}
Are we intentionally removing the text here? Isn't "Next/Previous" good for accessibility?

2021-07-01 16:53 UTC, mikemai2awesome commented on packages/components/bolt-carousel/src/carousel.js
> -        ${text}
We are only using this span for styles, and we have `aria-hidden="true"` on the span. The label is on the element with `role="button" already.

2021-07-02 13:57 UTC, danielamorse approved these changes
Nice, thanks for explaining and for updating the PR description.

I updated the heading structure around "Visual changes" in the PR description. I think it needs to be like this for the auto-release script to compile the release notes:
```
## Release notes
### Visual changes
...
```
Here's a good example: https://github.com/boltdesignsystem/bolt/pull/2207

:shipit:

2021-07-02 13:57 UTC, merged