Feature/ds 505
boltdesignsystem/bolt pull request #2246
Opened 2021-06-25 14:30 UTC by MarcinMr

## Jira

https://pegadigitalit.atlassian.net/browse/DS-505

## Summary

Simple sample of component made from scratch, based on banner component. 

## Details

Get familiar with a normal workflow when working within the design system. Here is attached a doc with few questions:
https://pegadigitalit.atlassian.net/browse/DS-507

## How to test

Take a look on a bolt-onboard component. Provide some code review and tips for further work. Please consider that there is also another branch named: **feature/DS-505-Bolt-Onboarding.** **<-- Please ignore that branch.**

2021-06-28 16:56 UTC, mikemai2awesome requested changes

2021-06-28 16:56 UTC, mikemai2awesome commented on packages/components/bolt-onboard/src/onboard.scss
> +    border-radius: 100em;
Make sure to use the sass function `bolt-border-radius` whenever defining border-radius.

Pro tip, in Slack, DM yourself and type `docbot: help`. It will give you a list of commands. Then type `docbot: bolt how to css` and you will see a lot of the commonly used CSS systems.

2021-06-28 16:56 UTC, mikemai2awesome commented on packages/components/bolt-onboard/src/onboard.scss
> +    border-radius: 0.6rem;
Same comment about border-radius sass function.

2021-06-28 16:56 UTC, mikemai2awesome commented on packages/components/bolt-onboard/src/onboard.twig
> +	{{ validate_data_schema(schema, _self) | raw }}
Tab size in this twig file is not following conventions.

2021-06-28 16:56 UTC, mikemai2awesome commented on packages/components/bolt-onboard/src/onboard.scss
> +    border: 0.1rem solid var(--bolt-color-blue);
Whenever possible, try to use spacing tokens instead of writing raw values: https://boltdesignsystem.com/pattern-lab/?p=visual-styles-spacing-tokens

Only exception would be `1px`.

2021-06-28 16:56 UTC, mikemai2awesome commented on packages/components/bolt-onboard/src/onboard.scss
> +@include bolt-custom-element('bolt-onboard', block, medium) {
Try not to nest any styles under this include. Leave it as one line. Separate out these styles.

2021-06-28 16:56 UTC, mikemai2awesome commented on docs-site/src/pages/pattern-lab/_patterns/40-components/onboard/00-onboard-docs.twig
> +  content: "This is an onboard component"
The quotes are not following conventions. Refer to Digital Team Standards and Conventions on Gitlab to ensure when double and single quotes are used.

2021-06-28 16:56 UTC, mikemai2awesome commented on docs-site/src/pages/pattern-lab/_patterns/40-components/onboard/05-onboard.twig
> +{% include "@bolt-components-onboard/onboard.twig" with {
The quotes are not following conventions. Refer to Digital Team Standards and Conventions on Gitlab to ensure when double and single quotes are used.

2021-06-28 16:56 UTC, mikemai2awesome commented on docs-site/src/pages/pattern-lab/_patterns/40-components/onboard/10-onboard-status-variations.twig
> +		{% include "@bolt-components-icon/icon.twig" with {
The quotes are not following conventions. Refer to Digital Team Standards and Conventions on Gitlab to ensure when double and single quotes are used.

2021-06-28 16:56 UTC, mikemai2awesome commented on docs-site/src/pages/pattern-lab/_patterns/40-components/onboard/15-onboard-border-radius-variations.twig
> +{% set schema = bolt.data.components["@bolt-components-onboard"].schema %}
The quotes are not following conventions. Refer to Digital Team Standards and Conventions on Gitlab to ensure when double and single quotes are used.

2021-06-28 16:56 UTC, mikemai2awesome commented on docs-site/src/pages/pattern-lab/_patterns/40-components/onboard/20-onboard-vertical-size-variations.twig
> +{% set schema =  bolt.data.components["@bolt-components-onboard"].schema %}
The quotes are not following conventions. Refer to Digital Team Standards and Conventions on Gitlab to ensure when double and single quotes are used.

2021-06-28 16:56 UTC, mikemai2awesome commented on packages/components/bolt-onboard/src/onboard.twig
> +{% set schema = bolt.data.components["@bolt-components-onboard"].schema %}
The quotes are not following conventions. Refer to Digital Team Standards and Conventions on Gitlab to ensure when double and single quotes are used.

2021-06-28 16:57 UTC, mikemai2awesome commented
@MarcinMr Nice job! You will need to read over the standards and conventions to get some of the formatting correct.

2021-06-28 19:55 UTC, danielamorse reviewed
@MarcinMr Looking good! I left a couple inline comments. You asked some excellent questions. Here's a brief explanation and we can talk more tomorrow at 11:30 (if you can make it).

1. **Styles not showing up in dev tools**
I think you found a bug, you get a prize! When I change the border color to `red`, the styles appear in dev tools. So, it seems to be a bug with CSS variables (`var(--my-variable)`), [CSS nano](https://github.com/cssnano/cssnano/issues/675), [constructable stylesheets](https://developers.google.com/web/updates/2019/02/constructable-stylesheets), or all of the above. I'd like to understand exactly why this breaks but it's a rabbit hole I can't go down right now, and both constructable stylesheets and CSS nano are potentially both getting removed in the future. If you use the long-hand css rule there (`border-left-width: 1rem;`) it seems to fix it. Let's go with that for now.

2. **Twig classes vs JS classes**
Twig renders the initial HTML and then JS replaces that HTML. If you turn JS off, you will see the Twig HTML. Basically, we have to duplicate the logic in Twig and JS to prevent a flash of unstyled content. It's good to know this pattern is used in our system, but we will avoid it in the future because it's too expensive to maintain.

3. **Web component props**
This is one of the neat features of [Lit Element](https://lit-element.polymer-project.org/guide/start). There is two-way binding built into Lit Element (the base class used by our web components). So when a "prop" changes the component re-renders. We should do an overview of Lit Element.

4. **Dump not working**
I think `dump()` is disabled by default in our repo for performance reasons, but it can be turned on. @remydenton please correct me if I'm wrong.

5. **replace-with-children, ssr-keep**
These are helper elements that, when a component boots up, remove parts of the Twig-rendered HTML we don't want to keep and preserve the parts we do. `replace-with-children` self-destructs and leaves only its children. `ssr-keep` destroys all ancestors until it reaches the tag specified in its `for` attribute and then self-destructs, leaving only its children. This is our custom solution to hydrating server-side rendered HTML with JS-rendered components. Again, good to know what it does, but we are using it less and less.

2021-06-28 19:55 UTC, danielamorse commented on .prettierrc
> +  "tabSize": 2,
This shouldn't be necessary. This prettier defaults to `tabWidth: 2` ([docs](https://prettier.io/docs/en/options.html#tab-width)).

If your code is formatting to 4 spaces it's probably your editor settings. Let's take a look tomorrow.

2021-06-28 19:55 UTC, danielamorse commented on packages/components/bolt-onboard/src/onboard.scss
> +    border-left: 1rem solid var(--bolt-color-warning);
If you're only changing the "width" you can use `border-left-width: 1rem`. Then you don't have to repeat the border color and style values.

2021-06-29 09:05 UTC, MarcinMr commented on .prettierrc
> +  "tabSize": 2,
@danielamorse yes, that's true I've changed VS Code formatting to 2 spaces.

2021-06-29 09:35 UTC, MarcinMr commented on packages/components/bolt-onboard/src/onboard.scss
> +    border-radius: 100em;
@mikemai2awesome thanks, I've changed it.

2021-06-29 09:35 UTC, MarcinMr commented on packages/components/bolt-onboard/src/onboard.scss
> +    border-radius: 0.6rem;
@mikemai2awesome as above.

2021-06-29 09:41 UTC, MarcinMr commented on packages/components/bolt-onboard/src/onboard.scss
> +    border: 0.1rem solid var(--bolt-color-blue);
Ok

2021-06-29 09:43 UTC, MarcinMr commented on packages/components/bolt-onboard/src/onboard.scss
> +    border-left: 1rem solid var(--bolt-color-warning);
That makes sense ;) @danielamorse

2021-06-29 09:52 UTC, MarcinMr commented on packages/components/bolt-onboard/src/onboard.scss
> +@include bolt-custom-element('bolt-onboard', block, medium) {
Ok, so in this case how should be done ? Just use `<bolt-onboard>` somwhere below `@include` tag and nest the icon styles inside it, like in the example below ?
@mikemai2awesome 

```
bolt-onboard {
  .c-bolt-icon {
    margin: var(--bolt-spacing-y-xsmall) var(--bolt-spacing-x-xsmall) 0 0;
  }

  .c-bolt-icon--warning {
    color: var(--bolt-color-warning);
  }

  .c-bolt-icon--product {
    color: var(--bolt-color-blue);
  }

  .c-bolt-icon--check-solid {
    color: var(--bolt-color-success);
  }
}

2021-06-29 10:09 UTC, MarcinMr commented on packages/components/bolt-onboard/src/onboard.twig
> +	{{ validate_data_schema(schema, _self) | raw }}
@mikemai2awesome it was something wrong with my VS Code formatting settings. I changed the settings and it should works fine in the future

2021-06-29 10:11 UTC, MarcinMr commented on docs-site/src/pages/pattern-lab/_patterns/40-components/onboard/00-onboard-docs.twig
> +  content: "This is an onboard component"
@mikemai2awesome Ok, if I understand this correctly, according to the gitlab rules, every quotes in .twig files should be single ('...') ?

2021-06-29 10:22 UTC, MarcinMr commented
@danielamorse @mikemai2awesome I made the change requests and add some comments above, I hope I didn't miss anything.

2021-07-07 21:42 UTC, mikemai2awesome commented on packages/components/bolt-onboard/src/onboard.scss
> +@include bolt-custom-element('bolt-onboard', block, medium) {
yes correct, separate them.

2021-07-07 21:47 UTC, mikemai2awesome commented on docs-site/src/pages/pattern-lab/_patterns/40-components/onboard/00-onboard-docs.twig
> +  content: "This is an onboard component"
no, not every quote in a twig file must be single, you have to write accordingly. you can write a lot of different things in a twig file. if you are writing twig, use single. if you are writing HTML, use double. if you are writing JS, use single.

2021-07-09 08:46 UTC, MarcinMr commented
@mikemai2awesome change request made

2021-07-09 15:43 UTC, mikemai2awesome approved these changes

2021-07-09 15:44 UTC, mikemai2awesome commented
Closing as this exercise is done.

2021-07-09 15:44 UTC, closed without merging