WWW-793: Closed captioning default display issues
boltdesignsystem/bolt pull request #2248
Opened 2021-06-29 22:08 UTC by colbytcook

## Jira

https://pegadigitalit.atlassian.net/browse/WWW-793

## Summary

Updated the Brightcove video examples in Patternlab

## Details

* Added a video with localized translation to Patternlab to test closed captioning
* Updated the first play event to a more stable version

2021-06-30 20:04 UTC, remydenton approved these changes
From the Brightcove docs 😂 :

> Not part of the HLS spec, and we're not sure if this is the best implementation yet, so use sparingly.

Good find!

2021-06-30 20:04 UTC, remydenton commented on packages/website-ui/styleguidekit-twig-default/views/partials/general-footer.twig
>        // NOTE: Safari does not immediately load the closed captioning menu on load, need to first wait until 'firstplay' event + 1/2 second wait time to avoid race conditions
Nitpick, the comment still mentions a 'firstplay' event.

2021-07-01 13:17 UTC, cjwhitedev requested changes
@colbytcook this wasn't working in safari for me. We should test in a few more environments and if it's only me I'll approve.

2021-07-06 12:23 UTC, colbytcook commented on packages/website-ui/styleguidekit-twig-default/views/partials/general-footer.twig
>        // NOTE: Safari does not immediately load the closed captioning menu on load, need to first wait until 'firstplay' event + 1/2 second wait time to avoid race conditions
Nice catch, I will update

2021-07-12 14:16 UTC, colbytcook commented on packages/website-ui/styleguidekit-twig-default/views/partials/general-footer.twig
>        // NOTE: Safari does not immediately load the closed captioning menu on load, need to first wait until 'firstplay' event + 1/2 second wait time to avoid race conditions
@remydenton this is updated

2021-08-12 15:16 UTC, cjwhitedev approved these changes

2021-08-12 17:13 UTC, merged