DS-109: Convert components to use border radius function
boltdesignsystem/bolt pull request #2249
Opened 2021-06-30 11:23 UTC by MarcinMr

## Jira

https://pegadigitalit.atlassian.net/browse/DS-109

## Summary

Update components to use `bolt-border-radius` function.

## Details

I went thru all components from `packages/components` some of them were already updated the other needed changes. 

**Below is a list of converted components**:

- accordion,
- bloquote,
- button,
- card replacement,
- carousel,
- chip,
- code snippet,
- headline,
- icon,
- listing teaser,
- menu,
- modal,
- navbar menu,
- pagination,
- progressbar,
- side-nav,
- teaser,
- tabs,
- typehead,
- video,
- video thumbnail

Following Mike advice I excluded: `device viewer`, `form`, `page header`.

## How to test

Run the branch locally and checked the demo pages for the list of affected components. Make sure the border radius is displaying correctly.

2021-06-30 18:25 UTC, mikemai2awesome requested changes
@MarcinMr Good job, please take a look at a few inline comments.

2021-06-30 18:25 UTC, mikemai2awesome commented on packages/components/bolt-button/src/button.scss
> +    border-radius: bolt-border-radius(full);
I believe this will be a breaking change. Let's revert it, and this component is already deprecated.

2021-06-30 18:25 UTC, mikemai2awesome commented on packages/components/bolt-carousel/src/_carousel.next-previous-buttons.scss
> +      border-radius: bolt-border-radius(small);
Let's revert this one, the `1px` is used intentionally.

2021-06-30 18:25 UTC, mikemai2awesome commented on packages/components/bolt-typeahead/typeahead.scoped.scss
> +$bolt-typeahead-border-radius: bolt-border-radius(large);
Unfortunately, this will be too big a visual change. Let's revert this one as well.

2021-07-01 09:55 UTC, MarcinMr commented on packages/components/bolt-button/src/button.scss
> +    border-radius: bolt-border-radius(full);
Ok, I reverted it

2021-07-01 10:02 UTC, MarcinMr commented on packages/components/bolt-carousel/src/_carousel.next-previous-buttons.scss
> +      border-radius: bolt-border-radius(small);
Ok, I fixed it

2021-07-01 10:04 UTC, MarcinMr commented on packages/components/bolt-typeahead/typeahead.scoped.scss
> +$bolt-typeahead-border-radius: bolt-border-radius(large);
Yeah, I wasn't sure about that; `small` value was too small and 'large` value was too large. I converted it back to 6px.

2021-07-01 16:49 UTC, mikemai2awesome requested changes
@MarcinMr Great! One more and it's all set.

2021-07-01 16:49 UTC, mikemai2awesome commented on packages/components/bolt-carousel/src/_carousel.next-previous-buttons.scss
> +  border-radius: bolt-border-radius(large);
This should be full because it's fully rounded.

2021-07-02 07:27 UTC, MarcinMr commented on packages/components/bolt-carousel/src/_carousel.next-previous-buttons.scss
> +  border-radius: bolt-border-radius(large);
I've changed it

2021-07-06 15:34 UTC, mikemai2awesome approved these changes

2021-07-07 15:12 UTC, merged