DS-535: Replace Button in Typeahead Component
boltdesignsystem/bolt pull request #2250
Opened 2021-06-30 18:54 UTC by cjwhitedev

## Jira

[https://pegadigitalit.atlassian.net/browse/DS-535](https://pegadigitalit.atlassian.net/browse/DS-535)

## Summary

Replace component button with element button in typeahead component.

## Details

we're deprecating and removing the button component. this replaces instance of the button component in typeahead with the button element.

## How to test

look at the demos in pattern lab as well as the code and the updated jest snap.

2021-06-30 22:08 UTC, danielamorse requested changes
Nice work on the JS. Looks like a pretty clean replacement.

Take a look at focus styles though. When you focus on the submit or close buttons they pop out of place.

https://user-images.githubusercontent.com/36336/124037832-2d36f980-d9ce-11eb-82bd-09f671dbbd35.mov

2021-06-30 22:08 UTC, danielamorse commented on packages/components/bolt-typeahead/typeahead.js
> -        ${this.clearInputText}
@mikemai2awesome I see we're replacing text with aria-labels. Is this the way forward for icon-only buttons?

2021-07-01 14:30 UTC, mikemai2awesome requested changes
Same comment as @danielamorse

2021-07-01 16:51 UTC, mikemai2awesome commented on packages/components/bolt-typeahead/typeahead.js
> -        ${this.clearInputText}
yes, it's redundant to have both. either use aria-label or use text. in icon only buttons, use aria-label.

2021-07-02 14:03 UTC, cjwhitedev commented
@danielamorse i had seen this before and thought i fixed it. i don't see it on my local in firefox, safari, or chrome. what browser are you using?

2021-07-06 15:56 UTC, mikemai2awesome requested changes
@cjwhitedev couple more fixes then it's all set.

2021-07-06 15:56 UTC, mikemai2awesome commented on packages/components/bolt-typeahead/typeahead.js
> +          <bolt-icon
oh, since we are writing web component markup here, you'll need to manually add `aria-hidden="true"`. that was handled in twig but doesn't happen automatically in web component.

2021-07-06 15:56 UTC, mikemai2awesome commented on packages/components/bolt-typeahead/typeahead.js
> +          <bolt-icon
Same here, `aria-hidden` needed. And please remove `title`. That attribute should never be used. We already have `aria-label` on the `<button>`.

2021-07-06 18:13 UTC, mikemai2awesome commented on packages/components/bolt-typeahead/typeahead.js
> +          <bolt-icon
@cjwhitedev Remove the `title` please.

2021-07-06 18:57 UTC, mikemai2awesome approved these changes

2021-07-07 12:05 UTC, merged