DS-537: Standarize schema and twig for bolt-banner
boltdesignsystem/bolt pull request #2255
Opened 2021-07-02 08:49 UTC by MarcinMr

## Jira

https://pegadigitalit.atlassian.net/browse/DS-537
https://pegadigitalit.atlassian.net/browse/DS-538

## Summary

These two tickets were done at the same time due they are related to each other. Files: `banner.schema.js`, `banner.twig` inside `packages/components/bolt-banner/src/` and `banner.js` inside `__tests__` were reviewed.

## Details

Component was checked with master tickets.

## How to test

Check if it is up to date with standards mentioned in master tickets:

Refer to the Standardize Schema ticket: https://pegadigitalit.atlassian.net/browse/DS-369
Refer to the Standardize Twig ticket: https://pegadigitalit.atlassian.net/browse/DS-370
Refer to the Standarize Test ticket: https://pegadigitalit.atlassian.net/browse/DS-413

2021-07-07 12:10 UTC, colbytcook commented on packages/components/bolt-banner/__tests__/banner.js
> +        content: `This banner is trying to convey ${option}`,
@MarcinMr you can remove this **content** data since it is already being passed in with the fixtures.defaultData object.

2021-07-07 12:10 UTC, colbytcook commented on packages/components/bolt-banner/__tests__/banner.js
> +        content: `The text is aligned to the ${option}`,
@MarcinMr you can remove this **content** data since it is already being passed in with the fixtures.defaultData object.

2021-07-07 15:29 UTC, MarcinMr commented on packages/components/bolt-banner/__tests__/banner.js
> +        content: `This banner is trying to convey ${option}`,
@colbytcook I thought it should be overwritten because `fixtures.defaultData` says: "this is a banner".  So this is ok for a default banner but what for options with `alignment` and `status` ? If I don't overwrite it, every banner's test snap will say "this is a banner". Shouldn't the test snaps say like 'the text is aligned to the `left`, `center` or `right` ? And 'this banner is trying to convey `information`, `warning` or `success` ? Am I wrong ? Or maybe that doesn't matter and it is ok that every snap test for banner has default "this is a banner".

This is what I mean when the `defaultData` is overwritten by `content`

<img width="672" alt="default" src="https://user-images.githubusercontent.com/85670248/124786822-531d4a80-df48-11eb-8998-3acd64c285ee.png">
<img width="638" alt="success" src="https://user-images.githubusercontent.com/85670248/124786826-544e7780-df48-11eb-99a5-95c069cea92d.png">

2021-07-07 15:29 UTC, MarcinMr commented on packages/components/bolt-banner/__tests__/banner.js
> +        content: `The text is aligned to the ${option}`,
The same as above @colbytcook

2021-07-07 15:58 UTC, mikemai2awesome requested changes

2021-07-07 15:58 UTC, mikemai2awesome commented on packages/components/bolt-banner/__tests__/banner.js
> +describe('Bolt banner Props', () => {
Let's fix the grammar here, use `Bolt banner prop - `.

2021-07-07 15:58 UTC, mikemai2awesome commented on packages/components/bolt-banner/__tests__/banner.js
> +    test(`status items: ${option}`, async () => {
Instead of `status items:`, write `status:`.

2021-07-07 15:58 UTC, mikemai2awesome commented on packages/components/bolt-banner/__tests__/banner.js
> +    test(`status items: ${option}`, async () => {
Make sure the change the text based on each prop. This should be `align:`.

2021-07-07 18:07 UTC, cjwhitedev reviewed
@MarcinMr We have been doing the conversions first, and then the tests in a separate PR. This way, Travis will alert us if something is wrong with the conversion before we change the tests.

2021-07-09 15:43 UTC, MarcinMr commented
@mikemai2awesome @cjwhitedev I made new PR for test schema

https://github.com/boltdesignsystem/bolt/pull/2262

2021-07-13 20:05 UTC, mikemai2awesome approved these changes

2021-07-14 13:02 UTC, cjwhitedev requested changes

2021-07-14 13:15 UTC, MarcinMr commented on packages/components/bolt-banner/__tests__/banner.js
> +        content: `This banner is trying to convey ${option}`,
<img width="693" alt="Screenshot 2021-07-14 at 15 07 26" src="https://user-images.githubusercontent.com/85670248/125628089-ef8c90b5-2f0b-4200-8e73-555fcb4bf4fd.png">

Ok, so maybe if we have information at the top of the snap (green frame) I can just remove the content and leave only `fixtures` with default data.

2021-07-15 09:46 UTC, MarcinMr commented on packages/components/bolt-banner/src/banner.twig
> +  {% if outer_classes %} class='{{ outer_classes|join(' ') }}' {% endif %}
@cjwhitedev I've changed that

2021-07-15 09:53 UTC, MarcinMr commented on packages/components/bolt-banner/__tests__/banner.js
> +        content: `This banner is trying to convey ${option}`,
@cjwhitedev this is no i this ticket anymore. I've brought back old schema here, when you wrote: "We have been doing the conversions first, and then the tests in a separate PR. This way, Travis will alert us if something is wrong with the conversion before we change the tests."

It's been in a separate ticket with no `content data` now. But I left it alone as you suggested yesterday on Slack.

2021-07-15 14:55 UTC, cjwhitedev approved these changes
@MarcinMr i just did a quick commit to make the ssr-keep for use double quotes since its HTML, not TWIG. (I also updated our master ticket so this is outlined in the future). This looks good to me, approved!

2021-07-15 17:44 UTC, merged