DS-534: Replace Button in Card Component
boltdesignsystem/bolt pull request #2256
Opened 2021-07-02 13:47 UTC by cjwhitedev

## Jira

(Enter a link to the Jira issue this PR applies to, if any)

## Summary

(Enter a one-line summary of the changes in this PR. This will be included in the release notes)

## Details

Replace component button with element button in card component.

## How to test

We're deprecating and removingt the button component. this replaces instance of the button component in card with the button element.

### Visual changes

The button element is slightly larger than the button component for accessibility purposes, this is expected.

2021-07-02 16:01 UTC, mikemai2awesome requested changes
I feel like we should do things the right way once and for all:
```
<bolt-card-replacement-action role="link" href="https://yahoo.com" target="_blank">
  ...
</bolt-card-replacement-action>
<bolt-card-replacement-action role="button" type="submit">
  ...
</bolt-card-replacement-action>
```
There are so many existing problems with the button/link inside the shadow dom, this will get it back to proper HTML.

Additionally, there is a lot that goes into removing white space in links and buttons, which you need to do the same here. Otherwise you will end up with underline like this:

![Screen Shot 2021-07-02 at 11 41 18 AM](https://user-images.githubusercontent.com/3027663/124300976-296db900-db2d-11eb-94a9-561a549e9cde.png)

2021-07-09 18:10 UTC, cjwhitedev commented on packages/components/bolt-card-replacement/src/card-replacement-actions/_card-replacement-action.twig
>            target: this.data.external.value == true ? '_blank' : '_self',
future @cjwhitedev this is incorrect

2021-07-13 16:40 UTC, danielamorse requested changes
@cjwhitedev nice work, almost there. This one was super tricky!

I made some inline comments. Take a look and lmk if you have any questions.

Thanks for adding the note for visual changes note for QA. Reminder that it has to be under the `## Release Notes` heading for it to be automatically compiled when we release. I added it 👍 

Also, if we no longer have a dependency on Bolt Button it can be removed from [Card's package.json file](https://github.com/boltdesignsystem/bolt/blob/feature/DS-534-card-button-replacement/packages/components/bolt-card-replacement/package.json#L22).

2021-07-13 16:40 UTC, danielamorse commented on packages/components/bolt-card-replacement/src/card-replacement-actions/card-replacement-action.js
> +                href="${ifDefined(this.url ? this.url : undefined)}"
@mikemai2awesome if `this.url` is undefined should this be a semantic `button[type="button"]`?

2021-07-13 16:40 UTC, danielamorse commented on packages/components/bolt-card-replacement/src/card-replacement-actions/card-replacement-action.js
> +                  ? // prettier-ignore
What whitespace problem does this solve? When I remove it I don't notice a difference on the front-end. Can you show me an example?

2021-07-13 16:40 UTC, danielamorse commented on packages/components/bolt-card-replacement/src/card-replacement-actions/_card-replacement-action.twig
> +          content: this.data.text.value,
@cjwhitedev what do you think of this refactor? This way you build up the button attributes and only add it once to the button props.
```
        {% set _button_attributes = attributes|default({}) %}
        {% set _button_attributes = _button_attributes|merge({ target: this.data.external.value == true ? '_blank' : '_self' }) %}

        {% if this.data.url.value %}
          {% set _button_attributes = _button_attributes|merge({ href: this.data.url.value }) %}
        {% else %}
          {% set _button_attributes = _button_attributes|merge({ type: 'button' }) %}
        {% endif %}

        {% set _button_props = {
          content: this.data.text.value,
          hierarchy: 'transparent',
          display: 'block',
          attributes: _button_attributes
        } %}

        {% if spacing is not empty %}
          {% set _button_props = _button_props|merge({ size: spacing }) %}
        {% endif %}

        {% if this.data.icon.value != 'none' %}
        ...
```

2021-07-13 16:48 UTC, mikemai2awesome commented on packages/components/bolt-card-replacement/src/card-replacement-actions/card-replacement-action.js
> +                href="${ifDefined(this.url ? this.url : undefined)}"
yes. but that locks it down to just `type="button"` without a way to do `reset` and `submit`.

2021-07-13 16:51 UTC, mikemai2awesome commented
@cjwhitedev @danielamorse There's still this white space issue on hover, see the underline is longer than it should be. It's not that jarring so if it's hard to fix then we can leave it.
<img width="318" alt="Screen Shot 2021-07-13 at 12 50 02 PM" src="https://user-images.githubusercontent.com/3027663/125493298-5cb78172-8602-475e-8704-301a80825105.png">

2021-07-13 16:57 UTC, danielamorse commented
> @cjwhitedev @danielamorse There's still this white space issue on hover

Oh yeah, meant to mention this - it's the whitespace in the light dom. So if you remove whitespace around the text it fixes it. Like so:
```
<bolt-card-replacement-action>Button text</bolt-card-replacement-action>
```

This is different than other whitespace issues we've fixed with JS in the past. I recommend letting the user fix it by simply not including line breaks.

2021-07-13 17:44 UTC, cjwhitedev commented on packages/components/bolt-card-replacement/src/card-replacement-actions/_card-replacement-action.scss
> +// @TODO: can we unify these? why are the styles different?
Yes - I guess I was initially confused why they were two different styles. It seems like one of them only applies to the WC but the other applies to both the twig and the WC. Why style them differently? But now I'm wondering if I just misunderstood the nesting.

2021-07-13 17:45 UTC, cjwhitedev commented on packages/components/bolt-card-replacement/src/card-replacement-actions/card-replacement-action.js
> +                href="${ifDefined(this.url ? this.url : undefined)}"
@mikemai2awesome @danielamorse so do we just leave this alone or is there work to be done?

2021-07-13 17:46 UTC, cjwhitedev commented on packages/components/bolt-card-replacement/src/card-replacement-actions/card-replacement-action.js
> +                  ? // prettier-ignore
This resolves the underline @mikemai2awesome called out in the web component uses.

2021-07-13 17:48 UTC, cjwhitedev commented on packages/components/bolt-card-replacement/src/card-replacement-actions/_card-replacement-action.twig
> +          content: this.data.text.value,
I think its a bit long winded, but neither @colbytcook or I could figure out another way to merge attributes without overwriting them. If you have a shorter way then I'd love to use it, but as far as I'm concerned, this works, and it's fine.

2021-07-13 18:14 UTC, danielamorse commented on packages/components/bolt-card-replacement/src/card-replacement-actions/_card-replacement-action.scss
> +// @TODO: can we unify these? why are the styles different?
`bolt-card-replacement-action` is the WC element. `.c-bolt-card_replacement__action` is the inner div in the shadow dom. `.e-bolt-button` is repeated in both because it can appear either in the shadow or the light dom. Does that clear things up @cjwhitedev?

2021-07-13 20:17 UTC, danielamorse commented on packages/components/bolt-card-replacement/src/card-replacement-actions/card-replacement-action.js
> +                href="${ifDefined(this.url ? this.url : undefined)}"
I vote to leave this alone. It only affects the web component. If you use Twig you get the proper semantic element.

2021-07-13 20:25 UTC, danielamorse approved these changes
Approved 🎉 

@cjwhitedev @mikemai2awesome,
- Added a demo of card opening a modal (`/pattern-lab/?p=tests-card-links-and-buttons`)
- Fixed the focus style
- Fixed the Twig logic so that semantic buttons don't get `target` attribute

What's up with the Listing Teaser snapshot in this PR? Is that something that's on `master` we can pull in rather than commit here?

2021-07-14 15:42 UTC, mikemai2awesome approved these changes

2021-07-14 15:45 UTC, merged