DS-539-Fix-alignmen-on-Toolbar-component
boltdesignsystem/bolt pull request #2259
Opened 2021-07-07 09:05 UTC by MarcinMr

## Jira

https://pegadigitalit.atlassian.net/browse/DS-539

## Summary

The Toolbar component ws updated, so that when there is a long breadcrumb the items on the right (download, share) do not wrap and align at the top of the container.

## Details

Above “medium” breakpoint Toolbar items do not wrap and are aligned to the top of the toolbar.

https://user-images.githubusercontent.com/85670248/124731768-d3c15400-df12-11eb-8ef6-b757978b73b8.mov

## How to test

Check if items on the right (download, share) behave properly above and below `medium` breakpoint.

2021-07-07 15:44 UTC, mikemai2awesome requested changes
This does not work, it is wrapping too early. Set it to wrap at `small` breakpoint.

Secondly, the ones with shorter titles are broken now. The title is not center aligned vertically:

![Screen Shot 2021-07-07 at 11 15 47 AM](https://user-images.githubusercontent.com/3027663/124789808-9790f200-df18-11eb-9de8-366f208a8d6c.png)

2021-07-08 13:07 UTC, MarcinMr commented
@mikemai2awesome 

I was suggested `medium` break point from the ticket description.

There is a case with rocket icon alignment:

1.`align-items: center`

1.a. Above `small` bp, neutral text length. Looks good

<img width="1358" alt="above-small-center-v-alignment-normal-text" src="https://user-images.githubusercontent.com/85670248/124919348-6dadfd00-dff6-11eb-84e8-b2b45f5be404.png">


1.b. Above `small` bp, longer text length. Looks good

<img width="1215" alt="above-small-centered-v-long-text" src="https://user-images.githubusercontent.com/85670248/124919537-a8179a00-dff6-11eb-8893-0d78d959e40c.png">


1.c Below `small` bp, longer text length. Rocket is vertically centered to the breadcrumb text

<img width="422" alt="below-small-centered-v-long text" src="https://user-images.githubusercontent.com/85670248/124919685-cd0c0d00-dff6-11eb-8922-5c3e1866dae4.png">

2.`align-items: flex-start`

2a. Below `small` bp, long text length. Looks good

<img width="425" alt="below-small-top-v-longer-text" src="https://user-images.githubusercontent.com/85670248/124920446-9c78a300-dff7-11eb-82c6-861fa6f3b2a1.png">


2b. Below `small` bp, short text length. Looks bad and it will also break above `small` bp if text is short like in your screenshot.

<img width="427" alt="below-small-top-v-short-text" src="https://user-images.githubusercontent.com/85670248/124920619-ca5de780-dff7-11eb-81a6-6c3fda88f046.png">


**I think we should stay with `align-items: center`**

2021-07-08 20:15 UTC, mikemai2awesome commented
@MarcinMr Actually, you can get it to behave as expected with css grid. Reference the changes I made to understand the method.

![toolbar](https://user-images.githubusercontent.com/3027663/124984832-b1f5c900-e007-11eb-825c-715f8681cd61.gif)

2021-07-08 20:42 UTC, mikemai2awesome approved these changes

2021-07-09 18:39 UTC, merged