DS-556 Convert $bolt-transition to CSS var
boltdesignsystem/bolt pull request #2273
Opened 2021-07-16 11:43 UTC by MarcinMr

## Jira

https://pegadigitalit.atlassian.net/browse/DS-556

## Summary

Delete all SCSS variables `$bolt-transition` and `bolt-transition-*` and apply relevant CSS var.

## Details

All SCSS transition vars were replace with CSS vars.
Here is reference to the CSS vars: https://github.com/boltdesignsystem/bolt/blob/master/packages/global/styles/00-vars/_vars-transition.scss

## How to test

Make sure there is no any of SCSS var: `$bolt-transition`, `$bolt-transition-*` and are respectively switched.
Compare transitions on this branch with the master branch.

2021-07-26 22:21 UTC, mikemai2awesome requested changes

2021-07-26 22:21 UTC, mikemai2awesome commented on packages/components/bolt-text/src/text.scss
> +    transition: all vr(--bolt-transition);
Fix the typo here.

2021-07-27 09:38 UTC, MarcinMr commented on packages/components/bolt-text/src/text.scss
> +    transition: all vr(--bolt-transition);
@mikemai2awesome typo fixed

2021-08-03 20:55 UTC, mikemai2awesome requested changes
Let's deprecate here as well, rather than remove. There are still many uses in the wild, removing will cause a breaking change: https://gitlab.com/search?group_id=5804310&repository_ref=master&scope=blobs&search=%24bolt-transition*&snippets=false

2021-08-03 20:55 UTC, mikemai2awesome commented on packages/core-v3.x/styles/01-settings/settings-global/_settings-global.scss
> -// Transition
We cannot remove. We are only deprecating.

2021-08-04 11:12 UTC, MarcinMr commented on packages/core-v3.x/styles/01-settings/settings-global/_settings-global.scss
> -// Transition
@mikemai2awesome changes undone

2021-08-04 19:35 UTC, mikemai2awesome approved these changes

2021-08-04 19:36 UTC, merged