DS-558 Deprecate color indigo
boltdesignsystem/bolt pull request #2287
Opened 2021-07-30 10:44 UTC by MarcinMr

## Jira

https://pegadigitalit.atlassian.net/browse/DS-558

## Summary

Any `indigo` usage was converted to `navy`.

## How to test

Make sure there is no more color `indigo` present in the repo.

2021-08-03 20:30 UTC, mikemai2awesome requested changes
@MarcinMr We are deprecating not removing. Please roll back some changes.

2021-08-03 20:30 UTC, mikemai2awesome commented on packages/core-v3.x/styles/01-settings/settings-colors/_settings-colors.scss
>    'navy': (
We want to deprecate first, make sure Pattern Lab itself doesn't use indigo anymore. We cannot remove yet.

2021-08-03 20:30 UTC, mikemai2awesome commented on docs-site/src/pages/pattern-lab/_patterns/30-layouts/layout/-45-layout-item-vertical-alignment.twig
> +              src: '/images/heros/hero-foreground--navy.png',
This is a file name, it should not be changed.

2021-08-03 20:31 UTC, mikemai2awesome commented on docs-site/src/pages/pattern-lab/_patterns/10-visual-styles/00-color/00-color-system.twig
> +          {% include "_color-swatch.twig" with {
Do not remove the condition here. It'll be done when we are removing indigo.

2021-08-03 20:43 UTC, mikemai2awesome requested changes

2021-08-03 20:43 UTC, mikemai2awesome commented on docs-site/src/pages/pattern-lab/_patterns/10-visual-styles/00-color/05-color-tokens.twig
> +        <bolt-text headline font-size="xlarge" tag="h3">
Same here, do not remove the condition.

2021-08-03 20:43 UTC, mikemai2awesome commented on docs-site/src/pages/pattern-lab/_patterns/10-visual-styles/00-color/05-color-tokens.twig
> +        {% if color_name != "navy" %}
Revert this.

2021-08-03 20:43 UTC, mikemai2awesome commented on docs-site/src/pages/pattern-lab/_patterns/10-visual-styles/00-color/15-text-color-utilities.twig
>            <bolt-text headline font-size="xlarge" tag="h3">
Same here, do not remove the condition.

2021-08-03 20:43 UTC, mikemai2awesome commented on docs-site/src/pages/pattern-lab/_patterns/10-visual-styles/00-color/15-text-color-utilities.twig
> +        {% if color_name != "navy" %}
Revert his.

2021-08-03 20:43 UTC, mikemai2awesome commented on docs-site/src/pages/pattern-lab/_patterns/40-components/hero/50-hero--image-valign-top.twig
> +  background: "/images/heros/hero-background--navy.jpg",
These are file names. Do not change.

2021-08-03 20:43 UTC, mikemai2awesome commented on docs-site/src/pages/pattern-lab/_patterns/40-components/icon/15-icon-color-variation.twig
> +    <bolt-list-item>
Same here, do not remove the condition.

2021-08-04 09:57 UTC, MarcinMr commented on packages/core-v3.x/styles/01-settings/settings-colors/_settings-colors.scss
>    'navy': (
Reverted

2021-08-04 09:57 UTC, MarcinMr commented on docs-site/src/pages/pattern-lab/_patterns/30-layouts/layout/-45-layout-item-vertical-alignment.twig
> +              src: '/images/heros/hero-foreground--navy.png',
Reverted

2021-08-04 09:57 UTC, MarcinMr commented on docs-site/src/pages/pattern-lab/_patterns/10-visual-styles/00-color/00-color-system.twig
> +          {% include "_color-swatch.twig" with {
Reverted

2021-08-04 09:57 UTC, MarcinMr commented on docs-site/src/pages/pattern-lab/_patterns/10-visual-styles/00-color/05-color-tokens.twig
> +        <bolt-text headline font-size="xlarge" tag="h3">
Reverted

2021-08-04 09:57 UTC, MarcinMr commented on docs-site/src/pages/pattern-lab/_patterns/10-visual-styles/00-color/05-color-tokens.twig
> +        {% if color_name != "navy" %}
Reverted

2021-08-04 09:57 UTC, MarcinMr commented on docs-site/src/pages/pattern-lab/_patterns/10-visual-styles/00-color/15-text-color-utilities.twig
> +        {% if color_name != "navy" %}
Reverted

2021-08-04 09:57 UTC, MarcinMr commented on docs-site/src/pages/pattern-lab/_patterns/40-components/hero/50-hero--image-valign-top.twig
> +  background: "/images/heros/hero-background--navy.jpg",
Reverted

2021-08-04 09:57 UTC, MarcinMr commented on docs-site/src/pages/pattern-lab/_patterns/40-components/icon/15-icon-color-variation.twig
> +    <bolt-list-item>
Reverted

2021-08-04 09:58 UTC, MarcinMr commented
@mikemai2awesome change requests reverted

2021-08-04 19:29 UTC, mikemai2awesome approved these changes
@danielamorse This has some Academy changes, please review.

2021-08-05 23:54 UTC, danielamorse requested changes
I reviewed the Academy changes and made [a ticket](https://pegadigitalit.atlassian.net/browse/ACD-957) to update colors in Academy codebase.

@MarcinMr @mikemai2awesome be sure to include a "Release notes" section to your PR description when there are deprecations. See [this PR](https://github.com/boltdesignsystem/bolt/pull/2229) for reference 🙏

2021-08-06 09:48 UTC, MarcinMr commented
@danielamorse I added release notes to this PR, let me know if that's ok.

2021-08-06 15:29 UTC, danielamorse approved these changes
Thanks for updating the "Release notes" @MarcinMr. I just removed the "Deprecations" heading.

We don't have an official format for this, but here's how the notes get compiled for [an actual release](https://github.com/boltdesignsystem/bolt/releases/tag/v4.2.0). Maybe in a future dev huddle we can decide on a good format and document it.

2021-08-09 13:45 UTC, merged