DS-409 Update plop component generator
boltdesignsystem/bolt pull request #2292
Opened 2021-08-05 12:16 UTC by MarcinMr

## Jira

https://pegadigitalit.atlassian.net/browse/DS-409

## Summary

Schema, twig and test templates were updated to our standards

## Details

A branch [feature/DS-408-Convert-Yeoman-to-Plop-alternative](https://github.com/boltdesignsystem/bolt/pull/2274) was pulled to this one.

- `title` and `content` were added to `component.schema`
- `component.docs.twig` was updated with single quotes
-  `component.twig` was updated with single quotes, `attributes` was changed with `props.class`, `title` and `content` were added to the template
- `component.test.js` was updated with commented code in case to use, according to the master schema
- `element.docs.twig` was updated with single quotes

## How to test

1. Pull the branch locally
2. Run `yarn cc` to generate component and check if all the files are generated correctly.
3. Run `yarn jest packages/generators/bolt-generator/__tests__/component/bolt-generator.js` and check if all tests passed.
4. Run `yarn ce` to generate element and check if all the files are generated correctly.
5. Run `yarn jest packages/generators/bolt-generator/__tests__/element/bolt-generator.js` and check if all tests passed.

2021-08-09 17:02 UTC, danielamorse approved these changes
Looks good! Thanks @MarcinMr. I just made [one formatting fix](https://github.com/boltdesignsystem/bolt/pull/2292/commits/c67d342b767a2ac96e5069e1c58ad9e92320db91).

2021-08-11 12:12 UTC, colbytcook approved these changes

2021-08-13 12:44 UTC, cjwhitedev requested changes
1. if we're trying to make less and less web components, do we want the default generator to be a web component out of the box? maybe we can add a step in the generator to ask if its a web component, then generate a separate directory.
2. in the twig file it doesnt look to me like we are properly leveraging `this.data` / validation  out of the box.
3. in the test file, are the right things commented out? if we are creating a web component by default, we should be testing a web component by default. if we go with any changes from my first comment above, then the test file should be rendered differently as well, right?

2021-08-13 14:06 UTC, mikemai2awesome commented
yes, we should chat about CJ's points.

2021-08-16 11:01 UTC, adamszalapski requested changes
Why did we change the name of the package? If this was already. discuss we should find all `bolt-generator` occurrences and change it to `generator-bolt` because of other tests and some exceptions based on this name.

2021-09-13 18:05 UTC, colbytcook approved these changes

2021-09-14 21:41 UTC, danielamorse reviewed
This looks good except for the tests. I'm running into some Jest test errors locally that I'll need more time to debug. Tests pass individually, and then when I run `yarn test:js` several generator tests fail.

2021-09-14 21:41 UTC, danielamorse commented on packages/generators/bolt-generator/__tests__/component/__snapshots__/bolt-generator.js.snap
> +// describe('Bolt Test prop -', () => {
@MarcinMr, @colbytcook if this is the new convention for Jest tests, would you please also update the [wiki](https://github.com/boltdesignsystem/bolt/wiki/Jest-Test:-Example-Jest-Test)?

2021-09-14 21:42 UTC, danielamorse commented on packages/generators/bolt-generator/__tests__/component/__snapshots__/bolt-generator.js.snap
>  describe('Bolt Test component', () => {
@MarcinMr @colbytcook same comment here about updating the wiki with the "component/element" convention if that's the new standard.

2021-09-15 07:30 UTC, adamszalapski approved these changes
Looks good. I agree with @danielamorse all-new approaches/conventions should be updated/added to our WIKI.

2021-09-15 12:36 UTC, cjwhitedev approved these changes

2021-09-16 12:01 UTC, danielamorse commented on packages/generators/bolt-generator/__tests__/component/__snapshots__/bolt-generator.js.snap
> +// describe('Bolt Test prop -', () => {
Updated: https://github.com/boltdesignsystem/bolt/wiki/Jest-Test:-Example-Jest-Test

2021-09-16 12:02 UTC, danielamorse commented on packages/generators/bolt-generator/__tests__/component/__snapshots__/bolt-generator.js.snap
>  describe('Bolt Test component', () => {
Updated: https://github.com/boltdesignsystem/bolt/wiki/Jest-Test:-Example-Jest-Test

2021-09-16 12:28 UTC, danielamorse requested changes
I'm seeing Jest test failures when I do the following:
1. Run `yarn test:js` (all tests pass... although I was seeing unrelated intermittent `bolt-text` fails, disregard for now)
2. Run `npx jest packages/generators/bolt-generator/__tests__/component/bolt-generator.js` (pass)
3. Run `npx jest packages/generators/bolt-generator/__tests__/element/bolt-generator.js` (pass)
4. Run `yarn test:js` (fail, [see error](https://gist.github.com/danielamorse/5c5ad4651dd98b338f830bc510a0ff9d))

The second time you run `yarn test:js` it produces different snapshots. It seems like something is left over from previous tests (perhaps in `tmp`?) that changes the test results.

I discovered this when I had to update the individual generator snapshots. Then I ran all tests and saw the error. It's an edge case, but we should fix it before this gets merged.

@adamszalapski any thoughts on why this might happen?

2021-09-16 13:57 UTC, adamszalapski commented
Good catch @danielamorse 
This issue's related to test asynchronously and how our bolt-generator uses `tmp` folder for checking the file structure. I updated the approach how we use `tmp` folder and now the issue is gone. This was a tricky one to catch, good work @danielamorse 👍

2021-09-17 10:26 UTC, adamszalapski commented
@danielamorse I update whole folder structure for `bolt-generator` tests, right now temp folders are generated in specific (component or element) folder. At the moment all test passing without any issue, please double check if everything is good.
![image](https://user-images.githubusercontent.com/16049049/133768179-29d6cf83-3730-4709-a243-f7afd0533754.png)

2021-09-17 12:08 UTC, danielamorse approved these changes
@adamszalapski works perfectly now. Thank you!

2021-09-17 12:09 UTC, merged