[DO NOT MERGE] DS-599: Optimized Campaign Landing Page
boltdesignsystem/bolt pull request #2310
Opened 2021-09-03 17:27 UTC by colbytcook

## Jira

https://pegadigitalit.atlassian.net/browse/DS-599

## Summary

Created the demo pages for the Optimized Campaign Landing Page

## Details

* Created doc pages for the Optimized Campaign Landing Page templates
* Create doc pages for the Optimized Campaign Landing Page themes
* Modified the Layout CSS to fix a mobile bug
* Added a `center_component` prop to the Video Thumbnail Component

## How to test

- Pull down the branch and look at the Optimized Campaign Landing Page templates in the doc site
- Reveal the Patternlab test folder and look at the examples of the themes

## Release notes

* Added the Optimized Campaign Landing Page docs pages
* Added a `center_component` prop to the Video Thumbnail Component

2021-09-03 17:30 UTC, colbytcook commented
@mikemai2awesome I will like some feedback on the `layout.scss` change that was made. Adding the `minmax` function here solves the carousel width issues we were having with the `layout-item`. I have done testing on and it seems that it did not introduce any regressions but I would like to get other eyes on this.

2021-09-03 17:33 UTC, colbytcook commented
TODO: We need to solve the "Theme #4" and "Theme #6" image placements. It seems that these one are not rendering correctly on the template due to their image orientation (these are vertical while the remaining four are horizontal). We might need to re-export these assets to change their orientation.

2021-09-07 22:22 UTC, mikemai2awesome commented
@colbytcook Thank you for jumping on this. I'll review what you did. I don't think we need to change any assets, they are positioned with specific css in specific layouts.

2021-09-09 20:26 UTC, mikemai2awesome requested changes
Waiting for https://github.com/boltdesignsystem/bolt/pull/2313#pullrequestreview-750783062 to get the Video Thumbnail updates.

2021-09-10 12:20 UTC, mikemai2awesome approved these changes
I pulled in the Video Thumbnail updates. This is all set.

2021-09-10 13:48 UTC, danielamorse approved these changes
This looks good guys! Tested new templates and Bolt Layout (no regressions found).

I added the Button and Link Text icon spacing changes to the Release Notes. Important to flag this type of change for QA.

2021-09-10 13:48 UTC, danielamorse commented on packages/layouts/bolt-layout/src/layout-item.twig
> -  {{ source_order ? 'source-order="' ~ source_order ~ '"' : '' }}
Does this fix a bug? It looks like the name didn't match the schema before. If it fixes a Layout bug, let's note it in the Release Notes.

2021-09-10 18:09 UTC, remydenton commented on packages/layouts/bolt-layout/src/layout-item.twig
> -  {{ source_order ? 'source-order="' ~ source_order ~ '"' : '' }}
Seems like it would fix a bug... we're using the `<bolt-layout>` custom element in the layout authoring work, because twig wasn't working (I don't know the details).  Maybe this was the problem, or part of it?

2021-09-10 18:10 UTC, remydenton approved these changes
Broadly speaking, the code looks good.  We plan to review these with stakeholders, right?

2021-09-10 21:31 UTC, colbytcook commented on packages/layouts/bolt-layout/src/layout-item.twig
> -  {{ source_order ? 'source-order="' ~ source_order ~ '"' : '' }}
Yes this was a fix to a bug in the ordering, there was a discrepancy between the schema and the twig (exactly what you said Dan).

2021-09-10 21:33 UTC, merged