[DO NOT MERGE] DS-529: Pega.com: Add 'Download slides' CTA to PW Replays "Best Of" cards
boltdesignsystem/bolt pull request #2312
Opened 2021-09-08 14:47 UTC by MarcinMr

## Jira

https://pegadigitalit.atlassian.net/browse/DS-529

## Summary

Download slides cta was added.

## Details

Download slides cta was added to the `bolt-teaser` component in relation to the proposed wireframe.

## How to test

Pull the branch. Make sure the new CTA is correct in terms of semantics and accessibility.

2021-09-09 15:00 UTC, colbytcook approved these changes

2021-09-09 15:32 UTC, mikemai2awesome requested changes
@MarcinMr @colbytcook I think the Best-of demos under Pages should be updated as well. Additionally, remove all the phases and keep just one final version.

2021-09-09 15:32 UTC, mikemai2awesome commented on docs-site/src/pages/pattern-lab/_patterns/40-components/teaser/30-teaser-status-and-actions.twig
> +    {% set sr_only %}
This is not needed. The visible text is already descriptive enough. Also, I do not see in the ticket's Definition of Done that says include `(PDF, 3 pages, 2.3mb)`. Is the ticket out of date?

2021-09-09 15:32 UTC, mikemai2awesome commented on docs-site/src/pages/pattern-lab/_patterns/40-components/teaser/30-teaser-status-and-actions.twig
> +  {% set sr_only %}
Same comment as last. Not needed.

2021-09-09 15:32 UTC, mikemai2awesome commented on packages/components/bolt-teaser/teaser.schema.js
> +    download_cta: {
The other two props don't have `_cta` postfix, so do not include it for this one. Keep in consistent and just name it `download`.

2021-09-09 15:32 UTC, mikemai2awesome commented on packages/components/bolt-teaser/src/teaser.twig
> +        {% if like or share or download_cta %}
Update this after the prop is renamed to `download`.

2021-09-10 09:49 UTC, MarcinMr commented on docs-site/src/pages/pattern-lab/_patterns/40-components/teaser/30-teaser-status-and-actions.twig
> +    {% set sr_only %}
I've read that it's a good practice to add a file name, number of pages, and weight of o file for screen readers to announce details of a downloading resource. But if it is not necessary I've already deleted those labels.

2021-09-10 09:49 UTC, MarcinMr commented on docs-site/src/pages/pattern-lab/_patterns/40-components/teaser/30-teaser-status-and-actions.twig
> +  {% set sr_only %}
Deleted

2021-09-10 09:49 UTC, MarcinMr commented on packages/components/bolt-teaser/teaser.schema.js
> +    download_cta: {
Renamed

2021-09-10 09:49 UTC, MarcinMr commented on packages/components/bolt-teaser/src/teaser.twig
> +        {% if like or share or download_cta %}
Updated

2021-09-10 09:50 UTC, MarcinMr commented
> @MarcinMr we need to make like, share, download row left aligned. See the "New, clickable 'Download slides' CTA added to PW Replays cards added to the right of existing "Like" and "Share" CTAs (now aligned left)" definition of done.

@colbytcook changed to aligned left

2021-09-10 15:48 UTC, mikemai2awesome approved these changes
Excellent job! @MarcinMr

2021-09-10 15:49 UTC, mikemai2awesome commented on docs-site/src/pages/pattern-lab/_patterns/40-components/teaser/30-teaser-status-and-actions.twig
> +    {% set sr_only %}
If the data exists, they can create a tooltip with the info. I'll leave that for them to decide.

2021-09-10 15:50 UTC, danielamorse requested changes
Looks good from a code standpoint. Nice cleanup of our old demos.

@mikemai2awesome I noticed the Listing Teaser actions can get pretty cramped, and the ones using the Icon Component vs Element wrap differently. Maybe we at least want to convert "Views" to Element for consistent wrapping?

![image](https://user-images.githubusercontent.com/36336/132881270-ba780c11-1daa-4c8f-8171-4417beab6b15.png)

@MarcinMr since this includes a visual change to the alignment of the Listing Teaser actions, would you please add that to the PR Release Notes? See [this PR](https://github.com/boltdesignsystem/bolt/pull/2310) for reference on formatting.

2021-09-10 15:51 UTC, mikemai2awesome commented on docs-site/src/pages/pattern-lab/_patterns/40-components/teaser/30-teaser-status-and-actions.twig
> +    {% set sr_only %}
I asked Ross in the ticket. Will wait for his reply. https://pegadigitalit.atlassian.net/browse/WWW-858?focusedCommentId=37360

2021-09-10 15:53 UTC, mikemai2awesome requested changes
@danielamorse Good catch. We should fix that.

2021-09-10 20:56 UTC, mikemai2awesome approved these changes
I pushed a fix for it. The icon alignment was off. @colbytcook

2021-09-10 21:22 UTC, colbytcook approved these changes

2021-09-11 01:26 UTC, danielamorse approved these changes
Alignment is fixed, code looks good 👍 

1. Updated the Teaser Jest snapshots, waiting for those to pass on Travis.
2. Updated the Teaser Status and Actions demo to use the [Twig](https://github.com/boltdesignsystem/bolt/pull/2312/files#diff-f73705727454aa76dd3ab6a16ec91b54d1b38dd06fd9ef21d0665c0e0c7db4c7R105-R114) version of Tooltip instead of the [web component](https://github.com/boltdesignsystem/bolt/pull/2312/commits/bdbeaeae98ecc78b48c41b7401df124e0faf891a#diff-f73705727454aa76dd3ab6a16ec91b54d1b38dd06fd9ef21d0665c0e0c7db4c7R105-R115). We use `<bolt-tooltip>` internally in some templates because it's convenient, but for demo code that devs will reference I think we want Twig.

@colbytcook @mikemai2awesome let me know if I'm missing something regarding the second note. If not, and you approve, ship this thing! :shipit:

2021-09-13 09:33 UTC, MarcinMr commented
> @MarcinMr since this includes a visual change to the alignment of the Listing Teaser actions, would you please add that to the PR Release Notes? See [this PR](https://github.com/boltdesignsystem/bolt/pull/2310) for reference on formatting.

@danielamorse Updated PR with release notes and visual changes

2021-09-13 09:49 UTC, MarcinMr commented
> @mikemai2awesome I noticed the Listing Teaser actions can get pretty cramped, and the ones using the Icon Component vs Element wrap differently. Maybe we at least want to convert "Views" to Element for consistent wrapping?
> 
@danielamorse @mikemai2awesome 

There is also a small issue with the horizontal teaser on a small screen. Newly added CTA overflows the viewport.

<img width="380" alt="overflow" src="https://user-images.githubusercontent.com/85670248/133062072-929f32c5-c504-4209-923d-d6b5d0fe15f3.png">

Perhaps we should wrap the list or entire block on the really small screens like on the shots below:

<img width="379" alt="list-wrap" src="https://user-images.githubusercontent.com/85670248/133062272-6394e5d6-ae95-4d7b-9b29-5685e07453a5.png"><img width="371" alt="whole-block-wrap" src="https://user-images.githubusercontent.com/85670248/133062309-201180bb-902d-4f49-9eca-86636ed9a78b.png">

2021-09-13 12:04 UTC, merged