WWW-960: mobile nav top link color
boltdesignsystem/bolt pull request #2314
Opened 2021-09-09 21:39 UTC by remydenton

## Jira

https://pegadigitalit.atlassian.net/browse/WWW-960

## Summary

Makes unselected top-level mobile links black for consistency

## Details

See screenshots in the "visual changes" section below.  All other colors should be unchanged.

## How to test

See screenshots in the "visual changes" section below.  All other colors should be unchanged.

## Release notes

### Visual changes

In the global nav, top-level links are now black instead of dark navy when not selected.  For example, on https://boltdesignsystem.com/pattern-lab/?p=components-page-header-example-main-site-with-subnav

Before:
![Screen Shot 2021-09-09 at 5 36 19 PM](https://user-images.githubusercontent.com/677668/132765883-b5c7f589-5b06-43b4-b374-2250b03c787c.png)

After:
![Screen Shot 2021-09-09 at 5 35 49 PM](https://user-images.githubusercontent.com/677668/132765880-d52eaf89-323d-4962-9d35-3f6ee0b68f92.png)

2021-09-09 22:29 UTC, mikemai2awesome requested changes
Page header is very complicated. Your change affected some other elements. I need a closer look tomorrow.

2021-09-10 14:47 UTC, mikemai2awesome approved these changes

2021-09-10 14:48 UTC, mikemai2awesome commented
All set.

2021-09-10 15:52 UTC, remydenton commented
With the latest changes, top level links have a different color in focus state (black)...
![Screen Shot 2021-09-10 at 11 45 15 AM](https://user-images.githubusercontent.com/677668/132881023-eb5611c3-18da-4881-8634-9a1cfa45ce04.png)

... than other links in focus state (dark navy)
![Screen Shot 2021-09-10 at 11 46 14 AM](https://user-images.githubusercontent.com/677668/132881123-87598fae-b379-4b7d-8864-7df6167738a8.png)

I actually don't see a good reason to have an `[aria-expanded='true']` style for mobile links, since they have identical styling to other links, hence my commit comment in [a2e752](https://github.com/boltdesignsystem/bolt/pull/2314/commits/a2e752).

At the end of the day, I don't really care as long as stakeholders are happy, and you're the original author @mikemai2awesome, so your call.

2021-09-10 15:56 UTC, mikemai2awesome commented
@remydenton They are both in expanded state, so the color should be kept consistent.

2021-09-10 16:22 UTC, colbytcook approved these changes

2021-09-10 16:29 UTC, remydenton commented
> They are not both in expanded state (one is acting as a heading and expanded, the other is an item and not expanded), so the color should be kept consistent (expanded state is black).

I'm aware they're not both expanded.  If you're trying to show that they're in different states, why do they look the same when not in focus state?

IMO, they should look identical, unless you want to distinguish between expanded and not-expanded links, in which case they should be styled differently both when focused and not.

Pretty sure the original PR makes more sense, unless there are other situations I'm not aware of.

2021-09-10 16:31 UTC, mikemai2awesome commented
@remydenton They shouldn't look the same intially. I intended headlines to take on headline color, links to take on link color, but I'm forced to change them to black which makes no sense.

2021-09-10 16:34 UTC, remydenton commented
> I'm forced to change them to black which makes no sense.

Fair, I think that's probably the root cause of why it feels weird to me.  I'm fine with this as-is, but let me have stakeholders take a look at the Pattern Lab demo link first so that we don't run the risk of yet more change requests 😄 .

2021-09-10 18:21 UTC, colbytcook commented
@mikemai2awesome @remydenton it looks like Ross responded to the JIRA question, we should be good to merge this one!

2021-09-10 18:23 UTC, merged