DS-483 code snippet updates
boltdesignsystem/bolt pull request #2317
Opened 2021-09-10 19:02 UTC by danielamorse

## Jira

https://pegadigitalit.atlassian.net/browse/DS-483

## Summary

(Enter a one-line summary of the changes in this PR. This will be included in the release notes)

## Details

(Explain the changes in enough detail fo reviewers to understand. Raise any questions for reviewers to consider.)

## How to test

(List clear steps to test that the changes are working)

## Release notes

(Optionally, add details that will be added to the release notes. Use this to call out deprecations. [Read more](https://intuit.github.io/auto/docs/generated/changelog#additional-release-notes))

### Visual changes

(Note any visual changes associated with this PR. This will be shared with QA team for VRT.)

2021-09-23 20:07 UTC, mikemai2awesome requested changes
Just one doc edit then all set.

2021-09-23 20:07 UTC, mikemai2awesome commented on docs-site/src/pages/pattern-lab/_patterns/40-components/code-snippet/20-code-snippet-custom-language-label.twig
> +  description: description,
Missing description.

2021-09-23 20:38 UTC, danielamorse commented on docs-site/src/pages/pattern-lab/_patterns/40-components/code-snippet/20-code-snippet-custom-language-label.twig
> +  description: description,
Good catch, [added](https://github.com/boltdesignsystem/bolt/pull/2317/commits/96c7434fda98c21948f81c0190ec7a7fa75cd1c8).

2021-09-23 20:41 UTC, mikemai2awesome approved these changes

2021-09-23 21:45 UTC, remydenton approved these changes
Looks great.  I left a few nitpick comments because I just couldn't help myself.  Should have been a librarian I guess 🤓 .

2021-09-23 21:45 UTC, remydenton commented on docs-site/src/pages/pattern-lab/_patterns/40-components/code-snippet/15-code-snippet-mode.twig
> +{% endset %}
What happens if you indent these?  e.g.:

```
     ...
    } only %}
  {% endverbatim %}
{% endset %}
```
Does it mess up the demo?  I was just thinking it makes it harder to read here, not the end of the world though.

2021-09-23 21:45 UTC, remydenton commented on docs-site/src/pages/pattern-lab/_patterns/40-components/code-snippet/20-code-snippet-custom-language-label.twig
> +  html_markup: html_markup
Total nitpick, but I noticed in some places you don't include a trailing comma after the last item in an array.

I realize this is extra nitpicky because we don't have official coding standards, but I think it makes sense to always have the trailing comma for the reasons you do it on other languages (js, php): to avoid extra noise in commit diffs.

2021-09-24 11:15 UTC, danielamorse commented on docs-site/src/pages/pattern-lab/_patterns/40-components/code-snippet/15-code-snippet-mode.twig
> +{% endset %}
We can't indent here or it will add the indentation whitespace to the rendered code-snippet. However, to make it easier to read we _could_ do this:
```
{% set twig_markup %}{% verbatim %}
...
{% endverbatim %}{% endset %}
```

Instead of this:
```
{% set twig_markup %}
{% verbatim %}
...
{% endverbatim %}
{% endset %}
```

Thoughts @remydenton @mikemai2awesome?

2021-09-24 11:36 UTC, danielamorse commented on docs-site/src/pages/pattern-lab/_patterns/40-components/code-snippet/20-code-snippet-custom-language-label.twig
> +  html_markup: html_markup
Bad habit of mine. Fixed!

I've grown used to Prettier doing this for me. I created [this ticket](https://pegadigitalit.atlassian.net/browse/DS-635) to try again to get some level of auto-formatting in Twig.

2021-09-24 13:52 UTC, remydenton commented on docs-site/src/pages/pattern-lab/_patterns/40-components/code-snippet/15-code-snippet-mode.twig
> +{% endset %}
Thanks @danielamorse, I think your suggestion is a small improvement, but certainly not required.

2021-09-29 18:12 UTC, mikemai2awesome commented on docs-site/src/pages/pattern-lab/_patterns/40-components/code-snippet/15-code-snippet-mode.twig
> +{% endset %}
We've been dealing with this for a long time, that's just the way it is. Any extra space will create undesired indents. Either way is fine on how we write verbatim.

2021-09-29 23:45 UTC, danielamorse commented
@mikemai2awesome ok updated with master. The upgrade to Twig 2 brought some unexpected errors that I just chased down and fixed. One of them resulted from using the `{% raw %}` filter to wrap `{% verbatim %}`. It worked in Twig 1 but now throws an error. I'm back to thinking there's no reasonable way to display an escaped `{% verbatim %}` tag in this demo. You can't event write them inside comments (!) or Twig will parse them. Instead I did this:

```
{% set twig_code %}
{# Twig does not allow nested verbatim tags, so the required verbatim tag placement for Twig language code snippets is shown in comments below #}
{# verbatim goes here #}
{% include '@bolt-components-banner/banner.twig' with {
  content: 'This is the banner content.'
} only %}
{# endverbatim goes here #}
{% endset %}
```

I figured this was better than simply leaving the Twig demo out, leaving the user wondering how to make a Twig code snippet.

2021-09-30 13:00 UTC, merged