[Do Not Merge] DS 594 Replace component-icons in Elements and Components
boltdesignsystem/bolt pull request #2320
Opened 2021-09-14 19:03 UTC by cjwhitedev

## Jira

[https://pegadigitalit.atlassian.net/browse/DS-594](https://pegadigitalit.atlassian.net/browse/DS-594)

## Summary

(Enter a one-line summary of the changes in this PR. This will be included in the release notes)

## Details

(Explain the changes in enough detail fo reviewers to understand. Raise any questions for reviewers to consider.)

## How to test

(List clear steps to test that the changes are working)

## Release notes

(Optionally, add details that will be added to the release notes. Use this to call out deprecations. [Read more](https://intuit.github.io/auto/docs/generated/changelog#additional-release-notes))

### Visual changes

(Note any visual changes associated with this PR. This will be shared with QA team for VRT.)

2021-09-15 21:41 UTC, mikemai2awesome requested changes

2021-09-15 21:41 UTC, mikemai2awesome commented on packages/components/bolt-page-header/src/page-header.scss
> +    > bolt-icon,
Let's revert any Page Header changes. I am taking care of it in the page header specific branch, I wanna avoid CSS conflicts. We'll make sure to bundle this and that branch together in the next release. @cjwhitedev

2021-09-17 19:40 UTC, mikemai2awesome commented on packages/components/bolt-page-header/src/page-header.scss
> +    > bolt-icon,
Reverted.

2021-09-20 13:58 UTC, danielamorse commented
@cjwhitedev quick note about the release notes (thank you for adding them 🙏)... It's important to give enough context to readers: devs and QA. Maybe I err on the side of too much, but I think it beats the alternative.

> Replaced components-icon with elements-icon

Where? In what components?

Also, something I was just a little unclear about:
> Yellow icon color is one shade darker. This matches the component version.

What exactly should QA be looking for? Are all yellow icons a shade darker or were two that were slightly different colors now exactly the same color?

2021-09-20 15:46 UTC, cjwhitedev commented
@danielamorse I will take another look at the release notes, but @mikemai2awesome added the visual change notes. Can you provide feedback on that @mikemai2awesome?

2021-09-20 17:46 UTC, danielamorse requested changes
Reviewed the code. Lots of great cleanup here! Please see inline comment.

Would you please also update the PR description with a list of the components that changed so I can do a visual QA of the front-end?

2021-09-20 17:46 UTC, danielamorse commented on packages/components/bolt-action-blocks/package.json
> +    "@bolt/elements-icon": "^4.4.0"
If `@bolt/components-icon` is no longer used, it can be removed as a dependency.

2021-09-20 17:46 UTC, danielamorse commented on packages/components/bolt-content-pagination/package.json
> +    "@bolt/elements-icon": "^4.4.0",
Ditto - don't need `@bolt/components-icon` (or `@bolt/components-tooltip` while we're at it).

2021-09-20 17:46 UTC, danielamorse commented on packages/components/bolt-copy-to-clipboard/__tests__/__snapshots__/copy-to-clipboard.js.snap
> +          Error trying to render "@bolt-elements-icon/icon.twig". Template "@bolt-elements-icon/icons/add-open.twig" is not defined in "@bolt-elements-icon/icon.twig" at line 30.
Let's fix this snapshot.

2021-09-20 17:46 UTC, danielamorse commented on packages/components/bolt-copy-to-clipboard/package.json
> +    "@bolt/elements-icon": "^4.4.0",
Ditto - don't need `@bolt/components-icon` or `@bolt/components-link`

2021-09-20 17:46 UTC, danielamorse commented on packages/components/bolt-listing-teaser/package.json
> +    "@bolt/elements-icon": "^4.4.0",
Please review this component and remove unused dependencies. Looks like there are several including `@bolt/components-icon`, `@bolt/components-button`, `@bolt/components-menu.

Also, it is missing at least `@bolt/elements-button`.

To see what's a dependency check Twig, SCSS (sometimes styles are included), and JS (if it's a web component).

2021-09-20 17:46 UTC, danielamorse commented on packages/components/bolt-listing-teaser/src/listing-teaser.scss
> +    .e-bolt-icon {
Do we need to support both or did we completely replace the old component usage here? If this is user provided content, then this is ok.

2021-09-20 17:46 UTC, danielamorse commented on packages/components/bolt-page-footer/package.json
> +    "@bolt/elements-icon": "^4.4.0"
Remove `@bolt/components-icon`

2021-09-20 17:46 UTC, danielamorse commented on packages/components/bolt-share/package.json
> +    "@bolt/elements-icon": "^4.4.0"
Please remove `@bolt/components-icon` and check to see if any others are missing or unused.

2021-09-20 17:46 UTC, danielamorse commented on packages/elements/bolt-text-link/package.json
> +    "@bolt/elements-icon": "^4.4.0",
Remove `@bolt/components-icon`

2021-09-20 18:02 UTC, cjwhitedev commented on packages/elements/bolt-text-link/__tests__/__snapshots__/text-link.js.snap
> +    <svg class="e-bolt-icon"
yes mike changed the chevron as part of this i believe so i will update tests now.

2021-09-20 19:30 UTC, cjwhitedev commented on packages/components/bolt-listing-teaser/src/listing-teaser.scss
> +    .e-bolt-icon {
i believe there are certain cases where a use can supply an icon, so we should leave both.

2021-09-23 19:33 UTC, mikemai2awesome approved these changes
@danielamorse The shade in yellow is a very slight change, they might not even notice. If you can word it better, go ahead.

2021-09-23 19:59 UTC, danielamorse requested changes
Looks good! Last thing to fix is the error in the teaser snapshot. Once that's resolved, this is good to go.

2021-09-23 19:59 UTC, danielamorse commented on packages/components/bolt-action-blocks/package.json
> -    "@bolt/components-icon": "^4.4.0",
We still need `@bolt/elements-icon` here. I added it.

2021-09-23 19:59 UTC, danielamorse commented on packages/components/bolt-content-pagination/package.json
> -    "@bolt/components-tooltip": "^4.4.0",
My bad, we do still need tooltip (I might've been looking at the other Pagination component). I'm adding it back in.

2021-09-23 19:59 UTC, danielamorse commented on packages/components/bolt-teaser/__tests__/__snapshots__/teaser.js.snap
> +                  <code>
We're getting an error trying to render Icon element here. Can you please look into this @cjwhitedev?

2021-09-23 20:07 UTC, danielamorse commented
> @danielamorse The shade in yellow is a very slight change, they might not even notice. If you can word it better, go ahead.

The wording is fine. I just removed "This matches the component version", as QA doesn't necessarily know or need to know what's a component vs element.

2021-09-24 15:11 UTC, danielamorse approved these changes

2021-09-24 15:14 UTC, merged