DS 615 Convert 'string' to 'any' in schema where appropriate
boltdesignsystem/bolt pull request #2323
Opened 2021-09-16 10:59 UTC by MarcinMr

## Jira

https://pegadigitalit.atlassian.net/browse/DS-615

## Summary

`String` props were changed to `any` across all `.schema`'s files.

## Details

`String` props were changed to `any` across all `.schema`'s in all:

- bolt elements
- bolt components

## How to test

Pull the branch, Make sure all `string` props were changed to `any`. Check if there is more to change or if some of them were changed unnecessarily.

2021-09-16 12:04 UTC, MarcinMr commented
@remydenton 

I went thru `.schema` files and converted `string` to `any` I wasn't sure of each of them. So if you find some unnecessary changes or places where the change should be please let me know and I'll fix them.

I was not sure if there were examples such as:  `src`,`url`, `hrefs`, `ids`.

And how about `[string, object,]` or `[string, object, array]`. If there is more than one type of data shouldn't it be converted to `any`?

2021-09-23 19:26 UTC, remydenton requested changes
I've only looked through the first few examples, but it's clear that this is a much more delicate proposition than going through and bulk changing `string` to `any`.  You have to really understand what's going on under the hood, making sure to not cause conflicts with the use of `init()`/`this.data`, and also recognize when an `enum` is actually implied and was just omitted by the original author.

2021-09-23 19:26 UTC, remydenton commented on packages/components/bolt-card-replacement/__tests__/__snapshots__/card-replacement.js.snap
> -        <bolt-card-replacement-action url="https://pega.com">
This is another test that is showing that something that's needed is now missing.

The lesson here @MarcinMr is that you should always double check when a test snapshot has failed and ask whether it makes sense.  Sometimes it does and you can safely just update the snapshot, but other times (like this) it is catching a real error.

2021-09-23 19:26 UTC, remydenton commented on packages/components/bolt-card-replacement/card-replacement.schema.js
> -            type: 'string',
The problem with changing this from `string` to `any` is that it will not longer pass through init() and appear appear in `this.data`:

https://github.com/boltdesignsystem/bolt/blob/master/packages/components/bolt-card-replacement/src/card-replacement-actions/_card-replacement-action.twig#L6

That's because it no longer returns true from `isAllowedSchemaType()`:

https://github.com/boltdesignsystem/bolt/blob/master/packages/twig-integration/twig-extensions-shared/src/Utils.php#L206

Maybe the right answer in this case is to not use this.data in the twig template, and instead use `{{ url }}`.  Thoughts @danielamorse ?

2021-09-23 19:26 UTC, remydenton commented on packages/components/bolt-card-replacement/card-replacement.schema.js
> -            type: 'string',
This will also break for the same reason as `url` (we're using this.data.text).

https://github.com/boltdesignsystem/bolt/blob/master/packages/components/bolt-card-replacement/src/card-replacement-actions/_card-replacement-action.twig#L23

Like `url`, I believe the correct answer here is to change the schema to `any` and not use `this.data` in the twig template.

2021-09-23 19:26 UTC, remydenton commented on packages/components/bolt-card-replacement/card-replacement.schema.js
> -            type: 'string',
This will break for the same reason as `url` (we're using `this.data.icon`):

https://github.com/boltdesignsystem/bolt/blob/master/packages/components/bolt-card-replacement/src/card-replacement-actions/_card-replacement-action.twig#L33

However, unlike for `url` and `text`, I think we want to keep the schema type as `string` and add an `enum` for what strings are valid for icon name (import the valid values from the icon component).  The description should also be updated to indicate that this only accepts an icon name (perhaps it should actually accept a rendered icon as well, but we'll save that for another day).

2021-09-23 19:26 UTC, remydenton commented on packages/components/bolt-copy-to-clipboard/copy-to-clipboard.schema.js
> -      type: 'string',
We probably shouldn't update `DEPRECATED` props at all.  But, I couldn't help but notice that iconSize should be have an `enum` and should not be of type `any`.

2021-12-09 17:03 UTC, colbytcook commented
Closing this PR for now, we will revisit this with a more granular approach (the ticket will have reference to this PR and the branch).

2021-12-09 17:03 UTC, closed without merging