[DO NOT MERGE] com-707: raise signifier link above headline link
boltdesignsystem/bolt pull request #2326
Opened 2021-09-23 19:30 UTC by mikemai2awesome

## Jira

(Enter a link to the Jira issue this PR applies to, if any)

## Summary

(Enter a one-line summary of the changes in this PR. This will be included in the release notes)

## Details

(Explain the changes in enough detail fo reviewers to understand. Raise any questions for reviewers to consider.)

## How to test

(List clear steps to test that the changes are working)

## Release notes

(Optionally, add details that will be added to the release notes. Use this to call out deprecations. [Read more](https://intuit.github.io/auto/docs/generated/changelog#additional-release-notes))

### Visual changes

(Note any visual changes associated with this PR. This will be shared with QA team for VRT.)

2021-09-29 13:51 UTC, colbytcook requested changes
I can confirm this looks correct on Safari and Chrome but I am not seeing it work properly on Firefox.

2021-10-01 13:20 UTC, colbytcook commented
@mikemai2awesome Looks good! 

I am seeing the fix on the Listing Teaser Search (/pattern-lab/?p=components-listing-teaser-use-case-search-result-list) page but I am not Community Search Page (/pattern-lab/?p=pages-community-search-layout). Not sure if that matters or not but I figured I would call it out.

2021-10-01 16:14 UTC, mikemai2awesome commented
@colbytcook Good catch. This should do it.

2021-10-04 16:59 UTC, colbytcook approved these changes

2021-10-04 17:37 UTC, merged