Build Hero Demos with Layout
boltdesignsystem/bolt pull request #2331
Opened 2021-09-27 15:26 UTC by cjwhitedev

## Jira

[DS-622](https://pegadigitalit.atlassian.net/browse/DS-622)

## Summary

Show Hero examples using Layout

## Details

We want to deprecate and remove the Hero Component, and not have a stand-alone replacement for it. These are demos showing how to use layout in different ways to replace Hero.

## How to test

Pull the branch and compare the new layout hero demos against the Hero Component demos.

2021-09-27 17:01 UTC, mikemai2awesome requested changes
@cjwhitedev Let's convert all usage to twig. As we discussed before, we haven't landed on the naming conventions yet, that's why the Layout docs currently have a warning message. Using twig template will ensure it will continue to work even when we change up the HTML and naming conventions.

2021-09-29 18:06 UTC, mikemai2awesome requested changes

2021-09-30 12:15 UTC, cjwhitedev commented on docs-site/src/pages/pattern-lab/_patterns/50-pages/80-heroes-with-layout/45-centered-content.twig
> +{% set _content %}
They were requested. They details are in the ticket.

2021-09-30 14:20 UTC, mikemai2awesome commented on docs-site/src/pages/pattern-lab/_patterns/50-pages/80-heroes-with-layout/45-centered-content.twig
> +{% set _content %}
@cjwhitedev I see. Can you build out exactly what they have in the screenshots? https://pegadigitalit.atlassian.net/browse/WWW-857

2021-11-17 14:55 UTC, colbytcook commented on docs-site/src/pages/pattern-lab/_patterns/50-pages/80-heroes-with-layout/45-centered-content.twig
> +{% set _content %}
@mikemai2awesome I added the live examples to the "Heroes with layout" folder on the doc site. I also moved the existing work to the test folder. Each live site example has a "Notes" section that give integration specifications on how to build each one of the heroes.

2021-11-18 12:42 UTC, colbytcook approved these changes

2021-11-19 18:59 UTC, mikemai2awesome approved these changes

2021-11-22 12:26 UTC, merged