DS-648: Update "information" banner colors
boltdesignsystem/bolt pull request #2334
Opened 2021-09-29 19:51 UTC by danielamorse

## Jira

https://pegadigitalit.atlassian.net/browse/DS-648

## Summary

Update the background and text colors of "information" banner.

## Details

As requested by Academy/Collaboration Center, banners with "information" status will now have light blue background and dark blue text.

## How to test

- Review code changes
- Review Banner demos, particularly "status" demo

## Release notes

### Visual changes
- Banner with status "information" are now light blue with dark blue text. Previously they were white with black text.

2021-09-29 20:22 UTC, mikemai2awesome requested changes

2021-09-29 20:22 UTC, mikemai2awesome commented on packages/components/bolt-banner/src/banner.scss
> +  border-left-color: var(--bolt-color-info-dark);
Use `--bolt-color-info` for the border. And then add the following:

```
@include bolt-repeat-rule(
  ('bolt-banner[status=information]', ':host(bolt-banner[status=information])')
) {
  --m-bolt-text: var(--bolt-color-info-dark);
  --m-bolt-headline: var(--bolt-color-info-dark);
  --m-bolt-link: var(--bolt-color-info-dark);
}
```

2021-10-04 16:43 UTC, danielamorse commented on packages/components/bolt-banner/src/banner.scss
> +  border-left-color: var(--bolt-color-info-dark);
@mikemai2awesome updated.

I don't think any of [these `:host()` rules](https://github.com/boltdesignsystem/bolt/blob/d45bc41da99d38e1e2ae76b2e53738acd647e1a8/packages/components/bolt-banner/src/banner.scss#L28-L57) are necessary, but I'm fine adding one for `[status="information"]` for consistency until this is reworked. The only reason we'd need the `:host()` selector is if the WC was used in an environment where bolt-global styles weren't loaded or inside the Shadow DOM (and none of our components put Banner inside their Shadow DOM).

2021-10-04 20:42 UTC, mikemai2awesome approved these changes

2021-10-04 20:43 UTC, merged