DS-590 Switch button component
boltdesignsystem/bolt pull request #2382
Opened 2021-11-12 17:23 UTC by colbytcook

## Jira

https://pegadigitalit.atlassian.net/browse/DS-590

## Summary

Adds a new component, Switch Button, which handles boolean UI functions that happens instantly.

## Details

1. Added new component, Jest test and docs.
2. Only bare minimum props are created to handle basic needs for the notifications project. We can expand on this component down the road.

## How to test

Run the branch locally and proof read the Switch Button docs. Make sure the docs are intuitive. Inspect the demo and change on/off to some other language that might be longer, make sure it looks ok. Then check the component code for any mistakes in the code.

2021-11-12 17:26 UTC, colbytcook commented
Refer to the previous PR for conversations and approvals, https://github.com/boltdesignsystem/bolt/pull/2356

2021-11-12 17:33 UTC, mikemai2awesome requested changes

2021-11-12 17:33 UTC, mikemai2awesome commented on packages/components/bolt-switch-button/switch-button.schema.js
> +      description: 'Controls the active state of the switch button',
Update the text here: "Set button state to on by default."

2021-11-12 17:33 UTC, mikemai2awesome commented on packages/components/bolt-switch-button/switch-button.schema.js
> +      description: 'Unique ID for popover, randomly generated if not provided.',
Fix the typo here. Switch button instead of popover.

2021-11-12 17:33 UTC, mikemai2awesome commented on packages/components/bolt-switch-button/src/switch-button.twig
> +<label {{ attributes.addClass(classes)|without('for') }} for="{{ _switch_button_id }}" uuid="{{ _uuid }}">
We want to use `uuid` value for `_switch_button_id` if provided, not as a separate attribute.

2021-11-12 17:35 UTC, colbytcook commented on packages/components/bolt-switch-button/src/switch-button.twig
> +<label {{ attributes.addClass(classes)|without('for') }} for="{{ _switch_button_id }}" uuid="{{ _uuid }}">
ah good catch, I will update that

2021-11-12 17:45 UTC, danielamorse commented on packages/components/bolt-switch-button/src/switch-button.twig
> +{% set _uuid = this.data.uuid|default(bolt.data.config.env == 'test' ? '12345' : random() ~ '') %}
@colbytcook @mikemai2awesome I don't think I explained myself well in [my original comment](https://github.com/boltdesignsystem/bolt/pull/2356#pullrequestreview-797985120) 😆 

We don't actually need a `uuid` prop to be output. Let's discuss.

2021-11-12 19:54 UTC, mikemai2awesome approved these changes

2021-11-16 14:16 UTC, danielamorse approved these changes

2021-11-16 14:16 UTC, danielamorse commented on docs-site/src/pages/pattern-lab/_patterns/999-tests/switch-button/switch-button-id.twig
> +      id: 'super-special-id-that-is-wonderful'
🤣

2021-11-16 14:17 UTC, merged