[DO NOT MERGE] DS-590 Profile view
boltdesignsystem/bolt pull request #2383
Opened 2021-11-13 04:22 UTC by mikemai2awesome

## Jira

(Enter a link to the Jira issue this PR applies to, if any)

## Summary

(Enter a one-line summary of the changes in this PR. This will be included in the release notes)

## Details

(Explain the changes in enough detail fo reviewers to understand. Raise any questions for reviewers to consider.)

## How to test

(List clear steps to test that the changes are working)

## Release notes

(Optionally, add details that will be added to the release notes. Use this to call out deprecations. [Read more](https://intuit.github.io/auto/docs/generated/changelog#additional-release-notes))

### Visual changes

(Note any visual changes associated with this PR. This will be shared with QA team for VRT.)

2021-11-15 22:50 UTC, mikemai2awesome commented
@danielamorse Need JS help with the Info Section component, convert the JS in `index.js` to be production ready in `info-section.js`.

```
const infoSectionToggleButtons = document.querySelectorAll(
  '.js-bolt-info-section-toggle-button',
);

infoSectionToggleButtons.forEach(button => {
  button.addEventListener('click', e => {
    const el = e.target;
    const isExpanded = el.getAttribute('aria-expanded') === 'true';
    const otherButtons = [...infoSectionToggleButtons].filter(
      button => button !== el,
    );

    if (isExpanded) {
      el.setAttribute('aria-expanded', false);
    } else {
      otherButtons.forEach(el => {
        el.setAttribute('aria-expanded', false);
      });
      el.setAttribute('aria-expanded', true);
    }
  });
});
```

2021-11-16 19:46 UTC, danielamorse commented
> @danielamorse Need JS help with the Info Section component, convert the JS in `index.js` to be production ready in `info-section.js`.

@mikemai2awesome, done in https://github.com/boltdesignsystem/bolt/pull/2383/commits/9c58bf858c259636c5561f26c3189cccdb66312d

2021-11-17 20:07 UTC, danielamorse approved these changes

2021-11-17 21:15 UTC, remydenton requested changes

2021-11-17 21:15 UTC, remydenton commented on packages/components/bolt-profile/src/profile.twig
> +      <h1><strong>{{ first_name }} {{ last_name }}</strong> (@{{ username }})</h1>
Two thoughts on the (@{{ username }}) pattern:

- Seems a little opinionated-- are we confident that all usernames should always start with `@`?  Even if it's 90% likely, we could just have them append the `@` in the data.  If you're sure though, this is OK.
- If no username is passed, you get ` (@)` here (username is not required in the schema).  We should add a conditional check to avoid printing the surroundings if it's empty.

2021-11-17 21:15 UTC, remydenton commented on docs-site/src/pages/pattern-lab/_patterns/40-components/profile/10-profile-full-bleed.twig
> +          type: 'button',
Curious, how come this is a button?  Is something supposed to happen when you click it?

2021-11-17 21:15 UTC, remydenton commented on packages/components/bolt-profile/src/profile.twig
> +          {% set _item_tag = _item_attributes.type ? 'button' : _item_attributes.href ? 'a' : 'span' %}
Shouldn't this be:
`{% set _item_tag = _item_attributes.type ? _item_attributes.type : ...`

As it is, if you pass any value for `item.attributes.type` and you'll always get `button`.

I also don't see `stats` in the schema, it should be added to clarify what kind of data is expected.

2021-11-17 21:15 UTC, remydenton commented on packages/components/bolt-profile/src/profile.twig
> +      {% if message %}
Please add `message` to the schema.

2021-11-17 21:38 UTC, mikemai2awesome commented on docs-site/src/pages/pattern-lab/_patterns/40-components/profile/10-profile-full-bleed.twig
> +          type: 'button',
These things are supposed to bring up modals.

2021-11-17 22:30 UTC, mikemai2awesome commented on packages/components/bolt-profile/src/profile.twig
> +          {% set _item_tag = _item_attributes.type ? 'button' : _item_attributes.href ? 'a' : 'span' %}
Added stats prop.

2021-11-17 22:31 UTC, mikemai2awesome commented on docs-site/src/pages/pattern-lab/_patterns/40-components/profile/10-profile-full-bleed.twig
> +          type: 'button',
Added notes.

2021-11-17 22:31 UTC, mikemai2awesome commented on packages/components/bolt-profile/src/profile.twig
> +      <h1><strong>{{ first_name }} {{ last_name }}</strong> (@{{ username }})</h1>
Combined into one `name` prop.

2021-11-17 22:31 UTC, mikemai2awesome commented on packages/components/bolt-profile/src/profile.twig
> +      <svg enable-background="new 0 0 600 205.8" viewBox="0 0 600 205.8" xmlns="http://www.w3.org/2000/svg"><path d="m142.8 0h457.2v205.7h-457.2z" fill="var(--bolt-color-yellow)"/><path d="m0 0h142.8
Created separate templates for the SVGs.

2021-11-17 22:31 UTC, mikemai2awesome commented on packages/components/bolt-profile/src/profile.twig
> +      {% if message %}
Added to schema.

2021-11-18 14:00 UTC, colbytcook commented on packages/components/bolt-profile/src/profile.scss
> +  aspect-ratio: 4/1;
This is not yet supported yet in Safari and the profile_cover is displaying much larger than expected.

2021-11-18 14:00 UTC, colbytcook commented on packages/components/bolt-profile/src/profile.scss
> +      aspect-ratio: 7/1;
This is not yet supported yet in Safari and the profile_cover is displaying much larger than expected.

2021-11-18 14:40 UTC, mikemai2awesome commented on packages/components/bolt-profile/src/profile.scss
> +  aspect-ratio: 4/1;
It is supported. I am controlling the cover SVG with CSS.

2021-11-18 14:41 UTC, mikemai2awesome commented on packages/components/bolt-profile/src/profile.scss
> +      aspect-ratio: 7/1;
Same as the other comment.

2021-11-18 15:10 UTC, colbytcook commented on packages/components/bolt-profile/src/profile.scss
> +  aspect-ratio: 4/1;
<img width="1680" alt="Screen Shot 2021-11-18 at 10 03 01 AM" src="https://user-images.githubusercontent.com/1932313/142441047-c3954941-1266-4920-80af-14495ed13d58.png" >
<img width="1680" alt="Screen Shot 2021-11-18 at 10 05 12 AM" src="https://user-images.githubusercontent.com/1932313/142441082-d62b5705-43ad-4ed9-8f9b-636246bfc8c7.png">

Is this the intended display? The cover image looks much larger than it does in other browsers. As far as I know I am on the most current Safari version.

The second image just shows the "Unsupported property value" flag on the aspect-ratio. By any chance do you have some kind of experimental  support  checked or something?

2021-11-18 15:15 UTC, colbytcook commented on packages/components/bolt-profile/src/profile.scss
> +  aspect-ratio: 4/1;
@mikemai2awesome by any chance do you `Developer > Experimental Features > CSS Aspect Ratio` checked in the Safari menu?

2021-11-18 15:16 UTC, remydenton commented on packages/components/bolt-profile/profile.schema.js
> +      properties: {
Instead of `properties`, you should use the "items" key when the data you're expecting is an array.

```
stats: {
  type: 'array',
  description: 'Render stats with text labels.',
  items: {
    type: 'object',
    properties: {
      attributes: {
        ...
```

See examples in other components like button group, chip list, etc.
More info: https://json-schema.org/understanding-json-schema/reference/array.html#id6

2021-11-18 15:19 UTC, colbytcook commented on packages/components/bolt-profile/src/profile.scss
> +  aspect-ratio: 4/1;
In the menu there is a "Reset All to Defaults" that might help. That is the settings I am running.

2021-11-18 15:21 UTC, remydenton commented on packages/components/bolt-profile/src/profile.twig
> +          {% set _item_tag = _item_attributes.type ? 'button' : _item_attributes.href ? 'a' : 'span' %}
As discussed in Slack, I was wrong about the logic, never mind that.  Thanks for the schema update.

2021-11-18 15:23 UTC, mikemai2awesome commented on packages/components/bolt-profile/src/profile.scss
> +  aspect-ratio: 4/1;
No, I am intentionally using aspect ratio to crop the SVG. The full graphic gives me room to play with, so it always fills that space. This is working as intended.

2021-11-18 15:26 UTC, mikemai2awesome commented on packages/components/bolt-profile/src/profile.scss
> +  aspect-ratio: 4/1;
Sorry, misunderstood the question. Let me check this.

2021-11-18 15:39 UTC, colbytcook commented on packages/components/bolt-profile/src/profile.scss
> +  aspect-ratio: 4/1;
no problem, let me know if you need any more info from me or help solving this

2021-11-18 16:24 UTC, mikemai2awesome commented on packages/components/bolt-profile/profile.schema.js
> +      properties: {
Updated.

2021-11-18 16:24 UTC, mikemai2awesome commented on packages/components/bolt-profile/src/profile.scss
> +  aspect-ratio: 4/1;
Fixed.

2021-11-18 17:02 UTC, colbytcook commented on packages/components/bolt-profile/src/profile.scss
> +  aspect-ratio: 4/1;
@mikemai2awesome looks perfect, nice work

2021-11-18 17:02 UTC, colbytcook approved these changes

2021-11-18 17:48 UTC, merged