Background Component Image Update
boltdesignsystem/bolt pull request #2385
Opened 2021-11-17 19:32 UTC by colbytcook

## Summary

Updated the Background Component to use the Image Element instead of the Image Component

## Details

In order to allow for a more performant Hero, we need to remove all the Image Component. On of the steps to do that is to replace the Image Element from the Background Component so we can leverage more perforrmant methods (for example, appending `loading="eager"` to all images in a hero).

## How to test

* Review the code and pull down the branch.
* Review the Bolt Background, and the Bolt Band docs.
* Review the docs "Pages" folder

## Release notes

The Background Component now leverages the Image Element instead of the Image Component. This is a step to create a more performant Hero

2021-11-17 20:43 UTC, mikemai2awesome requested changes

2021-11-17 20:43 UTC, mikemai2awesome commented on packages/components/bolt-background/src/background-item.twig
> +          style: 'object-position: ' ~ _alignment ~ ';'
Use the CSS var we set up rather than this.

2021-11-17 20:43 UTC, mikemai2awesome commented on docs-site/src/pages/pattern-lab/_patterns/40-components/background/05-background.twig
> +        width: 823,
Put in the source image width and height for all of these demos.

2021-11-17 20:43 UTC, mikemai2awesome commented on docs-site/src/pages/pattern-lab/_patterns/40-components/background/05-background.twig
>        }
Add `sizes: '100vw'` for all of these demos because they all take up full width of the viewport.

2021-11-17 22:34 UTC, danielamorse requested changes

2021-11-17 22:34 UTC, danielamorse commented on docs-site/src/pages/pattern-lab/_patterns/40-components/background/05-background.twig
> +        width: 823,
Also noticed that the Band demo has empty `width` and `height` attributes:
![image](https://user-images.githubusercontent.com/36336/142290597-09f36beb-dc99-4931-bcdc-27b61e1ed1d8.png)

2021-11-17 22:34 UTC, danielamorse commented on packages/components/bolt-background/src/background-item.twig
> +      {% set _height = item.height ? item.height : '' %}
Rather than setting these to empty strings, which will output empty attributes, you can do something like this:
```
{# conditional attribute #}
{% if item.srcset %}
  {% set attributes = attributes|merge({ src: item.srcset }) %}
{% endif %}

{% include '@bolt-elements-image/image.twig' with {
  background: true,
  attributes: attributes|merge({
    src: item.src, // unconditional attribute
  })
  ...
```

2021-11-18 12:47 UTC, colbytcook commented on docs-site/src/pages/pattern-lab/_patterns/40-components/background/05-background.twig
>        }
@mikemai2awesome I added this as the default in the background-item.twig on line 27

2021-11-18 13:30 UTC, colbytcook commented on packages/components/bolt-background/src/background-item.twig
> +          style: 'object-position: ' ~ _alignment ~ ';'
This is all set

2021-11-18 13:31 UTC, colbytcook commented on docs-site/src/pages/pattern-lab/_patterns/40-components/background/05-background.twig
> +        width: 823,
width and height values are updated and will no longer show if there are now values

2021-11-18 13:31 UTC, colbytcook commented on packages/components/bolt-background/src/background-item.twig
> +      {% set _height = item.height ? item.height : '' %}
empty attributes will no longer show if there are now values

2021-11-18 14:09 UTC, danielamorse approved these changes

2021-11-18 14:10 UTC, danielamorse commented on packages/components/bolt-background/src/background-item.twig
> +      {% set _height = item.height ? item.height : '' %}
Perfect

2021-11-18 15:20 UTC, mikemai2awesome approved these changes

2021-11-18 18:46 UTC, merged

2021-11-18 20:46 UTC, remydenton commented on packages/components/bolt-background/src/background-item.twig
> +    {% if item.pattern == 'image' %}
This is nicely backwards-compatible, but what's the plan going forward?  As it stands now, you _have_ to pass data as expected by the deprecated image component.  There's no way to do it "right" even if you know better.  Annoying at best, but this may come back to bit us when we try to replace other image components with image elements in Drupal.

Here's a proposal-- what if within `if item.pattern == image`, we have a second check: if there's either a `src` or `srcset` prop, then we assume that the deprecated image component pattern is being used (since those props exist in image component but not image element).  However, if neither of those props is present, we assume the user is actually passing data that's intended to be rendered with the image element.

Thoughts?  We can handle this in a follow up PR.

2021-11-23 00:07 UTC, remydenton commented on packages/components/bolt-background/src/background-item.twig
> +    {% if item.pattern == 'image' %}
Following up on this, I realized we already have this logic at the bottom of this control statement:
```
{% elseif (item is iterable) %}
  <div class="{{ 'c-bolt-background__item' }}">
    {{ item }}
  </div>
{% else %}
  {{ item }}
{% endif %}
```

That allows you to just pass an already rendered (or renderable) item without resorting to the horrible `pattern_template()` design pattern.  That is the preferred option for anyone who wants to use this pattern correctly.  Our schema docs need some updates, but otherwise this is fine as-is.