WWW-1157: iOS modal bug
boltdesignsystem/bolt pull request #2414
Opened 2022-01-06 20:10 UTC by colbytcook

## Jira

https://pegadigitalit.atlassian.net/browse/WWW-1157
https://pegadigitalit.atlassian.net/browse/DS-448

## Summary

Added a new utility class to help solve a iOS scroll bug with the modal, updated the modal CSS for more consistent behavior

## Details

* Added a utility CSS class that will apply a color background directly behind the modal and fix a regression bug with table modals
* Adjusted the modal styling to provide more consistent behavior on iOS Safari

## How to test

TBD

### Visual changes

On iOS Safari there will now be a navy blue background behind the modal, this can be seen by scrolling up (and having the bottom URL bar disappear below the fold). There will be a visible space between the bottom of the modal and the bottom of the screen, this should be now navy blue instead of showing the page content.

2022-01-07 17:04 UTC, mikemai2awesome requested changes

2022-01-07 17:04 UTC, mikemai2awesome commented on packages/global/styles/07-utilities/_utilities-ios-content-fill.scss
> +      .c-bolt-table {
This is very suspicious and I don't understand the comment, and it's not stated in the tickets neither. Again, do we actually have a problem with table since we didn't change to use css grid for modal?

2022-01-07 17:04 UTC, mikemai2awesome commented on packages/components/bolt-modal/src/modal.scss
>    height: 100vh;
Wanna double check one more time, I think ios safari has problem with `vh` specifically. Did you try `height: 100%` instead?

2022-01-07 17:04 UTC, mikemai2awesome commented on packages/global/styles/07-utilities/_utilities-ios-content-fill.scss
> +.u-bolt-ios-content-fill {
This is way too much for a utility class and very specific to modal. I prefer if it's tied to modal instead. This might be an example for data attribute. @danielamorse

2022-01-07 17:09 UTC, mikemai2awesome commented on packages/global/styles/07-utilities/_utilities-ios-content-fill.scss
> +        z-index: bolt-z-index('modal') - 1; // [3]
Please avoid doing math with z-index values from our system. Since modals are rendered at the bottom of `<body>`, they will cover up anything before them even if the same z-index is used, because the modals are higher than the `:before` element in the dom. So i believe this can just be `bolt-z-index('modal')`.

2022-01-07 17:10 UTC, mikemai2awesome commented on packages/global/styles/07-utilities/_utilities-ios-content-fill.scss
> +        bottom: 0;
`bottom: 0` conflicts with `150vh`, i don't think we need it.

2022-01-07 18:16 UTC, colbytcook commented on docs-site/src/pages/pattern-lab/_patterns/999-tests/table/00-table-modal.twig
> +  <bolt-table>
@mikemai2awesome I thought is was originally but when I added the `min-height` bit to the CSS it seemed to solve it by itself, so I reverted the `grid` back to soo owe didn't introduce any regressions.

2022-01-07 18:16 UTC, colbytcook commented on packages/components/bolt-modal/src/modal.js
> +  window.matchMedia('(max-width: 37.5em)') &&
I agree, I will update this.

2022-01-07 18:43 UTC, colbytcook commented on packages/components/bolt-modal/src/modal.js
> +  window.matchMedia('(max-width: 37.5em)') &&
@mikemai2awesome When I wrote this logic I did look around in the code base and found only two examples, `bolt-holy-grail` and the `bolt-page-header`, both of which are using hard coded values. 

@danielamorse do you have any insights here? Do we have examples of the JS using any of the values in a break point map (just so I use the existing patterns)? Or even the JS using any existing data maps (I did look but did not find any but maybe I was not looking for the right thing)? If not, I can spend some time to get this to work with the breakpoint map.

2022-01-07 18:45 UTC, colbytcook commented on packages/global/styles/07-utilities/_utilities-ios-content-fill.scss
> +.u-bolt-ios-content-fill {
@mikemai2awesome this is exactly why I called this one out in the stand up, I had the same feeling that it is very  closely tied to the modal and should live there but it is placed on the body which seems odd. 

@danielamorse what is your opinion on this?

2022-01-07 19:42 UTC, colbytcook commented on packages/global/styles/07-utilities/_utilities-ios-content-fill.scss
> +        bottom: 0;
@mikemai2awesome removed, I confirmed we don't need it (it wasn't breaking it but it was redundant). Good catch.

2022-01-07 19:43 UTC, colbytcook commented on packages/global/styles/07-utilities/_utilities-ios-content-fill.scss
> +        z-index: bolt-z-index('modal') - 1; // [3]
@mikemai2awesome updated

2022-01-07 19:50 UTC, colbytcook commented on packages/components/bolt-modal/src/modal.scss
>    height: 100vh;
@mikemai2awesome double checked again, I think safari has an issue with scrolling and `vh` and not `vh` specifically (`%` will at least attempt to re paint itself when the URL bar hides, `vh` does nothing). In this fix we need the modal to do nothing and remain the same height (both `vh` and `-webkit-fill-available` do this). While `%` does seem to work I would again rather only change CSS if is pertains too the bug fix here, `height: 100%` doesn't really do anything different than `height: 100vh` already does in this case.

2022-01-10 20:42 UTC, mikemai2awesome approved these changes
Approving. But feels weird to use a component class on the body, thoughts, @danielamorse?

2022-01-13 13:07 UTC, colbytcook commented
@danielamorse I updated this PR based on our conversation, the color overlay is now scoped to the `bolt-modal[open]` attribute, removed the breakpoints from the`modal.js`, the utility class is not removed and refactored the modal docs  to remove all examples of a modal nested inside a table since it is not supported anymore.

@mikemai2awesome please take a look at the update modal docs and let me know if you have any suggestions on improving them (I based the UI on the elements page structure).

2022-01-14 17:13 UTC, mikemai2awesome requested changes

2022-01-14 17:13 UTC, mikemai2awesome commented on docs-site/src/pages/pattern-lab/_patterns/40-components/modal/25-modal-scroll-variations.twig
> +  content: 'This is a modal set to overall scrolling.',
We should note when doing an image modal, you can set `spacing` and `theme` to none to show only the image.

2022-01-14 17:13 UTC, mikemai2awesome commented on docs-site/src/pages/pattern-lab/_patterns/40-components/modal/30-modal-trigger-variations.twig
> +  demo: demo,
This is missing code snippets. And the image modal is broken, the modal is still taking full width of screen instead of the width of the image.

2022-01-14 20:57 UTC, danielamorse approved these changes
@mikemai2awesome @colbytcook updated the CSS to leverage the existing overlay, [see commit](https://github.com/boltdesignsystem/bolt/pull/2414/commits/f07b207865725cac0918199e29c47d0251df20a7).

2022-01-18 16:31 UTC, colbytcook commented on docs-site/src/pages/pattern-lab/_patterns/40-components/modal/30-modal-trigger-variations.twig
> +  demo: demo,
@mikemai2awesome I am seeing this bug in Safari, but it seems like it is an existing bug (https://boltdesignsystem.com/pattern-lab/?p=components-modal-trigger-variations). I will spend sometime trying to fix this. If not, I will create a bug ticket to handle this another time.

2022-01-18 18:45 UTC, colbytcook commented on docs-site/src/pages/pattern-lab/_patterns/40-components/modal/30-modal-trigger-variations.twig
> +  demo: demo,
@mikemai2awesome I created https://pegadigitalit.atlassian.net/browse/DS-699 to track this. I was not able to track down what was causing this bug.

2022-01-21 16:54 UTC, mikemai2awesome approved these changes

2022-01-21 19:26 UTC, merged