DS-517 Type element
boltdesignsystem/bolt pull request #2415
Opened 2022-01-11 21:52 UTC by mikemai2awesome

## Jira

https://pegadigitalit.atlassian.net/browse/DS-517

## Summary

Adds a new Type element that will replace both Text and Headline components.

## Details

The element has a set of typographic styles that can be controlled via props. Twig and plain HTML usage are supported. Note that it is named `Type` to avoid Pattern Lab conflicts with the Text component.

## How to test

Run the branch locally and go through all docs under Elements > Type.

2022-06-23 16:57 UTC, remydenton requested changes

2022-06-23 16:57 UTC, remydenton commented on packages/elements/bolt-type/src/type.twig
> +    {% if icon_before %}<span class="e-bolt-type__icon-before" aria-hidden="true">{{ icon_before|spaceless }}</span>{% endif %}{{ this.data.content.value|spaceless }}{% if icon_after %}<span class="e
Why `this.data.content.value` and not just `content`?  I think we want to follow the example of text link element, which just does [content|spaceless](https://github.com/boltdesignsystem/bolt/blob/master/packages/elements/bolt-text-link/src/text-link.twig#L33).  Otherwise, we'll run into issues when someone wants to pass something that isn't a string, like a renderable object.

2022-06-23 16:57 UTC, remydenton commented on packages/elements/bolt-type/type.schema.js
> +      type: 'string',
Same idea as my other comment, this should probably be
```suggestion
      type: 'any',
```

2022-06-23 19:38 UTC, mikemai2awesome commented on packages/elements/bolt-type/src/type.twig
> +    {% if icon_before %}<span class="e-bolt-type__icon-before" aria-hidden="true">{{ icon_before|spaceless }}</span>{% endif %}{{ this.data.content.value|spaceless }}{% if icon_after %}<span class="e
updated

2022-06-24 18:31 UTC, remydenton approved these changes

2022-06-24 22:17 UTC, danielamorse reviewed
@mikemai2awesome this looks great 😎 

Only remaining issue is the schema isn't showing in the docs. At first glance, everything looks correct. I will have to debug more on Monday.

2022-06-24 22:17 UTC, danielamorse commented on docs-site/src/pages/pattern-lab/_patterns/20-elements/type/05-type.twig
> +  description: 'The type element displays text in Pega branded typographic styles.',
Should we just say "branded typographic styles" to avoid mention of "Pega"?

2022-06-27 19:58 UTC, mikemai2awesome commented on docs-site/src/pages/pattern-lab/_patterns/20-elements/type/05-type.twig
> +  description: 'The type element displays text in Pega branded typographic styles.',
I think it's only `pega.com` that's problematic.

2022-06-27 21:08 UTC, danielamorse commented
Schema issue fixed in https://github.com/boltdesignsystem/bolt/pull/2499. Will merge once next build passes.

2022-06-28 12:56 UTC, cjwhitedev approved these changes

2022-06-28 15:29 UTC, merged