Feature/ds 541 floating action buttons
boltdesignsystem/bolt pull request #2423
Opened 2022-01-21 16:18 UTC by cjwhitedev

## Jira

- [DS-541](https://pegadigitalit.atlassian.net/browse/DS-541)
- [DS-540](https://pegadigitalit.atlassian.net/browse/DS-540)

## Summary

Create a component for floating action buttons.

## Details

This is a component to add floating action buttons, with options to change position.

## How to test

1. Pull Down the Branch and update.
2. Check out the demo pages.

## Release notes

New Bolt-Satellite Component.

2022-01-21 21:07 UTC, mikemai2awesome requested changes
@cjwhitedev This is a good first pass. First, let's keep this simple and just name this Floating Action Buttons rather than a fancy term that doesn't resonate.

Secondly, let's go over some visual enhancements and semantics fixes.

## Visual

Let's create some information hierarchy here. If the more button toggles on additional buttons, these would be considered secondary. Rough sketch below:

![fab](https://user-images.githubusercontent.com/3027663/150598762-de0ea67a-5132-4f52-9aa9-b7f9f6252f6e.gif)

Additionally, it'd be great to smooth out the transition with some motion effects [like this](https://codepen.io/th3no0b/pen/ZvVMZe).

## Semantics

This is a list of buttons, let's apply the correct semantics in the markup.

```html
<ul>
  <li>
    <a href="">more</a>
    <ul>
      <li>
        <a href="">
          rocket
        </a>
      </li>
      <li>
        <a href="">
          rocket
        </a>
      </li>
      <li>
        <a href="">
          rocket
        </a>
      </li>
    </ul>
  </li>
  <li>
    <a href="">share</a>
  </li>
  <li>
    <a href="">scroll to top</a>
  </li>
</ul>
```

2022-01-21 21:07 UTC, mikemai2awesome commented on packages/components/bolt-satellite/satellite.schema.js
> +    position: {
We are lacking offset options to move this out of the way when there are sticky things on the page that's out of our control, such as Chatbot button and Cookie Consent panel.

Also, let's keep out testing things out of our schemas.

2022-01-25 15:07 UTC, cjwhitedev commented on packages/components/bolt-satellite/satellite.schema.js
> +    position: {
@mikemai2awesome 

1. There is a CSS var to control the offset. Should it be a prop instead?
2. How can I use it in the demos if its not in the schema?

2022-01-25 16:38 UTC, mikemai2awesome commented on packages/components/bolt-satellite/satellite.schema.js
> +    position: {
@cjwhitedev You can document it similar to [what we did with Image](https://boltdesignsystem.com/pattern-lab/?p=elements-image-use-case-background-fit-and-position). Have a dedicated page for advanced usage.

2022-01-28 19:20 UTC, cjwhitedev commented on packages/components/bolt-satellite/satellite.schema.js
> +    position: {
@mikemai2awesome I believe I've hit every point here. Please re-review this PR.

2022-02-02 19:46 UTC, danielamorse requested changes
@cjwhitedev This is really coming together. Almost there! I left you some inline comments.

Another thought - In our demos maybe we should position tooltips to the left when FAB is vertical so that the tooltip doesn't block the button above?

![image](https://user-images.githubusercontent.com/36336/152225634-97ade68d-4431-4ccc-9e83-c30d9a0a3651.png)

2022-02-02 19:46 UTC, danielamorse commented on packages/components/bolt-floating-action-buttons/src/floating-action-buttons.js
> +    this.visibleItems = this.el.getAttribute('data-visible-items');
From JS use: `this.el.dataset.visibleItems`

https://developer.mozilla.org/en-US/docs/Learn/HTML/Howto/Use_data_attributes

2022-02-02 19:46 UTC, danielamorse commented on packages/components/bolt-floating-action-buttons/src/floating-action-buttons.js
> +    this.showOnLoad = this.el.getAttribute('data-show-on-load');
Ditto, use `dataset`

2022-02-02 19:46 UTC, danielamorse commented on packages/components/bolt-floating-action-buttons/src/floating-action-buttons.js
> +    } else if (this.showOnLoad != null) {
The `null` check is probably unnecessary here, just `!this.showOnLoad` should do.

2022-02-02 19:46 UTC, danielamorse commented on packages/components/bolt-floating-action-buttons/src/floating-action-buttons.js
> +      this.handleshowOnScroll();
Fix camelcase, should be `handleShowOnScroll`.

2022-02-02 19:46 UTC, danielamorse commented on packages/components/bolt-floating-action-buttons/src/floating-action-buttons.js
> +        this.toggleShowMore();
Do "expandButton" and "showMore" refer to the same piece of UI? If so, let's use the same name for both. This makes me think they are two separate things.

2022-02-02 19:46 UTC, danielamorse commented on packages/components/bolt-floating-action-buttons/src/floating-action-buttons.js
> +    }, 200);
What exactly does this fix? What animation lag happens without a delay?

2022-02-02 19:46 UTC, danielamorse commented on packages/components/bolt-floating-action-buttons/src/floating-action-buttons.js
> +    var revealPosition = 0;
Use `let`/`const`

2022-02-02 19:46 UTC, danielamorse commented on packages/components/bolt-floating-action-buttons/src/floating-action-buttons.js
> +    var scrollPosition = window.scrollY;
Use `let`/`const`

2022-02-02 19:46 UTC, danielamorse commented on packages/components/bolt-floating-action-buttons/src/floating-action-buttons.js
> +    return revealPosition;
Nice way to handle `px`/`%`

2022-02-02 19:46 UTC, danielamorse commented on packages/components/bolt-floating-action-buttons/src/floating-action-buttons.js
> +    const superFunction = () => {
`superFunction` is fun, but `scrollHandler` is more descriptive.

2022-02-02 19:46 UTC, danielamorse commented on packages/components/bolt-floating-action-buttons/src/floating-action-buttons.js
> +      for (const contentItem of this.contentElement.children) {
I wouldn't use `children`. I would add a querySelector to `init()` that finds these elements based on classname. Use a `js-` classname [per the convention](https://gitlab.com/pegadigital/pega-digital-standards-and-conventions/-/wikis/Standards-Naming#front-end-examples).

2022-02-02 19:46 UTC, danielamorse commented on packages/components/bolt-floating-action-buttons/src/floating-action-buttons.js
> +        contentItem.setAttribute('aria-hidden', false);
Should this be 'false'?

2022-02-02 19:46 UTC, danielamorse commented on packages/components/bolt-floating-action-buttons/src/floating-action-buttons.js
> +        contentItem.setAttribute('aria-hidden', true);
Ditto, 'true'?

2022-02-02 19:46 UTC, danielamorse commented on packages/components/bolt-floating-action-buttons/src/floating-action-buttons.js
> +        contentItem.setAttribute('aria-hidden', false);
Ditto, 'false'?

2022-02-02 19:46 UTC, danielamorse commented on packages/components/bolt-floating-action-buttons/src/floating-action-buttons.js
> +    for (const contentItem of this.contentElement.children) {
See comment above about using a `js-` selector to find the children. Then, try using `map()` here. Map is good when you want to perform an operation on each item of an array. Let me know if you have any questions refactoring.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/map

2022-02-02 19:59 UTC, mikemai2awesome commented
@cjwhitedev The markup still doesn't make sense, let's try again.

**Currently this:**
```
<div class="c-bolt-floating-action-buttons c-bolt-floating-action-buttons--position-bottom-right" aria-hidden="false" aria-expanded="true" data-visible-items="2" data-show-on-load="" data-bolt-ready="">
  <ul class="c-bolt-floating-action-buttons__content">
    <li class="c-bolt-floating-action-buttons__content-item">
      <button type="button" class="e-bolt-button e-bolt-button--icon-only" aria-label="Share"></button>
    </li>
    <li class="c-bolt-floating-action-buttons__content-item">
      <button type="button" class="e-bolt-button e-bolt-button--icon-only" aria-label="Back to top"></button>
    </li>
    <li class="c-bolt-floating-action-buttons__content-item">
      <button type="button" class="e-bolt-button e-bolt-button--icon-only" aria-label="Secondary"></button>
    </li>
    <li class="c-bolt-floating-action-buttons__content-item">
      <button type="button" class="e-bolt-button e-bolt-button--icon-only" aria-label="Secondary"></button>
    </li>
    <li class="c-bolt-floating-action-buttons__content-item">
      <button type="button" class="e-bolt-button e-bolt-button--icon-only" aria-label="Secondary"></button>
    </li>
  </ul>
  <div class="c-bolt-floating-action-buttons__more">
    <button type="button" class="e-bolt-button e-bolt-button--icon-only" aria-label="More"></button>
  </div>
</div>
```

**What we want to get to is this:**
```html
<div class="c-bolt-floating-action-buttons c-bolt-floating-action-buttons--position-bottom-right" aria-hidden="false" data-visible-items="2" data-show-on-load data-bolt-ready>
  <ul class="c-bolt-floating-action-buttons__list">
    <li class="c-bolt-floating-action-buttons__list-item">
      <button type="button" class="e-bolt-button e-bolt-button--icon-only" aria-label="Share"></button>
    </li>
    <li class="c-bolt-floating-action-buttons__list-item">
      <button type="button" class="e-bolt-button e-bolt-button--icon-only" aria-label="Back to top"></button>
    </li>
    <li class="c-bolt-floating-action-buttons__list-item">
      <button type="button" class="e-bolt-button e-bolt-button--icon-only" aria-label="More" aria-expanded="false"></button>
      <ul class="c-bolt-floating-action-buttons__list">
        <li class="c-bolt-floating-action-buttons__list-item">
          <button type="button" class="e-bolt-button e-bolt-button--icon-only" aria-label="Secondary"></button>
        </li>
        <li class="c-bolt-floating-action-buttons__list-item">
          <button type="button" class="e-bolt-button e-bolt-button--icon-only" aria-label="Secondary"></button>
        </li>
        <li class="c-bolt-floating-action-buttons__list-item">
          <button type="button" class="e-bolt-button e-bolt-button--icon-only" aria-label="Secondary"></button>
        </li>
      </ul>
    </li>
  </ul>
</div>
```

`aria-expanded` is to be used on a `<button>` not a `<div>`. Also reference my rough design previously, when "more" is clicked on to expand, the ellipsis changes to an X.

2022-02-03 17:55 UTC, cjwhitedev commented on packages/components/bolt-floating-action-buttons/src/floating-action-buttons.js
> +    } else if (this.showOnLoad != null) {
as far as i can tell, `dataset` (or getAttribute) doesn't translate to booleans. the attribute is either there or it isn't. is there another way to approach this?

2022-02-03 18:19 UTC, cjwhitedev commented on packages/components/bolt-floating-action-buttons/src/floating-action-buttons.js
> +    }, 200);
Without the delay, on page load we can see the component for a moment before it hides itself. With the delay, the CSS animations happen behind the scenes for that .2 second before it becomes visible. Is there a better way to do this because I don't feel great about it as-is.

2022-02-03 18:35 UTC, cjwhitedev commented on packages/components/bolt-floating-action-buttons/src/floating-action-buttons.js
> +      for (const contentItem of this.contentElement.children) {
@danielamorse does it need the js-if there is an existing class name to target? look at `this.contentElement` in this file to see what I mean.

2022-02-03 18:59 UTC, cjwhitedev commented on packages/components/bolt-floating-action-buttons/src/floating-action-buttons.js
> +        contentItem.setAttribute('aria-hidden', false);
I don't think so - setting hidden to true would mean they are hidden, wouldn't it? I'm trying to show all the items here.

2022-02-03 18:59 UTC, cjwhitedev commented on packages/components/bolt-floating-action-buttons/src/floating-action-buttons.js
> +        contentItem.setAttribute('aria-hidden', true);
see above

2022-02-08 16:15 UTC, danielamorse commented on packages/components/bolt-floating-action-buttons/src/floating-action-buttons.js
> +      for (const contentItem of this.contentElement.children) {
Yes, we use `js-` as a way of saying "JS depends upon this class". It's more verbose but clearer and harder to break.

2022-02-08 16:16 UTC, danielamorse commented on packages/components/bolt-floating-action-buttons/src/floating-action-buttons.js
> +        contentItem.setAttribute('aria-hidden', false);
I meant `'false'` vs `false`, string vs Boolean.

2022-02-08 16:25 UTC, danielamorse commented on packages/components/bolt-floating-action-buttons/src/floating-action-buttons.js
> +    for (const contentItem of this.contentElement.children) {
Oh you are totally right. I think [forEach](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/forEach) is better here. You get the `index` automatically as the second arg.

2022-02-16 21:35 UTC, mikemai2awesome requested changes
@cjwhitedev Great job setting up the list structure. I have some inline comments and the following:

## Transition

1. The transition of the children action buttons are a bit choppy, might have to do with using `margin` which costs more than `transform`. Consult our animation expert @MarcinMr on improving this.
2. The button element tooltip transition is not working that well, you can see it in the icon only button doc page, sometimes the tooltip doesn't trigger at all (in Safari). Again, consult Marcin about this.
3. `show_on_scroll` needs fade in and fade out transitions.
4. Remove transitions when `@media (prefers-reduced-motion) {}` is true.

## Hidden

`aria-hidden` is supposed to be used for hiding things from just screen readers, which doesn't really apply to what we are doing with this component, because we are hiding things entirely. We shouldn't need to write css based on `aria-hidden`.

For the main container, you can toggle a `--hidden` modifier class when `show_on_scroll` is set.

For the toggle button, you handle the css with just `aria-expanded`:

```css
.e-bolt-button[aria-expand='false'] ~ .c-bolt-floating-action-buttons__list > .c-bolt-floating-action-buttons__list-item  {
  // hide the list items
}
```

2022-02-16 21:35 UTC, mikemai2awesome commented on packages/components/bolt-floating-action-buttons/src/floating-action-buttons.scss
> +  .c-bolt-floating-action-buttons__toggle[aria-expanded='false']
By removing the `.c-bolt-floating-action-buttons__toggle` class, you can just use `e-bolt-button` here.

2022-02-16 21:35 UTC, mikemai2awesome commented on packages/components/bolt-floating-action-buttons/src/floating-action-buttons.scss
> +  .c-bolt-floating-action-buttons__toggle-icon {
Also remove this class, we can use `nth-child` instead to handle the 2 icons. We should avoid mixing component classes with another component/element class.

2022-02-16 21:35 UTC, mikemai2awesome commented on packages/components/bolt-floating-action-buttons/src/floating-action-buttons.scss
> +    @include bolt-visuallyhidden;
When it's hidden, it needs to be completely hidden, not visually hidden. You should not be able to tab to these buttons if they are hidden.

2022-02-17 16:28 UTC, danielamorse requested changes
@cjwhitedev I took another pass through and left comments.

2022-02-17 16:28 UTC, danielamorse commented on packages/components/bolt-floating-action-buttons/src/floating-action-buttons-toggle-button.twig
> +<button
Is there a particular reason we're using HTML here and not the Button element Twig template? If it's to add a class somewhere the template doesn't allow can we explain that in a comment please?

2022-02-17 16:28 UTC, danielamorse commented on packages/elements/bolt-button/button.schema.js
> +    icon_only_tooltip: {
When you're ready to look at this one, let's have a quick call @cjwhitedev. I need to get up to speed.

2022-02-17 18:52 UTC, cjwhitedev commented on packages/components/bolt-floating-action-buttons/src/floating-action-buttons.scss
> +  .c-bolt-floating-action-buttons__toggle-icon {
@mikemai2awesome I was just trying this out and was running into an issue where it was hidding the children in the buttons i dont want it to. i think if we were to keep the `toggle` class from above this would be more feasible. Do you have thoughts on an alternate approach?

2022-02-18 19:04 UTC, mikemai2awesome commented on packages/components/bolt-floating-action-buttons/floating-action-buttons.schema.js
> +      default: true,
that sounds reasonable, then we'd need to follow our convention of boolean defaults to `false`. something like `hide_on_load`. @danielamorse @cjwhitedev 

let's say we are to do that, i think having 2 props to achieve one thing is kind of excessive:

```
{
  hide_on_load: true,
  show_on_scroll: '20%',
}
```

2022-02-18 21:04 UTC, mikemai2awesome commented on packages/components/bolt-floating-action-buttons/src/floating-action-buttons.scss
> +    @include bolt-visuallyhidden;
The different ways of hidden as discussed in our chat:

```
html:
aria-hidden="true" -> hide only from screen readers
hidden -> hide completely

css:
bolt-visuallyhidden -> hide only from visual
display: none -> hide completely
visibility: hidden -> hide completely but takes up space
opacity: 0 -> hide only from visual but takes up space
```

To hide/show the main container, it requires css `visibility: hidden` and `opacity` already, other methods are not to be used.

2022-02-18 21:05 UTC, mikemai2awesome commented on packages/components/bolt-floating-action-buttons/src/floating-action-buttons.scss
> +  .c-bolt-floating-action-buttons__toggle-icon {
As discussed in our chat, using the `children` prop as the logic to render a modifier class for the list item will allow us to not write additional classes on the button.

2022-02-18 21:06 UTC, mikemai2awesome commented on packages/components/bolt-floating-action-buttons/src/floating-action-buttons.scss
> +  .c-bolt-floating-action-buttons__toggle[aria-expanded='false']
As discussed in our chat, using the children prop as the logic to render a modifier class for the list item will allow us to not write additional classes on the button.

2022-03-01 11:56 UTC, MarcinMr commented
@mikemai2awesome @cjwhitedev I did an example of the children's btns animation. Had to change js for testing purposes, this might need to be refactored, didn't make cascade variables dynamic, but hardcoded at this moment in CSS as I don't know if this is what we are looking for.

2022-03-08 17:08 UTC, mikemai2awesome requested changes
@cjwhitedev As we discussed over chat, here are the things to look into:

1. The component needs to work without JS (the toggle button requires JS to expand/collapse, but we cannot hide the entire thing due to 1 button, similar to page header, it still appears without JS but the mega nav expand/collapse function is not expected to work).
2. Based on 1, the component should not have a hidden class by default.
3. The JS doesn't boot if a toggle button is not passed to the component (eg. passing only the "back to top" button and share button).
4. The JS hangs on every few refresh. Reproduce this by refreshing the page a few times till you hit one that doesn't load ready data attribute.
5. The `right-start` placement option does not account for the sticky page header, I've added a CSS hack for now. Figure out how to do it properly with Dan.

I am going to wrap up the following:

1. Animate the toggle button's icons.
2. Finish reformatting the docs.

cc @danielamorse

2022-03-21 21:22 UTC, mikemai2awesome commented
@cjwhitedev This is working great now. We have `show_on_scroll`, but how can we hide the FAB again if user scrolls back up? The scroll to top button on Collaboration Center fades away when user [scrolls back up](https://collaborate.pega.com/question/database-commit-operation-slow-after-oracle-19c-upgrade), we need to cover this use case.

2022-04-07 19:46 UTC, danielamorse requested changes
@cjwhitedev left a few inline requests. Please also update demo titles and description to reflect the new prop name (still see examples of "show-on-scroll-position"), and remember to prefix commit messages with the ticket number 🙏

2022-04-07 19:46 UTC, danielamorse commented on packages/components/bolt-floating-action-buttons/src/floating-action-buttons.js
> +    observer.observe(document.querySelector(el.dataset.showOnScrollSelector));
Assign `document.querySelector(el.dataset.showOnScrollSelector)` to a variable and check for it at the very top of this function. If it's not present `return`.

2022-04-07 19:46 UTC, danielamorse commented on packages/components/bolt-floating-action-buttons/src/floating-action-buttons.js
> +    this.hiddenListItems = this.el.querySelectorAll(
Instead of using the presence of the hidden class, use the show on scroll data attribute.

2022-04-15 13:44 UTC, danielamorse approved these changes
@cjwhitedev approved! 🎉  Thanks for sticking with this one. I think it turned out great.

I made two last tweaks. One is a very minor JS style thing - I tend to skip brackets for single-line `if` statement. It's totally fine to include brackets (some prefer that), but for consistency I removed them ([see commit](https://github.com/boltdesignsystem/bolt/pull/2423/commits/d13f397c18f337ebec9eb0e6fa79ad88eaa97117)). Second, I removed the remaining scroll-position demos ([see commit](https://github.com/boltdesignsystem/bolt/pull/2423/commits/5d2983ccd0712c40d1470d523ce09961bc87fd14)).

Before merging I just want to double-check this has Mike's approval. I think he approved before many recent changes.

2022-04-15 15:44 UTC, mikemai2awesome approved these changes
@danielamorse @cjwhitedev I fixed some docs and tested with screen readers. Good to go.

2022-04-15 18:40 UTC, merged