[DO NOT MERGE] Remove Nightwatch
boltdesignsystem/bolt pull request #2429
Opened 2022-01-31 20:41 UTC by colbytcook

## Jira

https://pegadigitalit.atlassian.net/browse/DS-690

## Summary

Removed Nightwatch from the build.

## Details

* Removed Nightwatch tasks from the main `package.json` file
* Removed the Nightwatch tasks from the `travis.xml` file
* Deleted all the `.e2e.js` files within the `/packages/components` folder
* Removed Nightwatch dependencies
* Removed the `packages/testing/ttesting-nightwatch` folder

## How to test

TBD

2022-03-10 02:49 UTC, danielamorse approved these changes
@colbytcook this looks great. The main things I wanted to confirm were 1) There were no more Nightwatch remnants (none found) 2) There were no unnecessary Travis build steps once Nightwatch was removed (looks good!).

Good to merge once conflicts are resolved and passing on Travis 🚀

2022-03-10 15:24 UTC, adamszalapski requested changes
I noticed that in `.gitignore` we have some info about nightwatch
```
# nightwatch.js test results when run locally
/tests_output/**
tests_output
```

2022-03-10 15:24 UTC, adamszalapski commented on jest.config.js
> +  // 'packages/components/**/*.e2e.js',
I suggest removing this line 4 and 5, and we should check if all e2e and no2e files are removed from the repo.

2022-03-10 18:45 UTC, remydenton approved these changes
The code here looks good to me.

I think I missed the convo where we decided to remove Nightwatch though.  Regarding thd description in JIRA the ticket:

> Since we have a QA team that is performing end to end testing...

Do we actually have a QA team doing that in Bolt?  And even if so, do they have the time to be as thorough as an automated test suite?

I trust you guys have already thought about this and made the right call, just noting here that these kinds of tests can indeed provide value.

2022-03-14 17:46 UTC, colbytcook commented on .travis.yml
> +        # - travis_retry yarn run test:e2e:full
@adamszalapski this has been updated

2022-03-14 17:46 UTC, colbytcook commented on .travis.yml
> +        # - travis_retry yarn run test:e2e:full
@adamszalapski this has been updated

2022-03-14 20:46 UTC, adamszalapski approved these changes

2022-03-14 20:47 UTC, merged