DC-337: Video Thumbnail Inline Play Functionality
boltdesignsystem/bolt pull request #2451
Opened 2022-03-15 15:00 UTC by colbytcook

## Jira

https://pegadigitalit.atlassian.net/browse/DC-337

## Summary

* Modified the Video Thumbnail component to handle both inline and modal video support.
* Adds a subtitle icon indicator.

## Details

* Refactored the Video Thumbnail schema to handle the new inline functionality option.
* Added `subtitles` and `video` props to  the schema.
* Added a inline video doc page.
* Updated all instances of the Video Thumbnail Component to include a `video.video_title` prop in the doc site.
* [WORK IN PROGRESS] Added Jest tests to the Video Thumbnail Component.

## How to test

* Review the code
* Pull down the branch
* Review the Video Thumbnail docs (a lot has changed within this section)

## Release notes

* Video Thumbnail Component now has a inline video option.
* Added a `subtitles` prop to the Video Thumbnail components. This prop will render a subtitles icon with a "Subtitles available" tooltip to a video thumbnail component.
* Added a `video` prop to the Video Thumbnail components. This prop will give a content author the ability to play videos inline.

2022-03-18 21:02 UTC, remydenton commented on packages/components/bolt-video-thumbnail/src/video-thumbnail.twig
> +            content: 'Subtitles'
Don't forget to add a |t here: `'Subtitles'|t`

2022-03-22 15:02 UTC, remydenton commented on packages/components/bolt-video-thumbnail/video-thumbnail.schema.js
> +    subtitles: {
Naming nitpick, change the naming of `subtitles` to `has_subtitles`.

This isn't a convention we've followed elsewhere, but honestly we should.  It's general programming naming convention for booleans (see, for example, https://www.serendipidata.com/posts/naming-guidelines-for-boolean-variables).  "Subtitles" is especially confusing here because it sounds like maybe you should be passing the subtitles themselves.

2022-03-22 19:42 UTC, mikemai2awesome requested changes
@colbytcook As we discussed in a call, let's update the inline video player version.

1. Reduce to just one focusable area which is the entire thumbnail. Tooltip for subtitles icon will appear on hover and focus state of this area. This area needs a visible focus outline (`outline: var(--bolt-focus-ring);`) and to reset button styles there is a mixin (`bolt-button-native-styles-reset`).
2. Make sure the entire thumbnail is clickable, any UI inside (subtitles icon, duration, etc.) should not block it.

2022-03-22 19:59 UTC, mikemai2awesome requested changes

2022-03-22 19:59 UTC, mikemai2awesome commented on packages/components/bolt-video-thumbnail/src/video-thumbnail.scss
> +.c-bolt-video-thumbnail__content__inline {
Let's just update this to `.c-bolt-video-thumbnail__content-video`. Set `display: none` so screen reader can't reach the hidden video embed until the button is clicked to reveal it.

2022-03-22 19:59 UTC, mikemai2awesome commented on packages/components/bolt-video-thumbnail/src/video-thumbnail.scss
> +.js-bolt-video-thumbnail__inline-play {
Cannot style JS classes, this would be `.c-bolt-video-thumbnail__inline-play-button`. To target it with JS, that would be a separate JS class.

2022-03-22 19:59 UTC, mikemai2awesome commented on packages/components/bolt-video-thumbnail/src/video-thumbnail.js
> +      .closest('.js-bolt-video-thumbnail__inline-play__target')
No BEM for JS classes. Just dash case.

2022-03-22 19:59 UTC, mikemai2awesome commented on packages/components/bolt-video-thumbnail/src/video-thumbnail.js
> +      '.js-bolt-video-thumbnail__inline-play',
No BEM for JS classes. Just dash case.

2022-03-22 19:59 UTC, mikemai2awesome commented on packages/components/bolt-video-thumbnail/src/video-thumbnail.twig
> +  <div class="c-bolt-video-thumbnail__content js-bolt-video-thumbnail__inline-play__target">
No BEM for JS classes. Just dash case.

2022-03-24 18:01 UTC, mikemai2awesome requested changes

2022-03-25 12:18 UTC, colbytcook commented on packages/components/bolt-video-thumbnail/src/video-thumbnail.twig
> +            content: 'Subtitles'
@remydenton updated

2022-03-25 12:18 UTC, colbytcook commented on packages/components/bolt-video-thumbnail/src/video-thumbnail.twig
> +        content: 'Play the video',
@remydenton updated

2022-03-25 12:18 UTC, colbytcook commented on packages/components/bolt-video-thumbnail/src/video-thumbnail.js
> +      .querySelector('.c-base-video')
Updated

2022-03-25 12:18 UTC, colbytcook commented on packages/components/bolt-video-thumbnail/src/video-thumbnail.scss
> +}
@remydenton updated

2022-03-25 12:18 UTC, colbytcook commented on packages/components/bolt-video-thumbnail/video-thumbnail.schema.js
> +    subtitles: {
@remydenton updated

2022-03-25 12:26 UTC, colbytcook commented on packages/components/bolt-video-thumbnail/video-thumbnail.schema.js
> +    video_title_display: {
@mikemai2awesome due to the accessibility needs the video.title is required (the title can be automatically fed into the component from Drupal). The video_title_display is different in that it is an optional display that adds a title chip, you see this behavior [here](https://boltdesignsystem.com/pattern-lab/?p=components-video-thumbnail-title-and-chips). The video.title will be fed into the title chip and the aria-label for the button automatically. 

So to summarize, the title (video.title) is required and will always be passed in but the title chip (video_title_display) is an optional visual display type that needs separate prop control for content authors. Let me know if you have anymore questions/suggestions on this.

2022-03-25 12:27 UTC, colbytcook commented on packages/components/bolt-video-thumbnail/video-thumbnail.schema.js
> +        video_title: {
@mikemai2awesome updated

2022-03-25 12:27 UTC, colbytcook commented on packages/components/bolt-video-thumbnail/src/video-thumbnail.twig
> +  {% if chip or video_title_display %}
@mikemai2awesome see comment above

2022-03-25 17:02 UTC, remydenton commented on packages/components/bolt-video-thumbnail/video-thumbnail.schema.js
> +      default: false,
I think it's the right thing to do to have this be hidden by default.

Currently, there are asset injectors that hide this title with CSS where it's not wanted, e.g. https://www.pega.com/admin/config/development/asset-injector/css/suppress_video_meta_title.  But I believe that is that majority of the time, so I think it's better to hide it by default, and add an option to the UI to display it in the (relatively rare) cases that's desired.

2022-03-25 17:14 UTC, remydenton commented on packages/components/bolt-video-thumbnail/src/video-thumbnail.twig
> +    <button {{ button_attributes.addClass('c-bolt-video-thumbnail__inline-button')|without('aria-label')|without('type') }} type="button" aria-label="{{ play_video_label|t }}">
`|t `doesn't work with a variable; you should instead use it on a literal string.  More info at https://www.drupal.org/docs/7/api/localization-api/localization-api-overview#s-introduction-to-interface-translation-in-drupal

In short, t should be used earlier on when you first declare the string:
```
{% set play_video_label = 'Play the video'|t %}
```

2022-03-25 18:59 UTC, mikemai2awesome approved these changes

2022-03-25 19:03 UTC, danielamorse approved these changes
@colbytcook updated the JS as we discussed.

2022-03-25 20:42 UTC, remydenton approved these changes

2022-03-28 14:32 UTC, mikemai2awesome approved these changes

2022-03-28 15:37 UTC, merged