Ds-602 Remove pattern template function
boltdesignsystem/bolt pull request #2478
Opened 2022-04-14 09:11 UTC by MarcinMr

## Jira

https://pegadigitalit.atlassian.net/browse/DS-602

## Summary

Pattern_template function and its usage were deleted from the Bolt repository.

## Details

All the examples of the `pattern_template` function in use in the Bolt repository (components and patternlab) are removed.

## How to test

Pull the branch.  Search for examples of `pattern_template` usage, confirm that there is no regression due to removing that function.

## Release notes

Patter_template function is deleted.

2022-04-15 16:58 UTC, colbytcook requested changes
@MarcinMr there seems to be more examples that need to be updated here (thanks @remydenton for finding these). Here are an example of a few.
- https://github.com/boltdesignsystem/bolt/blob/feature/DS-602-Remove-pattern_template-Function/docs-site/src/pages/pattern-lab/_patterns/999-archive/product-pages/_product-t3-extra-videos.twig#L653
- https://github.com/boltdesignsystem/bolt/blob/feature/DS-602-Remove-pattern_template-Function/docs-site/src/pages/pattern-lab/_patterns/999-archive/product-pages/_product-t3-extra-videos.twig#L653 

There are examples of some other example being present on the some of the page that you fixed already.
- https://github.com/boltdesignsystem/bolt/blob/feature/DS-602-Remove-pattern_template-Function/docs-site/src/pages/pattern-lab/_patterns/40-components/breadcrumb/15-breadcrumb-use-case-band.twig#L151
- https://github.com/boltdesignsystem/bolt/blob/feature/DS-602-Remove-pattern_template-Function/docs-site/src/pages/pattern-lab/_patterns/40-components/breadcrumb/15-breadcrumb-use-case-band.twig#L240

Please make another pass here and see if there are more examples that need to be updated. Just for your reference you can pretty easily find any errors regarding this by running the `yarn build` command.

2022-04-19 14:49 UTC, MarcinMr commented
@colbytcook @remydenton 

These examples you mentioned above have been corrected. `Yarn build` doesn't throw any errors on my side.

There were a lot of usage `pattern: 'image'` that I missed last time. I rewrite a little bit the `background-item` template to get rid of the `item.pattern = 'image'` statement and the all usage in the docs. I'm not sure if it's done correctly. I created a test page to see if it still works `/?p=tests-background-image`. It seems that for these two scenarios(passing image attributes as an object and pass the whole image as a variable) everything is fine. Let me know what do you think.

2022-04-28 16:42 UTC, colbytcook commented on packages/components/bolt-background/src/background-item.twig
> -        ratio: _ratio_value,
Should this ratio prop be remapped to a Ratio Element?

2022-05-12 15:01 UTC, danielamorse requested changes
@MarcinMr this will be a breaking change and we have to provide instructions for developers downstream on what props have been deprecated (still work but slated for removal) and what props have been removed (deleted and won't work).

There is a lot here, and a lot of very good cleanup, but I'm having trouble identifying the key changes that developers downstream will have to know about in order to pull in this code. Would you please add to the description of this PR exactly what components are affected and what props will change as a result of this PR. I'll use that in my review and we'll include those notes in the 6.x upgrade steps.

For example, here is how `contentItems` is being used in Drupal currently: https://gitlab.com/search?group_id=5804310&scope=blobs&search=%22contentItems%22

This may be a good opportunity to remove this prop completely, as long as we provide upgrade instructions to the Drupal team. Talk more in dev huddle.

cc @mikemai2awesome @remydenton

2022-05-16 20:23 UTC, remydenton commented on packages/components/bolt-background/src/background-item.twig
> -      {% include '@bolt-elements-image/image.twig' with {
The following section of this file actually allows you to pass items beside images:
```
{% elseif (item is iterable) %}
  <div class="{{ 'c-bolt-background__item' }}">
    {{ item }}
  </div>
{% else %}
  {{ item }}
{% endif %}
```
Why the `is iterable` condition?  it's not clear.  It was added in 8ff7e364c, which claims to be just breaking one template into smaller ones.  In any case, it's poor practice to use `is iterable` like this, and I would say the whole file should just look like the following after we're done removing `pattern_template()`:

```
{% if item %}
  <div class="{{ 'c-bolt-background__item' }}">
    {{ item }}
   </div>
{% endif %}
```

Of course, we'll want to leave the existing logic in the PR that is backwards-compatible (for the 5.x branch).  But in both PRs, we should update all pattern lab examples to pass data the correct/new way, that is, like this:
```
{% include '@bolt-elements-image/image.twig' with {
    background: true,
    attributes: {
      alt: 'Alt text.',
      loading: 'lazy',
      src: '/images/content/backgrounds/background-tall-4.jpg',
      width: 3840,
      height: 2160,
    },
  } only %}
{% endset %}
{% include '@bolt-components-background/background.twig' with {
  opacity: 'heavy',
  fill: 'gradient',
  content_items: [
    image
  ]
} only %}
```
:white_check_mark:

i.e. remove/replace all examples that look like this:
```
{% include '@bolt-components-background/background.twig' with {
    opacity: 'heavy',
    fill: 'gradient',
    content_items: [
      {
        alt: 'Alt text.',
        loading: 'lazy',
        src: '/images/content/backgrounds/background-tall-4.jpg',
        width: 3840,
        height: 2160,
      },
    ]
} only %}
```
:x:

2022-05-23 14:05 UTC, MarcinMr commented on packages/components/bolt-background/src/background-item.twig
> -      {% include '@bolt-elements-image/image.twig' with {
Updated examples in pattern lab to use the new way Remy mentioned above

2023-04-06 18:15 UTC, colbytcook commented
https://gitlab.com/pegadigital/bolt/design-system/-/merge_requests/3

2023-04-06 18:15 UTC, closed without merging