[DO NOT MERGE] Audio Player Test
boltdesignsystem/bolt pull request #2482
Opened 2022-04-21 16:29 UTC by colbytcook

## Jira

https://pegadigitalit.atlassian.net/browse/WWW-1304

## Summary

Updated the Bolt Brightcove init functionality to include the audio player

## Details

* Created a testing page
* Modified the Brightcove initialization script to handle the new audio player

## How to test

* Pull Down Branch
* Navigate to '/pattern-lab/?p=tests-audio-player'

2022-04-29 20:02 UTC, remydenton requested changes
Overall looks good, I left a few inline changes/questions.

2022-04-29 20:02 UTC, remydenton commented on packages/website-ui/styleguidekit-twig-default/views/partials/general-footer.twig
> +
+1 for consolidating the scripts here together.

Curious, how come there are two of them?  The answer to that question might be worth a short inline comment.

2022-04-29 20:02 UTC, remydenton commented on docs-site/src/pages/pattern-lab/_patterns/999-tests/video/40-audio-player.twig
> +        data-embed="default"s
Is that trailing `s` intentional?

2022-05-02 11:40 UTC, colbytcook commented on docs-site/src/pages/pattern-lab/_patterns/999-tests/video/40-audio-player.twig
> +    <div class="t-bolt-white" style="padding:20px;">
great suggestion, updated

2022-05-02 11:41 UTC, colbytcook commented on docs-site/src/pages/pattern-lab/_patterns/999-tests/video/40-audio-player.twig
> +        data-embed="default"s
removed

2022-05-02 11:42 UTC, colbytcook commented on packages/website-ui/styleguidekit-twig-default/views/partials/general-footer.twig
> +
Unfortunately I am not sure how we can consolidate these scripts since they are two different BC players. On the Drupal side was can conditionally load these in but on the Bolt side I don't think that is an option (or at least worth our time and energy anyways).

2022-05-02 18:30 UTC, remydenton commented on packages/website-ui/styleguidekit-twig-default/views/partials/general-footer.twig
> +
Makes sense, I say OK to leave it as-is.

2022-05-02 18:32 UTC, remydenton approved these changes

2022-05-02 19:55 UTC, merged