RFC: DS-777 button element type validation
boltdesignsystem/bolt pull request #2483
Opened 2022-05-04 18:48 UTC by remydenton

## Jira

https://pegadigitalit.atlassian.net/browse/DS-777

## Summary

Pilots a new strategy for validation in button elements

## Details

* Previously, when button type and href were both missing, no tag would be set and the button would render with a missing tag.  This PR adds a default type of `button` in that scenario.  If a button like this somehow makes it to prod, it will probably work as originally hoped.
* However, to warn developers that they shouldn't omit the button type, if twig debugging is enabled (we use enable_json_schema_validation as a proxy), the button will be replaced with an error message telling them what's wrong.

## How to test

1. Create a button with no type attribute in pattern lab:
```
{% include '@bolt-elements-button/button.twig' with {
    content: 'This is a button with no "type" attribute',
} only %}
```
2. Confirm that the button is replaced with a fat red error message as long as twig debugging is enabled:
![Screen Shot 2022-05-04 at 2 17 11 PM](https://user-images.githubusercontent.com/677668/166803654-8b819ddf-c25a-4252-8a28-c8ee58e53f05.png)

A similar warning should display if _both_ the `href` and `type` attributes are set.

If twig debugging is disabled (true in the case of the jest test snapshots added in this PR), the buttons should display normally, even though the data passed in is missing critical parts.

2022-05-04 19:15 UTC, mikemai2awesome requested changes
The template looks good, just a few minor adjustments.

2022-05-04 19:15 UTC, mikemai2awesome commented on packages/elements/bolt-button/src/button.twig
> +    {% set error_message = 'The type attribute is required for any button that is not a link'|t %}
Update the copy: "The type attribute is required for a semantic `<button>`, while the href attribute is required for a semantic `<a>`. Please pass one of those attributes."

2022-05-04 19:15 UTC, mikemai2awesome commented on packages/elements/bolt-button/src/button.twig
> +    {% set error_message = 'The type attribute is not supported for buttons that are links'|t %}
Update the copy: "The type attribute should be used for a semantic `<button>`, while the href attribute should be used for a semantic `<a>`. If you have a reason for using both at the same time, please contact the core team."

2022-05-04 19:15 UTC, mikemai2awesome commented on packages/elements/bolt-button/src/button.twig
> +    content: error_message,
Let's add the `close-circle` icon in front of the text.

2022-05-04 19:15 UTC, mikemai2awesome commented on packages/elements/bolt-button/src/button.twig
> + * 3. If type is empty for a button, an error message will be shown in place of the button to remind the developer that type is required.  However, in a prod environment, we will set a default for th
Update copy: "If the type attribute is empty for a semantic <button>, an error message will be shown in place of the button to remind the developer that type is required. However, in a prod environment, we will set a default (type="button") for them to try to recover."

I think I need some explanation on how this works, so we can address @danielamorse's concern about the error message showing up unexpectedly on live pages.

2022-05-04 22:49 UTC, remydenton commented on packages/elements/bolt-button/src/button.twig
> + * 3. If type is empty for a button, an error message will be shown in place of the button to remind the developer that type is required.  However, in a prod environment, we will set a default for th
I've updated the copy.

To explain a little about @danielamorse's concern, the key logic is this:
```
{% if enable_json_schema_validation %}
  ...
  {% set error_message = 'Some message' %}
```

My original assumption before looking into this was that `enable_json_schema_validation` would be false if twig debug mode was set to TRUE.  On further investigation though, that appears to not be the case, and this variable is basically [hard-coded to true](https://github.com/boltdesignsystem/bolt/blob/master/packages/twig-integration/twig-extensions-shared/src/TwigExtensions/BoltCore.php#L40).  I pushed an update to this PR that would update that, but it probably means this should wait for a major release to ensure sites actually pull it in before potentially breaking their buttons.

I think it's still worth getting some reviews and opinions on whether this kind of validation is a good direction to begin with.

2022-05-05 09:49 UTC, adamszalapski approved these changes
From the user's/developer's perspective should we have this error above the button?

2022-05-05 11:14 UTC, colbytcook approved these changes

2022-05-16 21:23 UTC, remydenton commented
I've moved the error after the button instead of replacing the button with the error, as it was doing previously.  Thanks for the feedback on that guys.

@danielamorse `isDebug` is a method on all Twig environments and isn't specific to Bolt.  There's [Drupal documentation](https://api.drupal.org/api/drupal/vendor%21twig%21twig%21lib%21Twig%21Environment.php/function/Twig_Environment%3A%3AisDebug/8.2.x) on it, and [the twig docs ](https://twig.symfony.com/doc/3.x/api.html#environment-options) discuss the `debug` boolean when initializing a Twig environment object.  

Pattern lab sets this this with its own `twigDebug` configuration, which we set to `true` here: https://github.com/boltdesignsystem/bolt/blob/master/docs-site/config/config.yml#L56.  I'm not sure if/how it gets set to `false` for production builds, but in theory it should be.  Originally added in d82d4756e69 ("back out code changes probably not needed" 🤦 ).

TLDR, this is intended to work in both Bolt and Drupal.

2022-05-18 20:31 UTC, danielamorse approved these changes
Thanks for making the update @remydenton.

It looks like `twigDebug` does not actually get set to `false` in Patternlab prod mode. I tested by running `yarn build && yarn serve` and saw the button error message there. Not ideal, but not something I'd bother fixing unless it's a trivial change.

:shipit:

2022-05-18 20:34 UTC, merged