DS-423: Typeahead Button only Clickable When Menu is Open
boltdesignsystem/bolt pull request #2495
Opened 2022-05-26 19:36 UTC by cjwhitedev

## Jira

[https://pegadigitalit.atlassian.net/browse/DS-769](https://pegadigitalit.atlassian.net/browse/DS-769)

## Summary

This PR is to fix the typeahead button still being clickable even when the menu is closed.

## Details

The submit button was still clickable even when the menu was closed. This moves the `pointer-events: all;` line to only be applicable when the menu is open.

## How to test

Follow the steps-to-reproduce shown in the ticket.

2022-05-26 20:16 UTC, mikemai2awesome approved these changes

2022-05-27 13:48 UTC, danielamorse requested changes
I can still click on the "clear text" button:

https://user-images.githubusercontent.com/36336/170712045-a8288eec-91c0-4ebc-9c05-2b07cebf9f24.mov

Would you please look into that?

2022-05-31 20:17 UTC, mikemai2awesome requested changes
@cjwhitedev This only takes care of mouse pointer events, the clear button can still be clicked on/focused on via screen reader after search panel is collapsed. Do we have a more permanent solution?

cc @danielamorse

2022-06-01 19:54 UTC, danielamorse commented
@mikemai2awesome @cjwhitedev this should be fixed now.

We were using the `visibility` CSS property to hide/show the "Clear" button. When you set `visibility: visible` screen readers will speak the element. This happens even if the container is set to `visibility: hidden`. There seemed to be no downside to using `display` instead of `visibility` to hide/show the "Clear" button, so that's what I did.

Once I made that change, I could also remove part of the CSS @cjwhitedev had to add earlier.

This should solve it for mouseover, focus, and screen readers. Please review to verify 🙏

2022-06-02 15:58 UTC, mikemai2awesome approved these changes
This works now! @danielamorse

2022-06-02 17:01 UTC, danielamorse approved these changes

2022-06-02 17:01 UTC, merged