DS-799 Object Inline List deprecation
boltdesignsystem/bolt pull request #2515
Opened 2022-07-14 14:40 UTC by MarcinMr

## Jira

https://pegadigitalit.atlassian.net/browse/DS-799

## Summary

Usage of `o-bolt-inline-list` were replaced with bolt-component `List` as was recommended in the [research ticket](https://pegadigitalit.atlassian.net/browse/DS-652)

## Details

Places where `inline-list object` was updated with Bolt-component `List`:

- form-icons.twig
- event-detail-twig
- 05-footer.twig

## How to test

Check if there are no regressions due to the replacement `inline-list object` with the `List` component.

## Release notes

Object inline-list is deprecated. Please use the Bolt component `List`.

2022-07-26 17:05 UTC, colbytcook commented on packages/components/bolt-form/src/form.scss
> +    var(--bolt-spacing-y-medium) / 2.5 - 0.25rem
@MarcinMr is this change intended? I don't see any mention of it in the description so I wanted to double check.

2022-07-26 17:09 UTC, colbytcook approved these changes
@MarcinMr approved with one minor comment

2022-07-27 07:55 UTC, MarcinMr commented on packages/components/bolt-form/src/form.scss
> +    var(--bolt-spacing-y-medium) / 2.5 - 0.25rem
@colbytcook After replacing `o-bolt-list` with the `list` component I saw a small vertical misalignment of icons inside form input, this is why I adjusted it a little bit.

2022-07-27 16:54 UTC, danielamorse requested changes

2022-07-27 16:54 UTC, danielamorse commented on packages/components/bolt-form/src/form.scss
> +    var(--bolt-spacing-y-medium) / 2.5 - 0.25rem
@MarcinMr minor suggestion: since we're already using one "magic number" here, `.25rem`, I would leave the divisor as `2` and tweak the `.25rem` value as needed.

Also, see Mike's comment on the next line and please update the comment with the new value. You can test the Japanese alignment by changing the `[lang]` tag on the `<html>` element to `lang="ja"`.

2022-07-28 08:24 UTC, MarcinMr commented on packages/components/bolt-form/src/form.scss
> +    var(--bolt-spacing-y-medium) / 2.5 - 0.25rem
@danielamorse thanks for the suggestion, I updated the numbers and comment

2022-07-28 08:28 UTC, MarcinMr commented on packages/components/bolt-form/src/form.scss
> +    var(--bolt-spacing-y-medium) / 2.5 - 0.25rem
**Vertical alignment before changes**
![Old number](https://user-images.githubusercontent.com/85670248/181458794-ac234fef-1453-45a0-b9ac-04313dc9931c.jpg)

**Vertical alignment after changes**
![New number](https://user-images.githubusercontent.com/85670248/181458973-d698ec5b-1299-49d4-8679-edcc54e9a27f.jpg)

2022-07-28 18:06 UTC, danielamorse approved these changes
Nice, thanks @MarcinMr!

2022-07-28 18:06 UTC, merged