DS-811 Wrapper Element
boltdesignsystem/bolt pull request #2522
Opened 2022-08-02 10:18 UTC by MarcinMr

## Jira

https://pegadigitalit.atlassian.net/browse/DS-811

## Summary

A new wrapper element is created.

## Details

A new wrapper is a basic element that contains a basic schema with `content` and `attributes`.

## How to test

Pull the branch. Check the wrapper docs and confirm it's a good equivalent of the old wrapper object.

## Release notes

The new `e-bolt-wrapper` will replace the old `o-bolt-wrapper` object

2022-08-04 16:00 UTC, colbytcook approved these changes
Approved

2022-08-05 13:08 UTC, cjwhitedev approved these changes

2022-08-09 18:25 UTC, danielamorse requested changes
@MarcinMr I left some copy suggestions. If this sounds good, please apply the changes and commit (you can [do this right in Github FYI](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/incorporating-feedback-in-your-pull-request#applying-suggested-changes)).

Otherwise, this looks great!

2022-08-09 18:25 UTC, danielamorse commented on docs-site/src/pages/pattern-lab/_patterns/20-elements/wrapper/05-wrapper.twig
> +    A wrapper has no semantic meaning. This element contains visual elements and content within itself.
```suggestion
  A wrapper provides a max-width for any content passed into it. It has no semantic meaning on its own.
```

2022-08-09 18:25 UTC, danielamorse commented on docs-site/src/pages/pattern-lab/_patterns/20-elements/wrapper/10-wrapper-use-case-custom-max-width.twig
> +  Whenever alternate width is needed use <code>attributes</code> prop and add <code>max-width</code> as an inline style.
```suggestion
  If a custom width is needed use <code>attributes</code> prop and add <code>max-width</code> as an inline style.
```

2022-08-09 18:25 UTC, danielamorse commented on packages/elements/bolt-wrapper/README.md
> +Allows to center content within a page
```suggestion
The Bolt Wrapper element provides a max-width for any content passed into it.
```

2022-08-09 18:25 UTC, danielamorse commented on packages/elements/bolt-wrapper/src/wrapper.scss
> + * Long-form comment.
Please remove the placeholder comment.

2022-08-09 18:25 UTC, danielamorse commented on packages/elements/bolt-wrapper/src/wrapper.scss
> +  // Styles go here. /* [1] */
Please remove the placeholder comment.

2022-08-10 11:14 UTC, MarcinMr commented on packages/elements/bolt-wrapper/src/wrapper.scss
> + * Long-form comment.
change request done

2022-08-10 11:14 UTC, MarcinMr commented on packages/elements/bolt-wrapper/src/wrapper.scss
> +  // Styles go here. /* [1] */
change request done

2022-08-10 11:33 UTC, MarcinMr commented
@danielamorse approved your suggestions

2022-08-10 14:30 UTC, danielamorse approved these changes

2022-08-10 14:31 UTC, merged