DS-733: make tabs show-more button invisble by default
boltdesignsystem/bolt pull request #2529
Opened 2022-08-18 19:49 UTC by cjwhitedev

## Jira

[https://pegadigitalit.atlassian.net/browse/DS-733](https://pegadigitalit.atlassian.net/browse/DS-733)

## Summary

Make the tabs show-more button invisble on page-load to prevent an unstyled flash

## Details

Make the tabs show-more button invisble on page-load to prevent an unstyled flash

## How to test

refresh a page with tabs on it, confirm that you are no longer seeing the more button flash before hiding again.

2022-08-19 09:30 UTC, MarcinMr approved these changes
There isn't any flash of the `more` button when refreshing. I tested also with the dev tools options network fast 3G  and slow 3G, seems like it works nice now.

2022-08-19 15:55 UTC, danielamorse requested changes
@cjwhitedev would you please try out my suggestion and let me know if it works?

2022-08-19 15:55 UTC, danielamorse commented on packages/components/bolt-tabs/src/tabs.js
> +            'is-invisible',
@cjwhitedev thinking about how this works, it would be better if we simply set `is-hidden` here and then left lines 243-247 as is. That way, any time we check the width of the button we also make it invisible, not just on load.

2022-08-22 14:01 UTC, MarcinMr approved these changes
Seems like still works as expected

2022-08-22 21:09 UTC, danielamorse approved these changes

2022-08-22 21:17 UTC, danielamorse approved these changes

2022-08-22 21:19 UTC, merged