DS-839: Add Edit Button to Profile Avatar
boltdesignsystem/bolt pull request #2531
Opened 2022-08-19 16:13 UTC by cjwhitedev

## Jira

[https://pegadigitalit.atlassian.net/browse/DS-839](https://pegadigitalit.atlassian.net/browse/DS-839)

## Summary

(Enter a one-line summary of the changes in this PR. This will be included in the release notes)

## Details

(Explain the changes in enough detail fo reviewers to understand. Raise any questions for reviewers to consider.)

## How to test

(List clear steps to test that the changes are working)

## Release notes

(Optionally, add details that will be added to the release notes. Use this to call out deprecations. [Read more](https://intuit.github.io/auto/docs/generated/changelog#additional-release-notes))

### Visual changes

(Note any visual changes associated with this PR. This will be shared with QA team for VRT.)

2022-08-22 17:48 UTC, colbytcook requested changes
@cjwhitedev I think the hover animation still seems off (we have discussed this previously), fir you confirm this was due to the circle being behind the circle or the scoped element for hover?
Additionally, the behavior when you click is a little jarring. Currently when you click on the edit button it abruptly inverts with the background overlay. Also, icon color does not change so we are left with a white font on light grey background. Could we investigate making this alittle more subtle? The currently click animation of the [Button Element](https://boltdesignsystem.com/pattern-lab/?p=elements-button) just reverts the slight animation adjustment of the button. Is this something we can adjust?

2022-08-22 21:59 UTC, danielamorse requested changes
@cjwhitedev let's talk more in the morning about maybe using a sub-template for the avatar instead. I think that would give us the control we need over the styling of this element and still give users the control they need to add attributes and content to the button.

2022-08-22 21:59 UTC, danielamorse commented on docs-site/src/pages/pattern-lab/_patterns/40-components/profile/15-profile-editable-avatar.twig
> +{% set demo %}
Is this 4-space indentation? Would you please check your VS Code settings if so?

2022-08-22 21:59 UTC, danielamorse commented on packages/components/bolt-profile/profile.schema.js
> +    avatar_edit: {
@cjwhitedev since we want to tightly control the style of the button, I think this would make sense as a sub-template with its own schema. Then you could have props for `content` and `attributes` and the user wouldn't have to build the rest of the button themselves.

2022-08-22 21:59 UTC, danielamorse commented on packages/components/bolt-profile/src/profile.scss
> +        transform: none;
Is `transform: none` to prevent the button from sliding up on hover? If so, would you please add a comment?

2022-08-22 21:59 UTC, danielamorse commented on packages/components/bolt-profile/src/profile.scss
> +      &::after {
We usually do `&:after` instead of `&::after`.

2022-08-23 12:01 UTC, MarcinMr reviewed
When it comes to the animation itself, maybe to make it smoother adding a `will-change: opacity` to the elements that have `transition: opacity var(--bolt-transition);` will help a little bit? Then worth checking if manipulating the speed of the transition and timing-function in this particular case will help. For example, override the `--bolt-transition-timing` like 350ms and maybe play with timing-function like `ease-in` or simply `linear`?

2022-08-23 23:31 UTC, danielamorse requested changes
@cjwhitedev I created a separate branch with some minor edits. Please take a look and merge if it all works for you: `feature/DS-839-editable-profile-avatar--edits`. See my changes [here](https://github.com/boltdesignsystem/bolt/commit/44400997a66a25d034b26f57d26ade3b6f773654).

I renamed a few things for clarity and consistency:
- `@bolt-components-profile/profile-avatar-button.twig` => `@bolt-components-profile/profile-avatar-edit-button.twig`
- `avatar_button` => `avatar_edit_button`
- `profile-editable-avatar.twig` => `profile-avatar-edit-button.twig`

I also added a missing Drupal `|t` function and updated some copy.

Next steps:
- Any animation updates you had in mind
- Edit button should show on focus as well as on hover
- Add an initial class to the button and target that class instead of `> *`

2022-08-25 21:52 UTC, danielamorse commented
> When it comes to the animation itself, maybe to make it smoother...

@MarcinMr good suggestion. I tried this but `will-change` also affected the z-index stacking order which made it impossible to position the pseudo element below the button.

2022-08-25 21:56 UTC, danielamorse commented
@cjwhitedev @MarcinMr I pushed changes that smooth out the animation, [see commit](https://github.com/boltdesignsystem/bolt/pull/2531/commits/954f6562234422da31c629b231503665ff0f604a).

It uses the pseudo element to make the whole avatar hoverable and uses a sibling `<span>` to apply the animation. This was the only way I could get the animation to be smooth. In some cases it seems fine to animate an element _and_ its pseudo-element, and it runs smoothly. In this case, perhaps because of the z-index requirements, it gets choppy. So, this is a work around, but I'm ok with it.

Would you please review the code and cross-browser test? We will aim to release this on Monday 🙏

2022-08-25 21:56 UTC, danielamorse approved these changes

2022-08-26 10:57 UTC, MarcinMr approved these changes
I think this solution works well now :). The animation is smoother than before. I also tested using chrome tools. Slowing down the animation to 25% or 10% still looks smooth. Testing with dev tools performance monitor and rendering doesn't show any issues when hovering. Tested on Chrome, Safari, and FF.

2022-08-29 19:43 UTC, merged