DS 835 table basic
boltdesignsystem/bolt pull request #2548
Opened 2022-09-28 12:39 UTC by MarcinMr

## Jira

https://pegadigitalit.atlassian.net/browse/DS-835

## Summary

The new component `table-basic` is created that can replace the basic functionalities of the current Table Component

## Details
1. Much of the props are taken from the old table component, for example:

- only rows table
- table with top headers only
- table with side headers only
- table with both top and side headers
- caption of the table
- borderless table
- format table (regular, numeric)

2. The following methods of display

- Twig (appearance and behavior can be achieved via choosing props from the schema)
- HTML only (appearance and behavior can be achieved by adding appropriate classes to the `<table>`)
- HTML only (without the **tbody**) (appearance and behavior can be achieved by adding appropriate classes to the `<table>`)

3. Js creates a wrapper and wraps the `<table>`
4. Table can have responsive behavior (with the horizontal scrollbar) or be set as 100% width of the container(by choosing the appropriate prop) and squeezes when window width is decreasing
5. There are props that set the first, second, or first two columns as fixed width

## How to test

Pull the branch. Check the code, especially the CSS and JS. Check the `table-basic` template. Go to test folder and find table-basic test examples. Play with them and confirm the work properly. 

_Note that we don't have the docs yet, After everything works fine in the test pages we can add the docs later.

## Release notes

There is a new tablep-basic component that replaces the basic functionalities of the current Table Component

2022-10-11 21:08 UTC, colbytcook approved these changes

2022-10-12 12:41 UTC, adamszalapski approved these changes
Looks good, few comments but they are not mandatory.

2022-10-12 12:41 UTC, adamszalapski commented on packages/components/bolt-table-basic/__tests__/table-basic.js
> +  fixed_width_table,
In other components, we use the camelCase approach, why we don't do this here?

2022-10-12 12:41 UTC, adamszalapski commented on packages/components/bolt-table-basic/__tests__/table-basic.js
> +  fixed_width_columns,
In other components, we use the camelCase approach, why we don't do this here?

2022-10-12 12:41 UTC, adamszalapski commented on packages/components/bolt-table-basic/src/table-basic.scss
> +    // &:first-child:empty ~ td {
We should remove all commented/unused code

2022-10-12 17:55 UTC, cjwhitedev requested changes

2022-10-12 17:55 UTC, cjwhitedev commented on docs-site/src/pages/pattern-lab/_patterns/20-elements/table/15-table-side-header.twig
> +    <bolt-li>The Table Element is designed to work with both Twig and vanilla HTML (Twig is the recommended method).</bolt-li>
i dont think we need this line on every demo

2022-10-12 17:55 UTC, cjwhitedev commented on docs-site/src/pages/pattern-lab/_patterns/20-elements/table/30-table-format-variations.twig
> +{% set demo %}
the demo isnt rendering for me, is anyone else having the same problem?

2022-10-12 17:55 UTC, cjwhitedev commented on docs-site/src/pages/pattern-lab/_patterns/20-elements/table/35-table-borderless.twig
> +          'The awe-inspiring leader of the Autobot forces. Selfless and endlessly courageous, he is the complete opposite of his mortal enemy Megatron.',
this content seems weird for this demo, it doesnt show the removed borders as well as shorter content might

2022-10-12 17:55 UTC, cjwhitedev commented on docs-site/src/pages/pattern-lab/_patterns/20-elements/table/45-table-column-fixed-width.twig
> +{% set demo %}
i cant see a difference between any of these demos until the last one.

2022-10-12 22:24 UTC, danielamorse requested changes
As we discussed on Slack, we probably want to base the Table element on the work @MarcinMr did in https://github.com/boltdesignsystem/bolt/pull/2437 rather than the current Table component. That work has many nice improvements to CSS, the schema, etc. Since you're making a new "element" we don't have to worry about introducing breaking changes.

2022-10-17 12:02 UTC, colbytcook commented on packages/components/bolt-table-basic/__tests__/table-basic.js
> +  fixed_width_columns,
Same as the previous comment

2022-10-17 12:04 UTC, colbytcook commented on docs-site/src/pages/pattern-lab/_patterns/20-elements/table/15-table-side-header.twig
> +    <bolt-li>The Table Element is designed to work with both Twig and vanilla HTML (Twig is the recommended method).</bolt-li>
Removed

2022-10-17 12:04 UTC, colbytcook commented on docs-site/src/pages/pattern-lab/_patterns/20-elements/table/30-table-format-variations.twig
> +{% set demo %}
This should be fixed now

2022-10-17 12:05 UTC, colbytcook commented on docs-site/src/pages/pattern-lab/_patterns/20-elements/table/45-table-column-fixed-width.twig
> +{% set demo %}
This is updated

2022-10-17 13:19 UTC, cjwhitedev reviewed
- For the caption: is this what we want it to look like? it doesnt have a border in the component version. also the rounded corners in this version are abutted to the the table and i dont think thats what we're going for.
- the sticky header is not working for me in firefox dev, i know i saw it working on @colbytcook's screen share though.
- i like the red in the fix width section, just wondering if we should put a note that says its only there for demo purposes?

2022-10-17 14:19 UTC, colbytcook commented
@cjwhitedev Updated the "Fixed Width" page with the note.

2022-10-17 21:18 UTC, danielamorse requested changes
@colbytcook, I reviewed the docs and noticed:
- Docs > Table Examples: The full-width tables aren't full width.
- Tests > Table Default html: The tables are full-width until the JS loads. I think @MarcinMr  works around this [on the 6.x branch](https://release-6-x.boltdesignsystem.com/pattern-lab/?p=components-table-column-width) by scoping the `width: 100%` rule to `.c-bolt-table > table`, or in your case `e-bolt-table-wrapper > .e-bolt-table`.

These are the only issues I found. Here are a couple other thoughts, not blockers:

**Full-width tables in wysiwyg**
If I'm a content author and I make a plain HTML table and I want it to be width 100% (and I'm not going to edit the raw markup), how do I do this? Since the "full-width" style comes from the wrapper and the wrapper is added by JS I don't think there's anything in place to support full-width tables for a non-power-user. To solve that we'd have to check for some additional class on the `<table>` itself. Is this a use case we are solving for? Any thoughts?

**Wrapper full-width classname**
To make the container full-width I'd actually go with `u-bolt-block`, like @MarcinMr did on the 6.x branch. I didn't realize that literally the only thing this wrapper had to do was set `display: block`. Alternatively, if you prefer a component class, maybe `e-bolt-table-wrapper--full-width` would tell the user more about what it does?

2022-10-18 00:40 UTC, colbytcook commented
@danielamorse I addressed the feedback you had

* Docs > Table Examples: the full width tables now render full width
* Tests > Table Default html: Updated the CSS to stop the flashes

Full Width Prop
I added a `full_width` prop into the schema that will do three things.
1. It will add a `e-bolt-table--full-width` class to the `<table>`. This class will apply a `width: 100%;` to the table to help prevent flash. 
2. The `table.twig` will now apply a `e-bolt-table-wrapper--full-width` class to the `e-bolt-table-wrapper` that will make the wrapper display block (and forcing it to be full width). 
3. The table JS will now poll the `<table>` for the `e-bolt-table--full-width` class and add the `e-bolt-table-wrapper--full-width` class to the wrapper when it is being rendered.

For WYSIWYG support, we can simply add a class (`e-bolt-table--full-width`) to the table element to achieve the desired effect.

I updated the existing docs pages with these changes (where applicable) and created a new documentation page for the full width prop. Let me know if you have any other questions regarding this.

2022-10-18 13:16 UTC, cjwhitedev reviewed
- i think the PR description needs to be updated again, at least since adding the full_width prop, if not more than that.
- see inline comment as well

2022-10-18 13:51 UTC, colbytcook commented on docs-site/src/pages/pattern-lab/_patterns/20-elements/table/00-table-docs.twig
> +{% set usage %}{% verbatim %}
@cjwhitedev I don't mind this initial demo page being longer than Layouts because layout examples are larger scoped than a table.

2022-10-18 13:55 UTC, colbytcook commented
@cjwhitedev Updated the PR description and responded to your inline comment

2022-10-18 13:56 UTC, cjwhitedev approved these changes

2022-10-18 14:03 UTC, merged

2022-10-18 16:49 UTC, remydenton commented on packages/elements/bolt-table/table-cell.schema.js
> +    filters: {
Is `filters` a real prop?  I don't see it used in the twig template or any of the examples.