DS-835: Table Sticky Top Bugfix
boltdesignsystem/bolt pull request #2559
Opened 2022-10-18 18:08 UTC by colbytcook

## Summary

Fixed a bug where the sticky top header would go behind the rows.

## Details

Removed a unneeded CSS on the `tr` that was causing this issue.

## How to test

Pull down the branch
Navigate to the `/pattern-lab/?p=tests-table-support-center` page
Scroll down on the table and observe that the top header is sticking

2022-10-18 19:37 UTC, danielamorse requested changes

2022-10-18 19:37 UTC, danielamorse commented on packages/elements/bolt-table/src/table.scss
> +      position: relative;
This rule breaks the stickiness of the side headers.

2022-10-18 19:37 UTC, danielamorse commented on packages/elements/bolt-table/src/table.scss
> +    z-index: 2;
`z-index: 1` seems to work for me once I remove the `position: relative` rule above. Does that work for you or am I missing something?

2022-10-19 11:14 UTC, colbytcook commented on packages/elements/bolt-table/src/table.scss
> +      position: relative;
This is now removed

2022-10-19 11:15 UTC, colbytcook commented on packages/elements/bolt-table/src/table.scss
> +    z-index: 2;
The z-indexes are now removed

2022-10-19 11:16 UTC, colbytcook commented
@danielamorse @MarcinMr I added the `min-width :0` to the `.l-bolt-site > *:only-child` selector to fix the bug. Can you please review again?

2022-10-19 11:55 UTC, MarcinMr approved these changes
Seems like scrolling behavior works for the table

2022-10-19 13:28 UTC, danielamorse commented on packages/elements/bolt-table/src/table.scss
> +    z-index: 2;
Cool, I was saying just to remove this one but I actually don't see any bugs with them both removed.

2022-10-19 13:28 UTC, danielamorse approved these changes

2022-10-19 13:38 UTC, merged