DS 889: Drupal Admin UI Paternlab Section
boltdesignsystem/bolt pull request #2579
Opened 2022-11-29 13:18 UTC by MarcinMr

## Jira

https://pegadigitalit.atlassian.net/browse/DS-889

## Summary

There's a new section Drupal Admin UI in the pattern lab navigation which contains the UX builds of the Drupal Admin panels for the new Layout Builder project.

## Details

**1. In the Bolt, we have a new section with UX builds:**
 - text paragraph
 - icon paragraph
 - image paragraph
 - button paragraph
 - blockquote paragraph
 - list paragraph
 - action blocks paragraph
 - tabs and accordion paragraph
 
 These above were recreated from the private Codepen.
 
 **2. The animation tab was updated and is now similar to this one which can be found here** https://shdemo2.pega.com/node/add/layout_page
*it's possible that this can be updated again in the future

## How to test

Pull the branch. Look at the Drupal admin UI section. Go thru all component examples and confirm that there are the same as Codepen examples.

## Release notes

We have a new Drupal admin UI section in the pattern lab navigation.

2022-11-29 15:06 UTC, MarcinMr commented
@remydenton 

I transferred Codepen's examples to the Bolt, it's ready to take a look at this

2022-11-29 20:12 UTC, remydenton requested changes
This looks really nice @MarcinMr , nice work.  I have the following updates:
1. One nitpitpick inline comment about a typo
2. Updates to make to the animations tab that I posted on the JIRA ticket so Matt could see: https://pegadigitalit.atlassian.net/browse/DS-889?focusedCommentId=65673 
3. One additional question, should we make this new section hidden/shown alongside the `test` and `archive` sections?  My thinking is that it is really only for a few people (me, Andrew, Matt), whereas the rest of the system should be useful to most developers and designers.  Thoughts on that @colbytcook @danielamorse ?

2022-11-30 14:03 UTC, MarcinMr commented on docs-site/src/pages/pattern-lab/_patterns/70-drupal-admin-user-interface/35-tabs-and-accrodion-paragraph.twig
> +{% extends "_drupal-admin-ui-template.twig" %}
Regards point 3, I was also wondering if this should be hidden or visible

2022-11-30 16:06 UTC, remydenton commented on docs-site/src/pages/pattern-lab/_patterns/70-drupal-admin-user-interface/35-tabs-and-accrodion-paragraph.twig
> +{% extends "_drupal-admin-ui-template.twig" %}
Let's discuss briefly in dev huddle

2022-12-02 00:03 UTC, remydenton approved these changes
Updates look good, thank you @MarcinMr.

For what it's worth, I had the same behavior in your screencast (wrong tabs display) when not in incognito mode.  After I cleared local storage in developer tools, it worked as expected.

2022-12-02 00:05 UTC, merged